Repository openucx/ucx, pull requests merged in 2018-12, with the labels that each got.

#3056 UCP: Optimize resources for homogeneous clusters
  src/ucp/core/ucp_context.c
  src/ucp/core/ucp_context.h
  src/ucp/core/ucp_ep.c
  src/ucp/core/ucp_ep.inl
  src/ucp/core/ucp_listener.c
  src/ucp/core/ucp_mm.h
  src/ucp/core/ucp_rkey.c
  src/ucp/core/ucp_types.h
  src/ucp/core/ucp_worker.c
  src/ucp/core/ucp_worker.h
  src/ucp/proto/proto_am.inl
  src/ucp/rma/flush.c
  src/ucp/tag/rndv.c
  src/ucp/wireup/address.c
  src/ucp/wireup/select.c
  src/ucp/wireup/wireup.c
  src/ucp/wireup/wireup.h
  src/ucp/wireup/wireup_ep.c
  src/ucs/arch/bitops.h
  test/gtest/ucp/test_ucp_wireup.cc
Labels: Optimization

#3060 Remove HW TM support from rc_verbs
  src/uct/Makefile.am
  src/uct/ib/dc/base/dc_iface.h
  src/uct/ib/rc/verbs/rc_verbs.h
  src/uct/ib/rc/verbs/rc_verbs_common.c
  src/uct/ib/rc/verbs/rc_verbs_common.h
  src/uct/ib/rc/verbs/rc_verbs_ep.c
  src/uct/ib/rc/verbs/rc_verbs_iface.c
  src/uct/ib/rc/verbs/rc_verbs_impl.h
Labels: Cleanup

#3069 UCT/IB/RC: Scatter to CQE upstream support
  config/m4/ib.m4
  src/uct/ib/dc/accel/dc_mlx5.c
  src/uct/ib/rc/accel/rc_mlx5_ep.c
  src/uct/ib/rc/accel/rc_mlx5_iface.c
  src/uct/ib/rc/base/rc_ep.c
  src/uct/ib/rc/base/rc_ep.h
  src/uct/ib/rc/base/rc_iface.h
  src/uct/ib/rc/verbs/rc_verbs_ep.c
Labels: Optimization, Waiting for Author Response

#3083 TEST/JENKINS: Use correct options for ucx_perftest
  Makefile.am
  contrib/test_jenkins.sh
  contrib/ucx_perftest_config/README
  contrib/ucx_perftest_config/test_types_ucp
  contrib/ucx_perftest_config/test_types_uct
  src/tools/perf/Makefile.am
Labels: Ready for Review

#3067 UCP/WORKER: refactoring of MT locking
  src/tools/info/tl_info.c
  src/tools/perf/perftest.c
  src/ucp/core/ucp_ep.c
  src/ucp/core/ucp_listener.c
  src/ucp/core/ucp_thread.h
  src/ucp/core/ucp_worker.c
  src/ucp/core/ucp_worker.h
  src/ucs/async/async.c
  src/ucs/async/async.h
  src/ucs/async/async_int.h
  src/ucs/async/thread.c
  src/ucs/async/thread.h
  src/ucs/config/parser.c
  src/ucs/config/types.h
  src/uct/ib/base/ib_device.c
  src/uct/ib/cm/cm.h
  src/uct/ib/cm/cm_iface.c
  test/gtest/common/test_perf.cc
  test/gtest/ucs/test_async.cc
  test/gtest/uct/test_flush.cc
  test/gtest/uct/test_uct_ep.cc
  test/gtest/uct/uct_test.cc
Labels: Ready for Review

#3092 UCS/TEST: Fix segfault in UCP, due to int truncation in count_one_bits()
  src/ucp/core/ucp_mm.c
  src/ucp/core/ucp_request.c
  src/ucp/core/ucp_request.inl
  src/ucp/core/ucp_rkey.c
  src/ucp/core/ucp_worker.c
  src/ucp/tag/rndv.c
  src/ucp/wireup/select.c
  src/ucs/arch/bitops.h
  src/uct/sm/mm/mm_iface.c
  test/gtest/ucs/test_math.cc
Labels: Bugfix

#3090 UCS: Check rdtsc on the very first ucs_time call
  src/ucs/arch/x86_64/cpu.c
  src/ucs/arch/x86_64/cpu.h
  src/ucs/config/global_opts.c
  src/ucs/config/global_opts.h
  src/ucs/sys/sys.c
  test/gtest/ucp/ucp_test.cc
  test/gtest/ucs/test_stats_filter.cc
Labels: Bugfix, Ready for Review
