Repository openucx/ucx, pull requests merged in 2018-10, with the labels that each got.

#2901 UCT/RDMACM/EP: fix a race condition on ops queue
  src/uct/ib/rdmacm/rdmacm_ep.c
  src/uct/ib/rdmacm/rdmacm_ep.h
  src/uct/ib/rdmacm/rdmacm_iface.c
Labels: Bugfix

#2905 TEST: fixed stats test
  test/gtest/ucs/test_stats_filter.cc
Labels: Bugfix

#2907 UCP/TAG: Profile tag offload callbacks
  src/ucp/tag/offload.c
Labels: Enhancement

#2879 CONFIG: Adding ThunderX2 compile time tunings
  config/m4/compiler.m4
Labels: Optimization

#2909 TEST/GTEST: Fix test failures with default configure parameters
  test/gtest/common/test_obj_size.cc
  test/gtest/ucp/test_ucp_wireup.cc
Labels: Bugfix, Test

#2908 TEST: fixed stats test - v1.4.x
  test/gtest/ucs/test_stats_filter.cc
Labels: Bugfix

#2897 UCP/TAG: Hash tags coming to offload-capable iface
  src/ucp/core/ucp_worker.c
  src/ucp/core/ucp_worker.h
  src/ucp/tag/eager_rcv.c
  src/ucp/tag/offload.c
  src/ucp/tag/offload.h
  src/ucp/tag/tag_match.c
  src/ucp/tag/tag_match.h
  test/gtest/ucp/test_ucp_tag_offload.cc
Labels: Optimization, Ready for Review

#2848 MEM-HOOKS/BISTRO: added runtime to hook calls using BISTRO
  config/m4/ucm.m4
  src/ucm/api/ucm.h
  src/ucm/bistro/bistro.c
  src/ucm/event/event.c
  src/ucm/malloc/malloc_hook.c
  src/ucm/mmap/install.c
  src/ucm/mmap/mmap.h
  src/ucm/util/replace.c
  src/ucm/util/replace.h
  src/ucm/util/sys.c
  src/ucs/config/ucm_opts.c
  test/gtest/ucm/malloc_hook.cc
Labels: Enhancement

#2916 UCT/IB/MLX5: Don't include mlx5dv.h unless supported
  config/m4/ib.m4
Labels: Bugfix, Critical v1.4.x

#2920 NEWS: Updating news file with known issues
  NEWS
Labels: Documentation

#2927 TEST/UCT: Skip p2p_am tests if transport has AM_DUP flag
  test/gtest/uct/test_p2p_am.cc
Labels: Bugfix, Test

#2926 CONTRIB: Add valgrind param check suppression for ibv_exp_cmd_free_dm
  contrib/valgrind.supp
Labels: Test

#2904 TESTS: added test for nested dlopen processing
  configure.ac
  test/gtest/Makefile.am
  test/gtest/ucm/malloc_hook.cc
  test/gtest/ucm/test_dlopen/Makefile.am
  test/gtest/ucm/test_dlopen/dlopen_test_do_load.c
  test/gtest/ucm/test_dlopen/dlopen_test_do_mmap.c
Labels: Test

#2925 TESTS: fixed tests for bistro-multithread
  test/gtest/ucm/malloc_hook.cc
Labels: Bugfix, Test

#2889 UCP/LISTENER: implement client-server connection request flow
  src/ucp/core/ucp_ep.c
  src/ucp/core/ucp_ep.h
  src/ucp/core/ucp_ep.inl
  src/ucp/core/ucp_listener.c
  src/ucp/core/ucp_listener.h
  src/ucp/core/ucp_worker.c
  src/ucp/core/ucp_worker.h
  src/ucp/stream/stream.h
  src/ucp/stream/stream_recv.c
  src/ucp/wireup/ep_match.c
  src/ucp/wireup/wireup.c
  src/ucp/wireup/wireup_ep.c
  src/ucp/wireup/wireup_ep.h
  src/ucs/type/status.c
Labels: Feature, Waiting for Author Response

#2929 GTEST: restrict cuda_copy uct to test RMA only with cuda target buffer
  test/gtest/uct/uct_p2p_test.cc
Labels: Bugfix

#2930 TEST: fixed build by latest compiler
  test/gtest/ucm/malloc_hook.cc
Labels: Bugfix, Test

#2877 UCP/UCT/UCM: Managed memory support
  src/tools/perf/libperf.c
  src/tools/perf/perftest.c
  src/tools/perf/ucp_tests.cc
  src/ucp/core/ucp_context.c
  src/ucp/core/ucp_mm.h
  src/ucp/core/ucp_request.inl
  src/ucp/dt/dt.c
  src/ucp/dt/dt.inl
  src/uct/api/uct.h
  test/gtest/uct/test_md.cc
Labels: API, Enhancement, Waiting for Author Response

#2933 GTEST: extended allowed tag sync mr range
  test/gtest/ucp/test_ucp_perf.cc
Labels: Test

#2935 TEST/UD: Fix failure in crep_ack_drop test
  test/gtest/uct/ib/test_ud.cc
Labels: Bugfix, Test

#2931 GTEST/MALLOC_HOOKS: added barrier to test exit
  test/gtest/ucm/malloc_hook.cc
Labels: Bugfix, Test

#2944 UCS/PROFILE: Fix 'accum' profiling mode
  src/ucs/profile/profile.c
Labels: Bugfix

#2943 TEST/ASYNC: Do several retries with waiting for timer events
  test/gtest/ucs/test_async.cc
Labels: Bugfix, Test

#2942 UCT/IB/MLX5: Accel requires CQ ignore overrun
  config/m4/ib.m4
Labels: Bugfix, Critical v1.4.x

#2945 UCP/TAG/PROFILE: Profile tag post and tag cancel
  src/ucp/tag/offload.c
Labels: Enhancement

#2827 UCP/UCT/IB: Fix thread mode in UCT
  src/tools/info/tl_info.c
  src/ucp/core/ucp_worker.c
  src/ucs/arch/aarch64/cpu.h
  src/ucs/arch/ppc64/cpu.h
  src/ucs/arch/x86_64/cpu.h
  src/uct/ib/base/ib_iface.c
  src/uct/ib/mlx5/ib_mlx5.c
  src/uct/ib/mlx5/ib_mlx5.h
  src/uct/ib/mlx5/ib_mlx5.inl
  src/uct/sm/mm/mm_iface.c
  src/uct/sm/self/self.c
  src/uct/tcp/tcp_iface.c
  test/gtest/uct/uct_test.cc
Labels: Bugfix, Critical v1.4.x, Ready for Review

#2932 GTEST/UCP: client/server API with connection handle testing
  src/ucp/core/ucp_listener.c
  test/gtest/ucp/test_ucp_sockaddr.cc
  test/gtest/ucp/ucp_test.cc
  test/gtest/ucp/ucp_test.h
Labels: Test, Waiting for Author Response

#2948 Backporting CUDA fixes to v1.4.x
  contrib/test_jenkins.sh
  test/gtest/uct/uct_p2p_test.cc
Labels: Bugfix, Critical v1.4.x

#2922 CONTRIB/JENKINS: Add build test with latest gcc
  contrib/test_jenkins.sh
Labels: Test

#2947 UCP/UCT/IB: Fix thread mode in UCT - v1.4.x
  src/tools/info/tl_info.c
  src/ucp/core/ucp_worker.c
  src/ucs/arch/aarch64/cpu.h
  src/ucs/arch/ppc64/cpu.h
  src/ucs/arch/x86_64/cpu.h
  src/uct/ib/base/ib_iface.c
  src/uct/ib/mlx5/ib_mlx5.c
  src/uct/ib/mlx5/ib_mlx5.h
  src/uct/ib/mlx5/ib_mlx5.inl
  src/uct/sm/mm/mm_iface.c
  src/uct/sm/self/self.c
  src/uct/tcp/tcp_iface.c
  test/gtest/uct/uct_test.cc
Labels: Bugfix, Critical v1.4.x

#2949 Backport build bugs
  config/m4/ib.m4
Labels: Critical v1.4.x

#2950 UCP/UCT: CUDA Managed memory support
  src/ucp/core/ucp_context.c
  src/ucp/core/ucp_mm.h
  src/ucp/core/ucp_request.inl
  src/ucp/dt/dt.c
  src/ucp/dt/dt.inl
  src/uct/api/uct.h
  test/gtest/uct/test_md.cc
Labels: Critical v1.4.x, Ready for Review

#2957 NEWS: Update for rc1
  NEWS
Labels: Documentation

#2956 IB/AMO: removed duplicating indirect AMO conf
  src/uct/ib/base/ib_md.c
  src/uct/ib/base/ib_md.h
Labels: Cleanup

#2954 UCT/IB/TEST: Support non-inline KLM list
  src/ucs/config/parser.c
  src/uct/ib/base/ib_md.c
  src/uct/ib/base/ib_md.h
  test/gtest/uct/ib/test_ib_md.cc
  test/gtest/uct/test_md.cc
  test/gtest/uct/test_md.h
Labels: Bugfix

#2952 UCP/AM: fix zcopy_multi protocol for iov datatype
  src/ucp/proto/proto_am.inl
  test/gtest/ucp/test_ucp_stream.cc
  test/gtest/ucp/ucp_datatype.h
Labels: Bugfix

#2958 GTEST: refactor log handlers using RAII idiom
  src/ucs/debug/log.c
  src/ucs/debug/log.h
  test/gtest/common/test.cc
  test/gtest/common/test.h
  test/gtest/ucp/test_ucp_atomic.cc
  test/gtest/ucp/test_ucp_context.cc
  test/gtest/ucp/test_ucp_mmap.cc
  test/gtest/ucp/test_ucp_peer_failure.cc
  test/gtest/ucp/test_ucp_sockaddr.cc
  test/gtest/ucp/ucp_test.cc
  test/gtest/ucs/test_async.cc
  test/gtest/ucs/test_log.cc
  test/gtest/uct/ib/test_sockaddr.cc
  test/gtest/uct/test_p2p_err.cc
  test/gtest/uct/test_peer_failure.cc
  test/gtest/uct/uct_test.cc
Labels: Bugfix, Test

#2838 DC with upstream
  config/m4/ib.m4
  configure.ac
  src/tools/info/type_info.c
  src/uct/Makefile.am
  src/uct/ib/base/ib_device.c
  src/uct/ib/base/ib_device.h
  src/uct/ib/base/ib_iface.c
  src/uct/ib/base/ib_iface.h
  src/uct/ib/base/ib_log.c
  src/uct/ib/base/ib_log.h
  src/uct/ib/base/ib_verbs.h
  src/uct/ib/dc/accel/dc_mlx5.c
  src/uct/ib/dc/accel/dc_mlx5.h
  src/uct/ib/dc/base/dc_iface.c
  src/uct/ib/dc/base/dc_iface.h
  src/uct/ib/dc/verbs/dc_verbs.c
  src/uct/ib/mlx5/ib_mlx5.h
  src/uct/ib/mlx5/ib_mlx5.inl
  src/uct/ib/mlx5/ib_mlx5_dv.c
  src/uct/ib/mlx5/ib_mlx5_log.c
  src/uct/ib/mlx5/ib_mlx5_log.h
  src/uct/ib/rc/accel/rc_mlx5_common.c
  src/uct/ib/rc/accel/rc_mlx5_common.h
  src/uct/ib/rc/accel/rc_mlx5_iface.c
  src/uct/ib/rc/base/rc_iface.c
  src/uct/ib/rc/base/rc_iface.h
  src/uct/ib/rc/verbs/rc_verbs_common.c
  src/uct/ib/rc/verbs/rc_verbs_iface.c
  src/uct/ib/ud/accel/ud_mlx5.c
  src/uct/ib/ud/base/ud_iface.c
  src/uct/ib/ud/verbs/ud_verbs.c
  test/apps/test_ucx_tls.py
  test/gtest/ucp/test_ucp_tag_xfer.cc
  test/gtest/uct/test_uct_ep.cc
Labels: Feature, Waiting for Author Response

#2961 GTEST: log handlers, part 2
  src/ucs/debug/log.c
  src/ucs/debug/log.h
  test/gtest/common/test.cc
  test/gtest/ucp/test_ucp_atomic.cc
  test/gtest/ucp/test_ucp_sockaddr.cc
Labels: Bugfix, Ready for Review, Test

#2959 NEWS: News file sync with v1.4.0 tree
  NEWS
Labels: Documentation

#2938 UCT/API: remove redundant UCT_CB_FLAG_SYNC
  src/tools/perf/libperf.c
  src/tools/perf/uct_tests.cc
  src/ucp/core/ucp_worker.c
  src/ucp/rma/amo_sw.c
  src/ucp/rma/rma_sw.c
  src/ucp/stream/stream_recv.c
  src/ucp/tag/eager_rcv.c
  src/ucp/tag/rndv.c
  src/uct/api/uct.h
  src/uct/base/uct_iface.c
  src/uct/base/uct_iface.h
  src/uct/ib/rdmacm/rdmacm_ep.c
  src/uct/ib/rdmacm/rdmacm_iface.c
  src/uct/ib/ud/base/ud_ep.c
  test/examples/uct_hello_world.c
  test/gtest/uct/ib/test_cq_moderation.cc
  test/gtest/uct/ib/test_dc.cc
  test/gtest/uct/ib/test_ib.cc
  test/gtest/uct/ib/test_rc.cc
  test/gtest/uct/ib/test_sockaddr.cc
  test/gtest/uct/test_event.cc
  test/gtest/uct/test_many2one_am.cc
  test/gtest/uct/test_mm.cc
  test/gtest/uct/test_p2p_am.cc
  test/gtest/uct/test_peer_failure.cc
  test/gtest/uct/test_pending.cc
  test/gtest/uct/test_tag.cc
  test/gtest/uct/uct_test.cc
Labels: API, Cleanup, Ready for Review

#2962 GTEST: fix test_ucp_stream_many2one.drop_data
  test/gtest/ucp/test_ucp_stream.cc
Labels: Bugfix, Ready for Review, Test

#2960 UCT/ACCEL: Avoid slow path when no CQE ready
  src/uct/ib/mlx5/ib_mlx5.c
  src/uct/ib/mlx5/ib_mlx5.inl
  src/uct/ib/rc/accel/rc_mlx5_common.c
  src/uct/ib/rc/accel/rc_mlx5_common.h
Labels: Optimization, Ready for Review

#2971 UCS/UCT: Better error message for memory allocaiton failures
  src/ucs/datastruct/mpool.c
  src/ucs/sys/sys.c
  src/ucs/sys/sys.h
  src/uct/base/uct_md.c
  src/uct/base/uct_md.h
  src/uct/base/uct_mem.c
  src/uct/ib/base/ib_md.c
  src/uct/sm/mm/mm_iface.c
  src/uct/sm/mm/mm_md.c
  src/uct/sm/mm/mm_md.h
  src/uct/sm/mm/mm_posix.c
  src/uct/sm/mm/mm_sysv.c
  src/uct/sm/mm/mm_xpmem.c
  test/gtest/ucs/test_memtrack.cc
Labels: Enhancement

#2968 UCS/QUEUE: Fix ucs_queue_for_each() with armclang
  contrib/test_jenkins.sh
  src/ucs/datastruct/queue.h
  test/gtest/ucs/test_datatype.cc
Labels: Bugfix, Critical v1.4.x

#2972 UCP/UCS: Warn about unused environment variables at ucp_worker_create()
  contrib/test_jenkins.sh
  src/ucp/core/ucp_worker.c
  src/ucs/config/parser.c
  src/ucs/sys/init.c
  test/gtest/common/main.cc
Labels: Bugfix

#2977 #2968 backport
  contrib/test_jenkins.sh
  src/ucs/datastruct/queue.h
  test/gtest/ucs/test_datatype.cc
Labels: Bugfix, Critical v1.4.x

#2978 NEWS: RC2 updates
  NEWS
Labels: Critical v1.4.x

#2974 UCS/CONFIG: Print configuration hierarchy
  src/ucs/config/parser.c
Labels: Documentation

#2983 UCP: Optimize mem type detection for non-CUDA case
  src/ucp/core/ucp_context.h
Labels: Optimization, Ready for Review

#2980 TOOLS/INFO: Fix CPU model info for aarch64
  contrib/test_jenkins.sh
  src/tools/info/sys_info.c
Labels: Bugfix

#2988 Enable M option
  src/tools/perf/perftest.c
Labels: Bugfix

#2997 NEWS: Minor typo fix before release
  NEWS
Labels: Critical v1.4.x

#2998 UCT/UD: Fix out-of-order with pending queue
  src/ucs/datastruct/arbiter.h
  src/uct/ib/ud/base/ud_ep.c
  src/uct/ib/ud/base/ud_inl.h
Labels: Bugfix
