Repository openucx/ucx, pull requests merged in 2018-06, with the labels that each got.

#2659 GTEST: Fix test_tag tests
  test/gtest/uct/test_tag.cc
Labels: bugfix

#2660 Fix out-of-tree vpath builds for PR #2657
  test/apps/Makefile.am
Labels: bugfix

#2650 Doxygen enhancements
  configure.ac
  doc/doxygen/conventions.dox
  doc/doxygen/conventions.md
  doc/doxygen/design.dox
  doc/doxygen/design.md
  doc/doxygen/header.tex.in
  doc/doxygen/intro.dox
  doc/doxygen/intro.md
  doc/doxygen/preface.dox
  doc/doxygen/preface.md
  doc/doxygen/ucxdox
Labels: documentation

#2661 UCT/IB: Added a new vendor_part_id for ConnectX-5 - 4122
  src/uct/ib/base/ib_device.c
Labels: portability

#2665 UCT/IB: Added a new vendor_part_id for ConnectX-5 - 4122
  src/uct/ib/base/ib_device.c
Labels: portability

#2666 TEST/EXAMPLES: Update the documentation in ucp_client_server.c
  test/examples/ucp_client_server.c
Labels: documentation

#2668 TEST/EXAMPLES: Update the documentation in ucp_client_server.c
  test/examples/ucp_client_server.c
Labels: documentation

#2669 UCP/RNDV/MLANE: disable mlane on self/shared AM TL
  src/ucp/wireup/select.c
Labels: bugfix

#2671 UCP/RNDV/MLANE: disable mlane on self/shared AM TL - v1.4
  src/ucp/wireup/select.c
Labels: bugfix

#2663 UCS/ASYNC//TEST: Fix timer ID generation
  src/ucs/async/async.c
  test/gtest/ucs/test_async.cc
Labels: bugfix

#2674 Update Tony's email address
  AUTHORS
Labels: documentation

#2673 UCP/WORKER: Fix setting AM handlers in destroy flow
  src/ucp/core/ucp_worker.c
Labels: bugfix

#2676 UCP/WORKER: Fix setting AM handlers in destroy flow - v1.4.x
  src/ucp/core/ucp_worker.c
Labels: bugfix

#2680 UCS: Enhance the error message for chunk_alloc
  src/ucs/datastruct/mpool.c
Labels: enhancement

#2679 UCP/DOC: improve ucp_worker_signal description
  src/ucp/api/ucp.h
Labels: Ready for Review, documentation

#2677 BUILD: Bump version to 1.5
  configure.ac
Labels: Ready for Review, documentation

#2686 UCP/WORKER: remove extra lock in ucp_worker_signal
  src/ucp/core/ucp_worker.c
Labels: enhancement

#2694 UCT/IB: Set minor gcc version if using clang version >= 300.
  contrib/test_jenkins.sh
  src/uct/ib/mlx5/ib_mlx5.h
Labels: bugfix, portability

#2701 UCP: condition in ucp_ep_match_list_for_each() - don't compare to NULL. - v1.4.x
  src/ucp/wireup/ep_match.c
Labels: bugfix

#2699 UCT/IB: Set minor gcc version if using clang version >= 300
  contrib/test_jenkins.sh
  src/uct/ib/mlx5/ib_mlx5.h
Labels: bugfix

#2703 UCM/TEST: Generate VM_UNMAP event for shmat(REMAP) and mmap(FIXED)
  contrib/test_jenkins.sh
  src/ucm/event/event.c
  test/gtest/ucm/malloc_hook.cc
  test/gtest/ucs/test_async.cc
  test/gtest/ucs/test_stats_filter.cc
Labels: bugfix

#2705 UCM/TEST: Generate VM_UNMAP event for shmat(REMAP) and mmap(FIXED) - v1.4.x
  contrib/test_jenkins.sh
  src/ucm/event/event.c
  test/gtest/ucm/malloc_hook.cc
  test/gtest/ucs/test_stats_filter.cc
Labels: bugfix

#2707 UCM/TEST: Generate VM_UNMAP event for shmat(REMAP) and mmap(FIXED) - v1.3.x
  contrib/test_jenkins.sh
  src/ucm/event/event.c
  src/ucs/Makefile.am
  src/ucs/arch/aarch64/cpu.c
  src/ucs/arch/aarch64/cpu.h
  src/ucs/sys/sys.c
  src/ucs/sys/sys.h
  src/uct/base/uct_mem.c
  src/uct/ib/base/ib_iface.c
  test/gtest/ucm/malloc_hook.cc
  test/gtest/ucs/test_stats_filter.cc
Labels: bugfix
