Repository openucx/ucx, pull requests merged in 2018-04, with the labels that each got.

#2468 UCP/WIREUP: Fix hang in performance tests
  src/ucp/wireup/wireup_ep.c
  test/gtest/ucp/ucp_test.cc
Labels: bugfix

#2465 TEST/MAKEFILE: Don't buffer stdout/stderr of tests
  test/gtest/Makefile.am
Labels: enhancement

#2473 UCT/RDMACM: Fix valgrind error when writing self->cm_id to log
  src/uct/ib/rdmacm/rdmacm_iface.c
Labels: bugfix

#2472 UCM/EVENT: Use hash table for tracking shmat() region size
  src/ucm/event/event.c
  src/ucm/mmap/install.c
Labels: optimization

#2474 UCP/DOC: Fix unpack routine description
  src/ucp/api/ucp.h
Labels: bugfix, documentation

#2466 UCT/ATOMICS: added ep_atomic_post and ep_atomic_fetch_nb calls
  src/uct/api/tl.h
  src/uct/api/uct.h
Labels: api, feature

#2467 UCT/CUDA/CUDA_IPC: cuda ipc uct skeleton
  src/uct/Makefile.am
  src/uct/cuda/cuda_ipc/cuda_ipc_ep.c
  src/uct/cuda/cuda_ipc/cuda_ipc_ep.h
  src/uct/cuda/cuda_ipc/cuda_ipc_iface.c
  src/uct/cuda/cuda_ipc/cuda_ipc_iface.h
  src/uct/cuda/cuda_ipc/cuda_ipc_md.c
  src/uct/cuda/cuda_ipc/cuda_ipc_md.h
Labels: feature

#2471 UCP/GTEST: Force creating an am_lane for the client-server flow.
  src/ucp/core/ucp_context.c
  src/ucp/core/ucp_ep.h
  src/ucp/core/ucp_listener.c
  src/ucp/core/ucp_proxy_ep.c
  src/ucp/wireup/select.c
  src/ucp/wireup/wireup.c
  test/gtest/ucp/test_ucp_sockaddr.cc
  test/gtest/ucp/ucp_test.cc
  test/gtest/ucp/ucp_test.h
Labels: bugfix

#2477 TEST/UCP/WIREUP: Fix and enhance wireup test
  src/tools/perf/libperf.c
  test/gtest/ucp/test_ucp_peer_failure.cc
  test/gtest/ucp/test_ucp_wireup.cc
Labels: test

#2476 UCS/TEST: Add strided allocator data structure
  src/ucs/Makefile.am
  src/ucs/datastruct/strided_alloc.c
  src/ucs/datastruct/strided_alloc.h
  src/ucs/sys/compiler.h
  src/ucs/sys/compiler_def.h
  test/gtest/Makefile.am
  test/gtest/ucs/test_strided_alloc.cc
Labels: feature

#2488 Small fixes in gtest
  test/gtest/common/test_helpers.h
  test/gtest/ucp/test_ucp_fence.cc
Labels: test

#2486 UCT/MM/SELF/ATOMIC: added bitwise ops
  src/ucs/arch/atomic.h
  src/uct/sm/base/sm_ep.c
  src/uct/sm/base/sm_ep.h
  src/uct/sm/mm/mm_iface.c
  src/uct/sm/self/self.c
Labels: feature

#2485 UCP: Unify rdesc release scenarios
  src/ucp/core/ucp_request.h
  src/ucp/core/ucp_request.inl
  src/ucp/core/ucp_worker.c
  src/ucp/core/ucp_worker.h
  src/ucp/stream/stream_recv.c
  src/ucp/tag/eager_rcv.c
  src/ucp/tag/rndv.c
  src/ucp/tag/tag_match.inl
  src/ucp/tag/tag_recv.c
Labels: enhancement

#2479 UCT/RCX/ATOMICS: added atomic bitwise ops-tests
  test/gtest/Makefile.am
  test/gtest/uct/test_amo.cc
  test/gtest/uct/test_amo.h
  test/gtest/uct/test_amo_add_xor.cc
  test/gtest/uct/test_amo_and_or.cc
  test/gtest/uct/test_amo_fadd.cc
  test/gtest/uct/test_amo_fadd_fxor.cc
  test/gtest/uct/test_amo_fand_for.cc
  test/gtest/uct/uct_test.cc
  test/gtest/uct/uct_test.h
Labels: test

#2480 UCT/MLX5/ATOMICS: added atomic bitwise operations
  src/uct/api/uct.h
  src/uct/ib/dc/accel/dc_mlx5.c
  src/uct/ib/mlx5/ib_mlx5.h
  src/uct/ib/rc/accel/rc_mlx5.h
  src/uct/ib/rc/accel/rc_mlx5_common.c
  src/uct/ib/rc/accel/rc_mlx5_common.h
  src/uct/ib/rc/accel/rc_mlx5_ep.c
  src/uct/ib/rc/accel/rc_mlx5_iface.c
Labels: feature

#2493 UCT/IB/MLX5: Use consistent naming for atomic opcodes
  src/uct/ib/base/ib_log.c
  src/uct/ib/mlx5/ib_mlx5_log.c
Labels: enhancement

#2491 TEST/ODP: Skip ODP tests on ppc64
  test/gtest/uct/ib/test_ib_xfer.cc
Labels: Ready for Review, test

#2487 UCP/ADDRESS: Use a wrapper structure for holding unpacked address
  src/ucp/core/ucp_ep.c
  src/ucp/core/ucp_types.h
  src/ucp/wireup/address.c
  src/ucp/wireup/address.h
  src/ucp/wireup/wireup.c
  test/gtest/ucp/test_ucp_wireup.cc
Labels: Ready for Review, enhancement

#2495 UCT/IB: Disable atomic UMR
  src/uct/ib/base/ib_md.c
  src/uct/ib/base/ib_md.h
  test/gtest/uct/ib/test_ib_xfer.cc
Labels: enhancement

#2496 UCP/WIREUP/ATOMICS: use 2 bits (32/64) to request atomics
  src/ucp/wireup/address.c
  src/ucp/wireup/address.h
  src/ucp/wireup/select.c
Labels: enhancement

#2489 UCP/EP: Allocate endpoint using a strided allocator
  src/tools/info/type_info.c
  src/ucp/core/ucp_ep.c
  src/ucp/core/ucp_ep.h
  src/ucp/core/ucp_ep.inl
  src/ucp/core/ucp_request.inl
  src/ucp/core/ucp_types.h
  src/ucp/core/ucp_worker.c
  src/ucp/core/ucp_worker.h
  src/ucp/proto/proto.h
  src/ucp/stream/stream.h
  src/ucp/stream/stream_recv.c
  src/ucp/wireup/wireup.c
  src/ucp/wireup/wireup_ep.c
  src/ucs/datastruct/strided_alloc.c
  src/ucs/datastruct/strided_alloc.h
  test/gtest/Makefile.am
  test/gtest/common/test_obj_size.cc
  test/gtest/ucp/test_ucp_peer_failure.cc
  test/gtest/ucp/test_ucp_wireup.cc
  test/gtest/ucs/test_hash_perf.cc
Labels: Ready for Review, optimization

#2500 UCP/CORE: Add data structure to match peer endpoints
  src/tools/info/type_info.c
  src/ucp/Makefile.am
  src/ucp/core/ucp_ep.c
  src/ucp/core/ucp_ep.h
  src/ucp/core/ucp_listener.c
  src/ucp/core/ucp_types.h
  src/ucp/core/ucp_worker.c
  src/ucp/core/ucp_worker.h
  src/ucp/wireup/ep_match.c
  src/ucp/wireup/ep_match.h
Labels: Ready for Review, enhancement

#2463 UCP/API: add UCP_EP_CLOSE_MODE_SYNC
  src/ucp/api/ucp.h
  src/ucs/type/status.h
Labels: api, documentation

#2497 UCP/WIREUP: fix pending counter in case of error
  src/ucp/wireup/wireup_ep.c
Labels: Waiting for Author Response, bugfix

#2498 UCT/IB/ATOMICS: adapt IB verbs transports to new API
  src/uct/ib/dc/verbs/dc_verbs.c
  src/uct/ib/rc/base/rc_iface.c
  src/uct/ib/rc/verbs/rc_verbs.h
  src/uct/ib/rc/verbs/rc_verbs_common.h
  src/uct/ib/rc/verbs/rc_verbs_ep.c
  src/uct/ib/rc/verbs/rc_verbs_iface.c
Labels: enhancement

#2504 TOOLS: added new atomic flags to ucx_info
  src/tools/info/tl_info.c
Labels: enhancement

#2499 UCT/CUDA/GTEST: {get,put}_short implementation
  contrib/valgrind.supp
  src/uct/Makefile.am
  src/uct/api/tl.h
  src/uct/api/uct.h
  src/uct/cuda/base/cuda_iface.h
  src/uct/cuda/cuda_copy/cuda_copy_ep.c
  src/uct/cuda/cuda_copy/cuda_copy_ep.h
  src/uct/cuda/cuda_copy/cuda_copy_iface.c
  src/uct/cuda/cuda_copy/cuda_copy_iface.h
  src/uct/cuda/gdr_copy/gdr_copy_ep.c
  src/uct/cuda/gdr_copy/gdr_copy_ep.h
  src/uct/cuda/gdr_copy/gdr_copy_iface.c
  src/uct/cuda/gdr_copy/gdr_copy_iface.h
  test/gtest/uct/test_p2p_rma.cc
  test/gtest/uct/test_p2p_rma.h
Labels: api, feature

#2502 UCP/EP: Refactor endpoint creation
  src/ucp/core/ucp_ep.c
  src/ucp/core/ucp_ep.h
  src/ucp/core/ucp_listener.c
Labels: enhancement

#2512 UCP: Fix the err labels order in the listener conn_req callback.
  src/ucp/core/ucp_listener.c
Labels: bugfix

#2511 UCT/TAG: Fix iov limit for eager_zcopy
  src/tools/info/tl_info.c
  src/uct/ib/dc/accel/dc_mlx5.c
  src/uct/ib/dc/base/dc_iface.c
  src/uct/ib/dc/base/dc_iface.h
  src/uct/ib/dc/verbs/dc_verbs.c
  src/uct/ib/mlx5/ib_mlx5.h
  src/uct/ib/rc/accel/rc_mlx5_common.h
  src/uct/ib/rc/accel/rc_mlx5_ep.c
  src/uct/ib/rc/accel/rc_mlx5_iface.c
  src/uct/ib/rc/base/rc_iface.c
  src/uct/ib/rc/base/rc_iface.h
  src/uct/ib/rc/verbs/rc_verbs_ep.c
  src/uct/ib/rc/verbs/rc_verbs_iface.c
  src/uct/ib/ud/accel/ud_mlx5.c
Labels: enhancement

#2509 UCT/ATOMIC: renamed atomic_fetch_nb to atomic_fetch
  src/uct/api/tl.h
  src/uct/api/uct.h
  src/uct/ib/dc/accel/dc_mlx5.c
  src/uct/ib/dc/verbs/dc_verbs.c
  src/uct/ib/rc/accel/rc_mlx5.h
  src/uct/ib/rc/accel/rc_mlx5_ep.c
  src/uct/ib/rc/accel/rc_mlx5_iface.c
  src/uct/ib/rc/verbs/rc_verbs.h
  src/uct/ib/rc/verbs/rc_verbs_ep.c
  src/uct/ib/rc/verbs/rc_verbs_iface.c
  src/uct/sm/base/sm_ep.c
  src/uct/sm/base/sm_ep.h
  src/uct/sm/mm/mm_iface.c
  src/uct/sm/self/self.c
  test/gtest/uct/test_amo.h
Labels: Ready for Review, api, enhancement

#2503 UCP/ATOMIC: updated UCP/UCT atomic masks
  src/ucp/core/ucp_context.c
  src/ucp/core/ucp_context.h
  src/ucp/core/ucp_worker.c
  src/ucp/wireup/address.c
  src/ucp/wireup/address.h
  src/ucp/wireup/select.c
  src/ucp/wireup/wireup.h
Labels: enhancement

#2524 UCS: Add case for invalid address alignment
  src/ucs/debug/debug.c
Labels: enhancement

#2528 BUILD: include cudamem.h in source tarball
  src/ucm/Makefile.am
Labels: bugfix

#2527 BUILD: include cudamem.h in source tarball
  src/ucm/Makefile.am
Labels: bugfix

#2505 API/UCT/UCP: Move the filling of the client's private data to a callback
  src/ucp/core/ucp_ep.c
  src/ucp/core/ucp_worker.c
  src/ucp/core/ucp_worker.h
  src/ucp/wireup/wireup_ep.c
  src/ucp/wireup/wireup_ep.h
  src/uct/api/tl.h
  src/uct/api/uct.h
  src/uct/api/uct_def.h
  src/uct/base/uct_iface.c
  src/uct/base/uct_iface.h
  src/uct/ib/rdmacm/rdmacm_ep.c
  src/uct/ib/rdmacm/rdmacm_ep.h
  src/uct/ib/rdmacm/rdmacm_iface.c
  test/gtest/ucp/test_ucp_sockaddr.cc
  test/gtest/uct/ib/test_sockaddr.cc
  test/gtest/uct/test_peer_failure.cc
  test/gtest/uct/uct_test.cc
  test/gtest/uct/uct_test.h
Labels: Ready for Review, api, feature

#2519 UCT/IB/MLX5: Fix TX completion accounting
  src/uct/ib/dc/accel/dc_mlx5.c
  src/uct/ib/mlx5/ib_mlx5.c
  src/uct/ib/mlx5/ib_mlx5.inl
  src/uct/ib/rc/accel/rc_mlx5_common.h
  src/uct/ib/rc/accel/rc_mlx5_iface.c
  src/uct/ib/rc/base/rc_ep.h
  src/uct/ib/rc/base/rc_iface.c
  src/uct/ib/rc/base/rc_iface.h
  src/uct/ib/ud/accel/ud_mlx5.c
Labels: bugfix

#2532 GTEST/UCT: Fix tag_cancel_noforce test
  test/gtest/uct/test_tag.cc
Labels: bugfix, test

#2516 UCT/IB: Add subnet_prefix filter
  src/uct/base/uct_md.h
  src/uct/ib/base/ib_device.c
  src/uct/ib/base/ib_iface.c
  src/uct/ib/base/ib_iface.h
  src/uct/ib/base/ib_md.c
  src/uct/ib/base/ib_md.h
  test/gtest/uct/ib/test_ib.cc
Labels: enhancement

#2531 ARM: replacing ldxr with ldxrb
  src/ucs/arch/aarch64/cpu.h
Labels: bugfix

#2533 JENKINS: load cuda module if available for release pkg distcheck
  contrib/test_jenkins.sh
Labels: test

#2538 GTEST: Create a separate class for wakeup testing + fix a leak in rdmacm
  src/uct/ib/rdmacm/rdmacm_iface.c
  test/gtest/ucp/test_ucp_sockaddr.cc
Labels: test

#2539 RPM/PERFTEST: Remove global CXXFLAGS setting from RPM build
  src/tools/perf/Makefile.am
  ucx.spec.in
Labels: cleanup

#2541 GTEST/UCT/ATOMIC: test for ADD switched to new API
  test/gtest/uct/test_amo_add_xor.cc
Labels: test

#2521 UCP/ATOMIC: added bitwise atomic ops
  src/ucp/amo/amo.inl
  src/ucp/amo/basic_amo.c
  src/ucp/amo/nb_amo.c
  src/ucp/api/ucp.h
  src/ucp/core/ucp_request.h
  src/uct/api/uct.h
Labels: Ready for Review, api, feature

#2546 UCT/IB: Ignore error if can't read board_vendor from sysfs
  src/uct/ib/base/ib_iface.c
Labels: bugfix

#2548 UCP/ATOMIC: return UCS_OK on all nonfailed ops
  src/ucp/amo/nb_amo.c
Labels: enhancement

#2550 GTEST/ATOMIC: p2p-mix test is ported to new atomic API
  test/gtest/uct/test_p2p_mix.cc
  test/gtest/uct/test_p2p_mix.h
Labels: test

#2551 GTEST/ATOMICS: test stats switched to new atomic API
  test/gtest/uct/test_stats.cc
Labels: test

#2506 UCT/UGNI/ATOMIC: added stub atomic implementation for new API
  src/uct/ugni/rdma/ugni_rdma_ep.c
  src/uct/ugni/rdma/ugni_rdma_ep.h
  src/uct/ugni/rdma/ugni_rdma_iface.c
Labels: Ready for Review

#2553 GTEST/ATOMICS: UCT atomics ADD/XOR test switched to new API
  test/gtest/uct/test_amo_fadd_fxor.cc
Labels: test

#2554 ATOMIC/PERFTEST: switched to new atomic API
  src/tools/perf/uct_tests.cc
Labels: test

#2555 UCP/WIREUP: Fix hang due to wireup request message not being sent
  src/ucp/wireup/wireup.c
Labels: bugfix

#2547 UCP/GTEST: added bitwise atomic tests
  test/gtest/ucp/test_ucp_atomic.cc
  test/gtest/ucp/test_ucp_atomic.h
Labels: Waiting for Author Response

#2559 UCS/RCACHE: Fix access to uninitialized queue
  src/ucs/sys/rcache.c
Labels: bugfix

#2564 UCP/TAG/GTEST: Fix tag offload sync zcopy
  src/ucp/tag/offload.c
  test/gtest/ucp/test_ucp_tag.cc
  test/gtest/ucp/test_ucp_tag.h
  test/gtest/ucp/test_ucp_tag_offload.cc
  test/gtest/ucp/test_ucp_tag_xfer.cc
Labels: bugfix, test

#2558 UCT/CM: Return empty resource list if ib_ucm.ko driver is not loaded
  src/uct/ib/cm/cm_iface.c
Labels: enhancement
