Repository openucx/ucx, pull requests merged in 2018-02, with the labels that each got.

#2255 Update news and spec version - v1.3.x
  NEWS
  doc/doxygen/header.tex
Labels: Ready for Review, documentation

#2278 UCP/RNDV-GET: fixed processing of message size
  src/ucp/tag/rndv.c
  test/gtest/ucp/test_ucp_tag_xfer.cc
Labels: bugfix

#2259 BUILD: Bump shared library version - v1.3.x
  configure.ac
Labels: documentation

#2297 TEST/UCM: Fix performance test of malloc with multiple ptrs
  test/gtest/ucm/malloc_hook.cc
Labels: bugfix, test

#2230 GTEST: Test INADDR_ANY in the sockaddr tests.
  src/ucp/core/ucp_listener.c
  test/gtest/ucp/test_ucp_sockaddr.cc
  test/gtest/ucp/ucp_test.cc
  test/gtest/uct/ib/test_sockaddr.cc
  test/gtest/uct/uct_test.cc
  test/gtest/uct/uct_test.h
Labels: test

#2304 UCP/RNDV: fix for hang on osu collective tests with multi-rail - v1.3
  src/ucp/tag/rndv.c
Labels: bugfix

#2300 UCT/IB: Remove leftover numa.h include - v1.3.x
  src/uct/ib/base/ib_iface.c
Labels: bugfix

#2305 TEST/UCM: Fix performance test of malloc with multiple ptrs
  test/gtest/ucm/malloc_hook.cc
Labels: bugfix, test

#2294 TEST/UCT: Wait for send resorces for up to 10sec
  test/gtest/uct/test_p2p_am.cc
Labels: bugfix, test

#2302 UCP/RNDV: fix for hang on osu collective tests with multi-rail
  src/ucp/tag/rndv.c
Labels: Waiting for Author Response, bugfix

#2306 UCT/IB: Remove leftover numa.h include
  src/uct/ib/base/ib_iface.c
Labels: bugfix, portability

#2296 UCS/CONFIG: Don't freeze on error by default
  src/ucs/config/global_opts.c
Labels: enhancement

#2308 UCT/CUDA: create cuda streams on first use
  src/uct/cuda/cuda_copy/cuda_copy_ep.c
  src/uct/cuda/cuda_copy/cuda_copy_iface.c
  src/uct/cuda/cuda_copy/cuda_copy_iface.h
Labels: bugfix

#2312 UCT/IB: Enhance error message of ibv_open_device()
  src/uct/ib/base/ib_device.c
Labels: enhancement

#2310 UCT/CUDA: create cuda streams on first use - v1.3.x
  src/uct/cuda/cuda_copy/cuda_copy_ep.c
  src/uct/cuda/cuda_copy/cuda_copy_iface.c
  src/uct/cuda/cuda_copy/cuda_copy_iface.h
Labels: bugfix

#2273 UCT/IB: disable ib data dump log when mem type direct access is enabled.
  src/uct/ib/base/ib_device.h
  src/uct/ib/base/ib_iface.h
  src/uct/ib/base/ib_log.c
  src/uct/ib/base/ib_log.h
  src/uct/ib/base/ib_md.c
  src/uct/ib/dc/accel/dc_mlx5.c
  src/uct/ib/dc/verbs/dc_verbs.c
  src/uct/ib/mlx5/ib_mlx5_log.c
  src/uct/ib/mlx5/ib_mlx5_log.h
  src/uct/ib/rc/accel/rc_mlx5_common.h
  src/uct/ib/rc/accel/rc_mlx5_ep.c
  src/uct/ib/rc/verbs/rc_verbs_ep.c
  src/uct/ib/ud/accel/ud_mlx5.c
  src/uct/ib/ud/verbs/ud_verbs.c
Labels: bugfix

#2311 UCX: Update NEWS file
  NEWS
Labels: Ready for Review, documentation

#2318 UCT/RC_IFACE: fixed potential error in macro
  src/uct/ib/rc/base/rc_iface.h
Labels: bugfix

#2264 UCT/UD: dispatch pending ops from the progress() context only
  src/tools/perf/libperf.c
  src/ucs/Makefile.am
  src/ucs/datastruct/arbiter.c
  src/ucs/datastruct/arbiter.h
  src/uct/ib/cm/cm.h
  src/uct/ib/cm/cm_iface.c
  src/uct/ib/ud/accel/ud_mlx5.c
  src/uct/ib/ud/base/ud_ep.c
  src/uct/ib/ud/base/ud_ep.h
  src/uct/ib/ud/base/ud_iface.c
  src/uct/ib/ud/base/ud_iface.h
  src/uct/ib/ud/base/ud_inl.h
  src/uct/ib/ud/verbs/ud_verbs.c
  test/gtest/uct/test_pending.cc
Labels: bugfix

#2317 UCP: reset uuid in address pack for mem type ep
  src/ucp/core/ucp_ep.c
Labels: bugfix

#2309 UCP/STREAM: add generic datatype support to ucp_stream_recv_nb
  src/ucp/stream/stream_recv.c
  test/gtest/ucp/test_ucp_stream.cc
  test/gtest/ucp/ucp_datatype.h
Labels: feature

#2319 UCP: reset uuid in address pack for mem type ep
  src/ucp/core/ucp_ep.c
Labels: bugfix

#2314 UCT/DC: Don't consider fc_wnd if flow control is disabled
  src/uct/ib/dc/base/dc_ep.h
  src/uct/ib/rc/base/rc_ep.h
  test/gtest/uct/ib/test_dc.cc
  test/gtest/uct/ib/test_rc.cc
  test/gtest/uct/ib/test_rc.h
Labels: bugfix

#2327 Fix test types batch file and improve perftest error message
  contrib/ucx_perftest_config/test_types
  src/tools/perf/perftest.c
Labels: bugfix, cleanup

#2326 UCT/SELF: Cleanups in self transport
  src/tools/info/type_info.c
  src/uct/Makefile.am
  src/uct/sm/self/self.c
  src/uct/sm/self/self.h
  src/uct/sm/self/self_ep.c
  src/uct/sm/self/self_ep.h
  src/uct/sm/self/self_iface.c
  src/uct/sm/self/self_iface.h
  src/uct/sm/self/self_md.c
  src/uct/sm/self/self_md.h
  test/gtest/common/test_obj_size.cc
Labels: cleanup

#2325 UCP/EAGER: enabled mlane on UD transport
  src/ucp/wireup/select.c
Labels: cleanup

#2271 TEST: Added a UCP client-server API example.
  contrib/test_jenkins.sh
  test/examples/Makefile.am
  test/examples/ucp_client_server.c
Labels: documentation

#2337 UCP/CONTEXT: added variable to suppress version mismatch
  src/ucp/core/ucp_context.c
Labels: enhancement

#2340 UCS/MPOOL: follow strong limit of mpool elements
  src/ucs/datastruct/mpool.c
Labels: enhancement

#2335 GTEST/UCT/DC: Fix DC flow control test
  src/uct/ib/dc/base/dc_ep.c
  test/gtest/uct/ib/test_dc.cc
Labels: Ready for Review, bugfix, test

#2324 GTEST/UCT: add UCS_OK pending queue test
  test/gtest/uct/test_pending.cc
Labels: test

#2291 UCM/GTEST: cuda memory allocation/free hooks
  src/ucm/api/ucm.h
  src/ucm/cuda/cudamem.h
  src/ucm/cuda/install.c
  src/ucm/event/event.c
  src/ucm/util/replace.c
  src/ucm/util/replace.h
  test/gtest/ucm/cuda_hooks.cc
Labels: Waiting for Author Response, enhancement

#2342 UCM/GTEST: cuda driver memory alloc/free hooks
  src/ucm/cuda/cudamem.h
  src/ucm/cuda/install.c
  src/ucm/event/event.c
  src/ucm/util/replace.c
  test/gtest/ucm/cuda_hooks.cc
Labels: enhancement

#2344 Test: Fix compilation with the -Wall flag and add it to the Makefile.am
  test/examples/Makefile.am
  test/examples/ucp_client_server.c
Labels: bugfix, test

#2349 JENKINS: check nvidia driver installation for running cuda tests
  contrib/test_jenkins.sh
Labels: test

#2345 UCS/RCACHE: add stats
  src/tools/info/type_info.c
  src/ucs/Makefile.am
  src/ucs/sys/rcache.c
  src/ucs/sys/rcache.h
  src/ucs/sys/rcache_int.h
  test/gtest/ucs/test_rcache.cc
Labels: enhancement

#2353 UCT/IB/MLX5: fixed compilation issue
  src/uct/ib/dc/accel/dc_mlx5.c
  src/uct/ib/rc/accel/rc_mlx5_ep.c
Labels: bugfix

#2352 UCT/RC/IFACE: fixed macro
  src/uct/ib/rc/base/rc_iface.h
Labels: cleanup

#2341 UCT/RC/MLX5: Fix SRQ clean flow
  src/uct/ib/rc/accel/rc_mlx5_common.c
  test/gtest/ucp/test_ucp_peer_failure.cc
Labels: bugfix

#2350 UCT/CUDA: drain cudaLastError if it failed to get cudaPointerGetAttri…
  src/uct/cuda/cuda_copy/cuda_copy_md.c
  src/uct/cuda/gdr_copy/gdr_copy_md.c
Labels: bugfix
