Repository openucx/ucx, pull requests merged in 2018-11, with the labels that each got.

#2984 IB: added cache for AH
  src/ucs/datastruct/khash.h
  src/uct/ib/base/ib_device.c
  src/uct/ib/base/ib_device.h
  src/uct/ib/base/ib_iface.c
  src/uct/ib/base/ib_iface.h
  src/uct/ib/base/ib_md.c
  src/uct/ib/dc/accel/dc_mlx5.c
  src/uct/ib/dc/verbs/dc_verbs.c
  src/uct/ib/mlx5/ib_mlx5.c
  src/uct/ib/ud/accel/ud_mlx5_common.c
  src/uct/ib/ud/verbs/ud_verbs.c
Labels: Bugfix

#3012 TEST/RCACHE: Fix rcache stats test, to account for region struct unmap
  test/gtest/ucs/test_rcache.cc
Labels: Bugfix, Test

#2987 UCT/IB: Compact AV fix
  src/uct/ib/base/ib_device.c
  src/uct/ib/base/ib_device.h
  src/uct/ib/base/ib_iface.c
  src/uct/ib/base/ib_iface.h
  src/uct/ib/cm/cm.h
  src/uct/ib/cm/cm_ep.c
  src/uct/ib/dc/accel/dc_mlx5.c
  src/uct/ib/dc/base/dc_iface.c
  src/uct/ib/dc/verbs/dc_verbs.c
  src/uct/ib/mlx5/ib_mlx5.c
  src/uct/ib/ud/accel/ud_mlx5_common.c
  src/uct/ib/ud/base/ud_iface.c
  test/gtest/uct/ib/test_ib.cc
  test/gtest/uct/ib/test_ud_ds.cc
Labels: Bugfix, Optimization

#2995 validate rma lane if rkey is not needed for mem type
  contrib/test_jenkins.sh
  src/ucp/core/ucp_mm.h
  src/ucp/core/ucp_rkey.c
  src/ucp/tag/offload.c
  src/ucp/tag/rndv.c
Labels: Bugfix

#3017 DOC: Newer doxygen generates reasonably good man pages
  doc/doxygen/ucxdox
Labels: Documentation

#3011 TEST/ASYNC: Add retries to test_async_timer_mt.multithread
  test/gtest/ucs/test_async.cc
Labels: Bugfix, Test

#3006 UCT/IB: Add HDR 16-links config recognition
  src/uct/ib/base/ib_iface.c
Labels: Enhancement

#3015 DOCS: fix doxygen warnings about broken links
  doc/doxygen/ucxdox
  src/ucp/api/ucp.h
  src/ucp/api/ucp_compat.h
  src/ucp/api/ucp_def.h
  src/ucs/config/types.h
  src/ucs/datastruct/callbackq.h
  src/uct/api/uct.h
  src/uct/api/uct_def.h
Labels: Documentation

#2991 UCT/IB: Add configuration to change default MMIO mode for post_send
  src/uct/ib/dc/accel/dc_mlx5.c
  src/uct/ib/dc/accel/dc_mlx5.h
  src/uct/ib/mlx5/ib_mlx5.c
  src/uct/ib/mlx5/ib_mlx5.h
  src/uct/ib/rc/accel/rc_mlx5.h
  src/uct/ib/rc/accel/rc_mlx5_common.c
  src/uct/ib/rc/accel/rc_mlx5_common.h
  src/uct/ib/rc/accel/rc_mlx5_ep.c
  src/uct/ib/rc/accel/rc_mlx5_iface.c
  src/uct/ib/ud/accel/ud_mlx5.c
  src/uct/ib/ud/accel/ud_mlx5.h
Labels: Enhancement

#3003 UCT/IB/MLX5: Include verbs.h before mlx5dv.h
  config/m4/ib.m4
  src/uct/ib/mlx5/ib_mlx5.h
Labels: Bugfix

#3019 UCT/IB/MLX5: Set minimal RoCEv2 UDP source port
  src/uct/ib/mlx5/ib_mlx5.h
  src/uct/ib/ud/accel/ud_mlx5_common.c
Labels: Bugfix

#3021 UCT/IB: Fix force global AV
  src/uct/ib/base/ib_iface.c
Labels: Bugfix

#3022 TEST/EXAMPLES: Simplify client/server example - config is not required
  test/examples/ucp_client_server.c
Labels: Cleanup, Ready for Review

#3018 Improve IB error reporting
  src/uct/ib/dc/accel/dc_mlx5.c
  src/uct/ib/dc/base/dc_iface.c
  src/uct/ib/mlx5/ib_mlx5.c
  src/uct/ib/mlx5/ib_mlx5_log.c
  src/uct/ib/mlx5/ib_mlx5_log.h
  src/uct/ib/rc/accel/rc_mlx5_iface.c
  test/gtest/ucp/test_ucp_sockaddr.cc
  test/gtest/uct/ib/test_dc.cc
  test/gtest/uct/test_p2p_mix.cc
Labels: Enhancement, Ready for Review

#3016 GTEST: increase timeout in test_ud_slow_timer.ep_destroy
  test/gtest/uct/ib/test_ud_slow_timer.cc
Labels: Waiting for Author Response

#3031 Optimizations for PUT message rate
  src/ucp/rma/rma_basic.c
  src/uct/ib/rc/accel/rc_mlx5_common.h
Labels: Optimization

#3032 UCP/FLUSH: Flush endpoint while flushing a worker
  src/ucp/core/ucp_context.c
  src/ucp/core/ucp_context.h
  src/ucp/core/ucp_ep.c
  src/ucp/core/ucp_ep.h
  src/ucp/core/ucp_request.h
  src/ucp/rma/flush.c
  src/uct/ib/dc/base/dc_iface.c
  src/uct/tcp/tcp_ep.c
Labels: Bugfix

#2999 GitLab CI config to upload release assets
  .gitlab-ci.yml
Labels: Waiting for Author Response

#2989 TEST/IB: Re-enable ODP tests, and flush sender iface to fix err syndrome
  test/gtest/uct/ib/test_ib_xfer.cc
  test/gtest/uct/test_p2p_mix.cc
  test/gtest/uct/uct_p2p_test.cc
Labels: Bugfix, Test

#2965 UCT: implement flags of uct_ep_pending_add
  src/uct/base/uct_iface.c
  src/uct/base/uct_iface.h
  src/uct/ib/cm/cm.h
  src/uct/ib/cm/cm_ep.c
  src/uct/ib/cm/cm_iface.c
  src/uct/ib/dc/base/dc_ep.c
  src/uct/ib/rc/base/rc_ep.c
  src/uct/ib/ud/base/ud_ep.c
  src/uct/ib/ud/base/ud_ep.h
  src/uct/sm/mm/mm_ep.c
  src/uct/tcp/tcp_ep.c
  src/uct/ugni/base/ugni_ep.c
  test/gtest/uct/test_p2p_am.cc
Labels: Feature, Waiting for Author Response

#3053 UCP: Add latency to am_bw score calc - v1.5.x
  src/ucp/wireup/select.c
Labels: Critical v1.5.x

#3051 UCP: Add latency to am_bw score calculation
  src/ucp/wireup/select.c
Labels: Bugfix, Critical v1.5.x

#3024 Topic/dv devx
  config/m4/ib.m4
  src/uct/Makefile.am
  src/uct/ib/base/ib_device.c
  src/uct/ib/base/ib_device.h
  src/uct/ib/mlx5/ib_mlx5.c
  src/uct/ib/mlx5/ib_mlx5_dv.c
  src/uct/ib/mlx5/ib_mlx5_ifc.h
  src/uct/ib/rc/accel/rc_mlx5_common.c
  src/uct/ib/rc/base/rc_iface.c
Labels: Feature, Waiting for Author Response

#3040 refactor UCT transports
  config/m4/ib.m4
  configure.ac
  src/tools/info/type_info.c
  src/ucp/core/ucp_context.c
  src/uct/Makefile.am
  src/uct/ib/dc/verbs/dc_verbs.c
  src/uct/ib/dc/verbs/dc_verbs.h
  test/gtest/common/test_obj_size.cc
  test/gtest/ucp/test_ucp_sockaddr.cc
  test/gtest/ucp/test_ucp_tag_offload.cc
  test/gtest/ucp/ucp_test.h
  test/gtest/uct/ib/test_dc.cc
  test/gtest/uct/test_tag.cc
  test/gtest/uct/uct_test.h
Labels: Cleanup, Waiting for Author Response

#3054 Fixes for endpoint flush
  src/ucp/core/ucp_ep.inl
  src/ucp/rma/flush.c
  src/ucp/wireup/wireup.c
  src/uct/sm/mm/mm_ep.c
Labels: Bugfix, Critical v1.5.x

#3033 UCT/IB: Add DV CQE 128bit support
  config/m4/ib.m4
  src/uct/ib/base/ib_device.c
  src/uct/ib/base/ib_device.h
  src/uct/ib/base/ib_iface.c
  src/uct/ib/base/ib_iface.h
  src/uct/ib/cm/cm_iface.c
  src/uct/ib/dc/accel/dc_mlx5.c
  src/uct/ib/mlx5/ib_mlx5.c
  src/uct/ib/mlx5/ib_mlx5.h
  src/uct/ib/rc/accel/rc_mlx5_iface.c
  src/uct/ib/rc/verbs/rc_verbs_iface.c
  src/uct/ib/ud/accel/ud_mlx5.c
  src/uct/ib/ud/verbs/ud_verbs.c
Labels: Optimization

#3064 Fixes for endpoint flush - v1.5.x
  src/ucp/core/ucp_ep.inl
  src/ucp/rma/flush.c
  src/ucp/wireup/wireup.c
  src/uct/sm/mm/mm_ep.c
  test/gtest/ucs/test_stats.cc
  test/gtest/ucs/test_stats_filter.cc
Labels: Bugfix, Critical v1.5.x

#3068 TEST/GTEST: Workaround armclang 19 segfault - avoid empty initializer
  test/gtest/ucs/test_stats.cc
  test/gtest/ucs/test_stats_filter.cc
Labels: Bugfix

#3055 UCP/WIREUP: add async wireup
  src/ucp/core/ucp_request.c
  src/ucp/core/ucp_request.h
  src/ucp/core/ucp_request.inl
  src/ucp/proto/proto_am.inl
  src/ucp/rma/amo_sw.c
  src/ucp/rma/rma.inl
  src/ucp/rma/rma_send.c
  src/ucp/rma/rma_sw.c
  src/ucp/stream/stream_send.c
  src/ucp/tag/eager_snd.c
  src/ucp/tag/rndv.c
  src/ucp/tag/tag_send.c
  src/ucp/wireup/wireup.c
  src/ucp/wireup/wireup_ep.c
  src/ucp/wireup/wireup_ep.h
  test/gtest/common/test_helpers.cc
  test/gtest/common/test_helpers.h
  test/gtest/ucp/test_ucp_sockaddr.cc
  test/gtest/ucp/test_ucp_tag_offload.cc
  test/gtest/ucp/test_ucp_wireup.cc
  test/gtest/ucp/ucp_test.h
  test/gtest/uct/ib/test_dc.cc
  test/gtest/uct/test_stats.cc
  test/gtest/uct/uct_test.h
Labels: Approved pending CI
