Repository openucx/ucx, pull requests merged in 2018-08, with the labels that each got.

#2775 UCS: Change rcache reg warn to debug
  src/ucs/sys/rcache.c
Labels: bugfix

#2766 TEST: fixed valgrind args
  contrib/test_jenkins.sh
  src/ucm/malloc/malloc_hook.c
  src/ucm/util/reloc.c
  src/ucm/util/reloc.h
Labels: bugfix

#2772 UCS/PGTABLE: return error instead of assert on inserting overlapped region - 1.4.x
  src/ucs/datastruct/pgtable.c
Labels: bugfix

#2774 GTEST: ignore warnings on stats filter test
  src/ucs/arch/x86_64/cpu.c
  src/ucs/config/global_opts.c
  src/ucs/config/global_opts.h
  test/gtest/ucp/ucp_test.cc
  test/gtest/ucs/test_stats_filter.cc
Labels: bugfix

#2776 UCP: fix a bunch of typos
  src/ucp/core/ucp_context.c
Labels: bugfix, documentation

#2783 UCP: Clarify UCX_TLS possible values
  src/ucp/core/ucp_context.c
Labels: bugfix, documentation

#2779 UCM: fix crash in debug log for NULL filename
  src/ucm/util/log.c
Labels: bugfix

#2778 UCS/ucx_info: add new Intel CPU models
  src/tools/info/sys_info.c
  src/ucs/arch/cpu.h
  src/ucs/arch/x86_64/cpu.c
Labels: enhancement

#2786 GTEST: Move restore_errors() to after the server's ep creation.
  src/ucp/wireup/wireup_ep.c
  test/gtest/ucp/test_ucp_sockaddr.cc
Labels: bugfix

#2785 UCM/UCS/RCACHE: allow rcache to register for multiple events
  src/ucm/event/event.c
  src/ucs/sys/rcache.c
  src/ucs/sys/rcache.h
  src/uct/cuda/gdr_copy/gdr_copy_md.c
  src/uct/ib/base/ib_md.c
  src/uct/sm/knem/knem_md.c
  test/gtest/ucm/cuda_hooks.cc
  test/gtest/ucs/test_rcache.cc
Labels: enhancement

#2796 UCT/UD: fix out of order sending
  src/uct/ib/ud/base/ud_ep.c
Labels: bugfix

#2742 UCP/LISTENER: Fix a race condition between async and main thread
  src/ucp/core/ucp_ep.c
  src/ucp/core/ucp_listener.c
  src/ucp/core/ucp_listener.h
  src/ucp/core/ucp_request.c
  src/ucp/core/ucp_thread.h
  src/ucp/core/ucp_worker.c
  src/ucp/core/ucp_worker.h
  src/ucp/rma/basic_amo.c
  src/ucp/rma/basic_rma.c
  src/ucp/rma/flush.c
  src/ucp/rma/nb_amo.c
  src/ucp/stream/stream_recv.c
  src/ucp/stream/stream_send.c
  src/ucp/tag/probe.c
  src/ucp/tag/tag_recv.c
  src/ucp/tag/tag_send.c
  src/ucp/wireup/wireup_ep.c
  src/ucs/async/async.h
  src/ucs/async/signal.h
  src/ucs/async/thread.h
  test/gtest/ucp/test_ucp_sockaddr.cc
Labels: Ready for Review, bugfix

#2798 Logging fixes
  src/ucs/debug/assert.c
  src/uct/ib/ud/base/ud_inl.h
Labels: enhancement

#2743 Compilation with upstream
  config/m4/ib.m4
  contrib/valgrind.supp
  src/uct/base/uct_worker.h
  src/uct/ib/base/ib_iface.c
  src/uct/ib/base/ib_iface.h
  src/uct/ib/base/ib_verbs.h
  src/uct/ib/mlx5/ib_mlx5.c
  src/uct/ib/mlx5/ib_mlx5.h
  src/uct/ib/mlx5/ib_mlx5.inl
  src/uct/ib/mlx5/ib_mlx5_dv.c
  src/uct/ib/mlx5/ib_mlx5_hw.h
  src/uct/ib/mlx5/ib_mlx5_log.c
  src/uct/ib/rc/accel/rc_mlx5_common.c
  src/uct/ib/rc/base/rc_iface.c
  src/uct/ib/ud/base/ud_iface.c
  test/apps/test_ucx_tls.py
  test/gtest/ucm/malloc_hook.cc
  test/gtest/uct/ib/test_ib_md.cc
  test/gtest/uct/test_amo_swap.cc
Labels: portability

#2804 UCP/RMA: Implement blocking RMA/AMO using non-blocking APIs
  src/ucp/Makefile.am
  src/ucp/rma/amo.inl
  src/ucp/rma/amo_basic.c
  src/ucp/rma/basic_amo.c
  src/ucp/rma/flush.c
  src/ucp/rma/nb_amo.c
  src/ucp/rma/rma.inl
  src/ucp/rma/rma_basic.c
  test/gtest/ucp/test_ucp_atomic.cc
Labels: enhancement

#2806 UCX: bump version to v1.3.1
  NEWS
  configure.ac
  ucx.spec.in
Labels: Ready for Review, documentation

#2809 UCP/RMA: Define protocols from RMA and AMO
  src/ucp/Makefile.am
  src/ucp/core/ucp_mm.h
  src/ucp/core/ucp_rkey.c
  src/ucp/core/ucp_types.h
  src/ucp/rma/amo_basic.c
  src/ucp/rma/amo_send.c
  src/ucp/rma/flush.c
  src/ucp/rma/rma.h
  src/ucp/rma/rma.inl
  src/ucp/rma/rma_basic.c
  src/ucp/rma/rma_send.c
Labels: enhancement

#2811 UCP/WIREUP: Fix pending requests purge
  src/ucp/wireup/wireup_ep.c
Labels: bugfix

#2814 TEST/UCP: Test only non-blocking RMA/AMO
  test/gtest/ucp/test_ucp_atomic.cc
  test/gtest/ucp/test_ucp_atomic.h
  test/gtest/ucp/test_ucp_fence.cc
  test/gtest/ucp/test_ucp_memheap.cc
  test/gtest/ucp/test_ucp_rma.cc
  test/gtest/ucp/test_ucp_rma_mt.cc
  test/gtest/ucp/ucp_test.cc
Labels: test

#2807 RC/UD with upstream
  config/m4/ib.m4
  configure.ac
  src/tools/info/type_info.c
  src/uct/Makefile.am
  src/uct/ib/base/ib_iface.c
  src/uct/ib/base/ib_iface.h
  src/uct/ib/base/ib_verbs.h
  src/uct/ib/cm/cm_iface.c
  src/uct/ib/dc/accel/dc_mlx5.c
  src/uct/ib/dc/base/dc_iface.c
  src/uct/ib/dc/base/dc_iface.h
  src/uct/ib/dc/verbs/dc_verbs.c
  src/uct/ib/mlx5/ib_mlx5.c
  src/uct/ib/mlx5/ib_mlx5_dv.c
  src/uct/ib/mlx5/ib_mlx5_hw.c
  src/uct/ib/rc/accel/rc_mlx5_common.h
  src/uct/ib/rc/accel/rc_mlx5_iface.c
  src/uct/ib/rc/base/rc_iface.c
  src/uct/ib/rc/base/rc_iface.h
  src/uct/ib/rc/verbs/rc_verbs_iface.c
  src/uct/ib/ud/accel/ud_mlx5.c
  src/uct/ib/ud/base/ud_iface.c
  src/uct/ib/ud/base/ud_iface.h
  src/uct/ib/ud/verbs/ud_verbs.c
  test/apps/test_ucx_tls.py
Labels: Waiting for Author Response, feature

#2790 MALLOK HOOKS: added binary instrumentation based hooks
  config/m4/ucs.m4
  src/ucm/Makefile.am
  src/ucm/bistro/bistro.c
  src/ucm/bistro/bistro.h
  src/ucm/bistro/bistro_aarch64.c
  src/ucm/bistro/bistro_aarch64.h
  src/ucm/bistro/bistro_int.h
  src/ucm/bistro/bistro_ppc64.c
  src/ucm/bistro/bistro_ppc64.h
  src/ucm/bistro/bistro_x86_64.c
  src/ucm/bistro/bistro_x86_64.h
  src/ucs/arch/aarch64/cpu.h
  src/ucs/arch/cpu.h
  src/ucs/arch/ppc64/cpu.h
  src/ucs/arch/x86_64/cpu.c
  src/ucs/arch/x86_64/cpu.h
  test/gtest/ucm/malloc_hook.cc
Labels: feature

#2821 UCT/IB: options to enable/disable GPUDirect RDMA
  src/uct/ib/base/ib_md.c
  src/uct/ib/base/ib_md.h
Labels: enhancement

#2823 Fixes for MLNX_OFED 4.4 testing
  contrib/valgrind.supp
  test/apps/test_ucx_tls.py
Labels: test
