Repository openucx/ucx, pull requests merged in 2018-03, with the labels that each got.

#2355 UCT/DC: Remove FC EP from arbiter before it is cleaned
  src/uct/ib/dc/base/dc_iface.c
Labels: bugfix

#2358 UCT/MLX5: added common config infrastructure
  config/m4/ib.m4
  src/uct/ib/dc/accel/dc_mlx5.c
  src/uct/ib/dc/accel/dc_mlx5.h
  src/uct/ib/rc/accel/rc_mlx5.h
  src/uct/ib/rc/accel/rc_mlx5_common.c
  src/uct/ib/rc/accel/rc_mlx5_common.h
  src/uct/ib/rc/accel/rc_mlx5_iface.c
Labels: enhancement

#2334 UCP/STREAM: add UCP_REQUEST_FLAG_RECV_WAITALL support
  src/ucp/api/ucp.h
  src/ucp/core/ucp_request.h
  src/ucp/core/ucp_request.inl
  src/ucp/stream/stream_recv.c
  test/gtest/ucp/test_ucp_stream.cc
  test/gtest/ucp/test_ucp_tag.h
  test/gtest/ucp/test_ucp_tag_xfer.cc
  test/gtest/ucp/ucp_datatype.cc
  test/gtest/ucp/ucp_datatype.h
Labels: Ready for Review, api, enhancement

#2359 Print all variables regardless of hardware availability
  src/tools/info/Makefile.am
  src/tools/info/cfg_info.c
  src/tools/info/ucx_info.c
  src/tools/info/ucx_info.h
  src/ucp/core/ucp_context.c
  src/ucs/config/global_opts.c
  src/ucs/config/parser.c
  src/ucs/config/parser.h
  src/uct/api/uct.h
  src/uct/base/uct_iface.h
  src/uct/base/uct_md.c
  src/uct/base/uct_md.h
Labels: api, cleanup, enhancement

#2360 UCT/RC/MLX5: Fix srq handling for HW TM
  src/uct/ib/rc/accel/rc_mlx5_common.c
  src/uct/ib/rc/base/rc_iface.c
Labels: bugfix

#2343 UCS: Allow profiling user application for release builds
  contrib/test_jenkins.sh
  src/tools/profile/read_profile.c
  src/ucp/amo/amo.inl
  src/ucp/amo/basic_amo.c
  src/ucp/amo/nb_amo.c
  src/ucp/core/ucp_request.inl
  src/ucp/dt/dt.c
  src/ucp/dt/dt.inl
  src/ucp/dt/dt_contig.c
  src/ucp/proto/proto_am.inl
  src/ucp/rma/basic_rma.c
  src/ucp/stream/stream_recv.c
  src/ucs/Makefile.am
  src/ucs/config/global_opts.c
  src/ucs/debug/debug.c
  src/ucs/debug/profile.h
  src/ucs/profile/profile.c
  src/ucs/profile/profile.h
  src/ucs/profile/profile_defs.h
  src/ucs/profile/profile_off.h
  src/ucs/profile/profile_on.h
  src/ucs/sys/init.c
  src/ucs/sys/rcache.c
  src/uct/base/uct_mem.c
  src/uct/ib/base/ib_md.c
  test/apps/Makefile.am
  test/examples/Makefile.am
  test/examples/ucx_profiling.c
  test/gtest/ucs/test_profile.cc
Labels: enhancement

#2356 UCT/RC/MLX5: Fix typo in comment
  src/uct/ib/rc/accel/rc_mlx5_common.c
Labels: bugfix

#2370 UCM: Use strerror_r in a portable way
  configure.ac
  src/ucm/util/log.c
  src/ucm/util/sys.c
  src/ucm/util/sys.h
Labels: bugfix, portability

#2367 UCT/IB: Remove prototype of deleted function
  src/uct/ib/base/ib_iface.h
Labels: cleanup

#2363 UCT/MLX5: added DM initialization
  config/m4/ib.m4
  src/uct/ib/mlx5/ib_mlx5.h
  src/uct/ib/rc/accel/rc_mlx5_common.c
  src/uct/ib/rc/accel/rc_mlx5_common.h
Labels: Waiting for Author Response, optimization

#2374 UCT/DC/MLX5: Register correct progress cb in worker
  src/uct/ib/dc/accel/dc_mlx5.c
Labels: optimization

#2366 UCS/UCM: Set UCM configuration from UCS during init time
  src/tools/info/ucx_info.c
  src/ucm/Makefile.am
  src/ucm/api/ucm.h
  src/ucm/cuda/install.c
  src/ucm/event/event.c
  src/ucm/malloc/malloc_hook.c
  src/ucm/mmap/install.c
  src/ucm/util/log.c
  src/ucm/util/log.h
  src/ucm/util/reloc.c
  src/ucm/util/sys.c
  src/ucm/util/ucm_config.c
  src/ucm/util/ucm_config.h
  src/ucs/Makefile.am
  src/ucs/config/ucm_opts.c
  test/gtest/common/main.cc
  test/gtest/ucm/malloc_hook.cc
  test/mpi/test_memhooks.c
Labels: enhancement

#2379 UCT/IB/MLX5: fixed compilation issue - v1.3.x
  src/uct/ib/dc/accel/dc_mlx5.c
  src/uct/ib/rc/accel/rc_mlx5_ep.c
Labels: portability

#2375 UCT/CUDA: use only driver API for memory detection
  src/uct/Makefile.am
  src/uct/cuda/base/cuda_md.c
  src/uct/cuda/base/cuda_md.h
  src/uct/cuda/cuda_copy/cuda_copy_md.c
  src/uct/cuda/cuda_copy/cuda_copy_md.h
  src/uct/cuda/gdr_copy/gdr_copy_md.c
  src/uct/cuda/gdr_copy/gdr_copy_md.h
Labels: cleanup

#2371 UCP: Fix RNDV_SEND_NBR_THRESH setting
  src/ucp/core/ucp_context.c
  src/ucp/core/ucp_ep.c
Labels: Ready for Review, bugfix

#2373 IB/DC: new vendor_part_id for ConnectX-5 and enable dc for a Generic HCA
  src/uct/ib/base/ib_device.c
  src/uct/ib/dc/base/dc_iface.c
  src/uct/ib/dc/base/dc_iface.h
Labels: enhancement

#2384 UCT/IB: Disable GDR-copy when ODP is used
  src/uct/base/uct_md.h
  src/uct/ib/base/ib_md.c
Labels: bugfix

#2333 ucp: add APIs for request-based put and get operations
  src/ucp/api/ucp.h
  src/ucp/rma/basic_rma.c
  test/gtest/common/test_helpers.h
  test/gtest/ucp/test_ucp_rma.cc
Labels: Ready for Review, api, feature

#2385 UCT/IB: Disable GDR-copy when ODP is used - v1.3.x
  src/uct/base/uct_md.h
  src/uct/ib/base/ib_md.c
Labels: bugfix

#2377 RPM Spec: bump version to 1.3.0
  ucx.spec.in
Labels: documentation

#2387 UCT/BASE: Add return status to uct_worker_tl_data_get()
  src/uct/base/uct_worker.h
  src/uct/ib/mlx5/ib_mlx5.c
Labels: enhancement

#2362 UCP/UCS: Memory type allocation cache
  contrib/test_jenkins.sh
  src/ucp/core/ucp_context.c
  src/ucp/core/ucp_context.h
  src/ucs/Makefile.am
  src/ucs/sys/memtype_cache.c
  src/ucs/sys/memtype_cache.h
  test/gtest/Makefile.am
  test/gtest/ucp/test_ucp_mem_type.cc
  test/gtest/ucs/test_memtype_cache.cc
Labels: Waiting for Author Response, optimization

#2381 UCP/UCS/CONFIG: Validate all provided env vars are valid during ucp_init
  src/ucp/core/ucp_context.c
  src/ucs/config/parser.c
  src/ucs/config/parser.h
  test/gtest/Makefile.am
Labels: enhancement

#2395 UCT/SELF: fixed hang in mpi-test-suite
  src/uct/sm/self/self.c
  src/uct/sm/self/self.h
Labels: bugfix

#2383 UCT/DOC: Fix documentation of uct_worker_create() - async cannot be NULL
  src/uct/api/uct.h
  src/uct/base/uct_worker.c
Labels: Ready for Review, api, documentation

#2411 UCP: minor cleanups
  src/ucp/wireup/select.c
Labels: bugfix

#2403 UCS/STRING: fixed compilation by gcc8+
  src/ucs/debug/debug.c
  src/ucs/sys/string.c
  src/ucs/sys/string.h
  src/ucs/sys/sys.c
Labels: bugfix

#2407 UCP: Fix md_index in rndv-put mode
  src/ucp/tag/rndv.c
Labels: bugfix

#2405 UCP/WORKER: Reduce address size by not passing peer name in release mode
  src/ucp/core/ucp_context.c
  src/ucp/wireup/address.c
Labels: optimization

#2378 UCT/MLX5/DM: added *_short send routines implementation
  src/uct/ib/rc/accel/rc_mlx5_common.c
  src/uct/ib/rc/accel/rc_mlx5_common.h
  src/uct/ib/rc/accel/rc_mlx5_ep.c
  src/uct/ib/rc/accel/rc_mlx5_iface.c
Labels: optimization

#2415 UCT/UD: fixed compilation by gcc8
  src/uct/ib/ud/base/ud_def.h
Labels: bugfix, portability

#2416 UCT/UD: fixed compilation by gcc8 v1.3
  src/uct/ib/ud/base/ud_def.h
Labels: bugfix, portability

#2399 API/UCP: Added clarifications to the ucp_worker_arm() documentation.
  src/ucp/api/ucp.h
Labels: Ready for Review, api, documentation

#2413 UCT/IB/MLX5: Move QP to RESET (instead of error) before cleaning the SRQ
  config/m4/ib.m4
  src/uct/ib/rc/accel/rc_mlx5_ep.c
  src/uct/ib/rc/base/rc_ep.c
Labels: bugfix

#2420 UCP/GTEST: Move the listener's wireup init flow to the main thread
  src/ucp/core/ucp_listener.c
  src/ucp/core/ucp_listener.h
  src/uct/ib/rdmacm/rdmacm_iface.c
  test/gtest/uct/ib/test_sockaddr.cc
  test/gtest/uct/uct_test.cc
Labels: bugfix

#2414 UCP/EP/INFO: Fix ep info print when there is no wireup lane
  src/ucp/core/ucp_ep.c
Labels: bugfix

#2418 UCP/EP: Fix missing initialization of rndv_send_nbr thresholds
  src/ucp/core/ucp_ep.c
Labels: bugfix

#2410 UCP: Respect AM score during tag offload lane setup
  src/ucp/wireup/select.c
Labels: Ready for Review, optimization

#2428 UCT/IB/MLX5: Move QP to RESET (instead of error) before cleaning the SRQ - v1.3.x
  config/m4/ib.m4
  src/uct/ib/rc/accel/rc_mlx5_ep.c
  src/uct/ib/rc/base/rc_ep.c
Labels: bugfix

#2430 UCP/EP/INFO: Fix ep info print when there is no wireup lane - v1.3.x
  src/ucp/core/ucp_ep.c
Labels: bugfix

#2431 UCP/EP: Fix missing initialization of rndv_send_nbr thresholds v1.3.x
  src/ucp/core/ucp_ep.c
Labels: bugfix

#2348 UCP/GTEST: Support the wakeup mechanism with client-server and test it.
  src/ucp/core/ucp_listener.c
  src/uct/api/uct.h
  test/gtest/ucp/test_ucp_sockaddr.cc
Labels: documentation, feature

#2422 UCT/RC/MLX5: Clean tag-matching QP from inprogress receives
  src/uct/ib/base/ib_device.c
  src/uct/ib/base/ib_device.h
  src/uct/ib/dc/accel/dc_mlx5.c
  src/uct/ib/dc/verbs/dc_verbs.c
  src/uct/ib/rc/accel/rc_mlx5_ep.c
  src/uct/ib/rc/base/rc_ep.c
  src/uct/ib/rc/base/rc_ep.h
Labels: bugfix

#2427 UCS/CONFIG: During exit, issue warning if a UCX_ env var was never used
  contrib/test_jenkins.sh
  src/ucp/core/ucp_context.c
  src/ucs/config/global_opts.c
  src/ucs/config/global_opts.h
  src/ucs/config/parser.c
  src/ucs/config/parser.h
  src/ucs/sys/init.c
  src/ucs/type/component.h
Labels: enhancement

#2432 TEST/JENKINS: In ucp_client_server, the server's listener is always up
  contrib/test_jenkins.sh
  test/examples/ucp_client_server.c
Labels: test

#2423 UCT/API: Add API for GET SHORT.
  src/tools/info/tl_info.c
  src/tools/perf/libperf.c
  src/ucp/core/ucp_ep.c
  src/ucp/core/ucp_ep.h
  src/ucp/wireup/address.h
  src/ucp/wireup/wireup_ep.c
  src/uct/api/tl.h
  src/uct/api/uct.h
  src/uct/base/uct_iface.c
Labels: api, feature

#2445 GTEST/UCT: Fix rc_mlx5/uct_p2p_err_test.remote_access_error
  test/gtest/uct/test_p2p_err.cc
  test/gtest/uct/uct_test.cc
Labels: bugfix

#2443 IB/DC: new vendor_part_id for ConnectX-5 and enable dc for a Generic HCA - v1.3.x
  src/uct/ib/base/ib_device.c
  src/uct/ib/dc/base/dc_iface.c
  src/uct/ib/dc/base/dc_iface.h
Labels: bugfix

#2444 UCS/PARSER: fixed crash on exit
  src/ucs/config/parser.c
  src/ucs/datastruct/khash.h
Labels: bugfix

#2451 UCT/RCX/IFACE: fixed typo in macro
  src/uct/ib/rc/base/rc_iface.h
Labels: bugfix

#2438 UCT/RC/DC: Do not translate TMH to BE
  src/uct/ib/dc/accel/dc_mlx5.c
  src/uct/ib/dc/verbs/dc_verbs.c
  src/uct/ib/rc/accel/rc_mlx5_common.c
  src/uct/ib/rc/accel/rc_mlx5_common.h
  src/uct/ib/rc/accel/rc_mlx5_ep.c
  src/uct/ib/rc/base/rc_ep.c
  src/uct/ib/rc/base/rc_ep.h
  src/uct/ib/rc/base/rc_iface.c
  src/uct/ib/rc/base/rc_iface.h
  src/uct/ib/rc/verbs/rc_verbs_common.c
  src/uct/ib/rc/verbs/rc_verbs_common.h
  src/uct/ib/rc/verbs/rc_verbs_ep.c
Labels: Ready for Review, optimization

#2338 UCT/IB: Use separate resource domain for mlx5 trasnports
  config/m4/ib.m4
  contrib/test_jenkins.sh
  contrib/valgrind.supp
  src/uct/ib/base/ib_iface.c
  src/uct/ib/base/ib_iface.h
  src/uct/ib/base/ib_verbs.h
  src/uct/ib/cm/cm_iface.c
  src/uct/ib/dc/accel/dc_mlx5.c
  src/uct/ib/dc/base/dc_iface.c
  src/uct/ib/dc/base/dc_iface.h
  src/uct/ib/dc/verbs/dc_verbs.c
  src/uct/ib/mlx5/ib_mlx5.h
  src/uct/ib/rc/accel/rc_mlx5_iface.c
  src/uct/ib/rc/base/rc_ep.c
  src/uct/ib/rc/base/rc_iface.c
  src/uct/ib/rc/base/rc_iface.h
  src/uct/ib/rc/verbs/rc_verbs_iface.c
  src/uct/ib/ud/accel/ud_mlx5.c
  src/uct/ib/ud/base/ud_iface.c
  src/uct/ib/ud/base/ud_iface.h
  src/uct/ib/ud/verbs/ud_verbs.c
Labels: bugfix

#2456 UCP/TAG: Optimize unexp eager offload handling
  src/ucp/core/ucp_request.inl
  src/ucp/tag/eager_rcv.c
  src/ucp/tag/rndv.c
Labels: optimization

#2458 UCT/RCX/DCX: Optimize path for small unexp messages
  src/uct/ib/rc/accel/rc_mlx5_common.h
Labels: optimization

#2459 UCP/TAG: Remove UCP_EP_FLAG_TAG_OFFLOAD_ENABLED flag
  src/ucp/core/ucp_ep.c
  src/ucp/core/ucp_ep.h
  src/ucp/tag/eager.h
  src/ucp/tag/rndv.c
  src/ucp/tag/tag_send.c
  src/ucp/wireup/wireup.c
  test/gtest/ucp/test_ucp_tag_offload.cc
Labels: optimization

#2460 GTEST/UCP: Re-enable tag offload multi test
  test/gtest/ucp/test_ucp_tag_offload.cc
Labels: Ready for Review, bugfix, test

#2462 UCT/ATOMIC: bit-op preparation: renaming of func-macro
  src/uct/ib/dc/accel/dc_mlx5.c
  src/uct/ib/dc/verbs/dc_verbs.c
  src/uct/ib/rc/accel/rc_mlx5_ep.c
  src/uct/ib/rc/base/rc_iface.h
  src/uct/ib/rc/verbs/rc_verbs_ep.c
Labels: enhancement

#2457 UCT/UD: Fix reordering with pending queue for sends from am callback
  src/uct/ib/ud/base/ud_ep.c
  src/uct/ib/ud/base/ud_ep.h
  src/uct/ib/ud/base/ud_inl.h
  test/gtest/common/test_obj_size.cc
  test/gtest/ucp/test_ucp_fence.cc
  test/gtest/ucp/test_ucp_memheap.cc
  test/gtest/ucp/test_ucp_rma_mt.cc
  test/gtest/ucp/test_ucp_wireup.cc
Labels: bugfix
