Repository openucx/ucx, pull requests merged in 2018-07, with the labels that each got.

#2708 UCT/TCP: Ignore unknown link speed, set it to 100 Mbps by default
  src/uct/tcp/tcp_net.c
Labels: bugfix

#2712 UCS/UCT: Added flags to the mem_reg function in ucs_rcache_ops.
  src/ucs/sys/rcache.c
  src/ucs/sys/rcache.h
  src/uct/cuda/gdr_copy/gdr_copy_md.c
  src/uct/ib/base/ib_md.c
  src/uct/sm/knem/knem_md.c
  test/gtest/ucs/test_rcache.cc
Labels: enhancement

#2714 UCP/UCT/GTEST: if can't work on an md, skip it and move to the next one.
  src/ucp/core/ucp_context.c
  test/gtest/ucp/ucp_test.cc
  test/gtest/uct/uct_test.cc
Labels: enhancement

#2717 CONFIG/KNEM: Fail the build if knem was requested but not found.
  config/m4/knem.m4
Labels: bugfix

#2716 UCP/TAG: Fix eager max_short config
  src/ucp/core/ucp_ep.c
  src/ucp/core/ucp_ep.h
  src/ucp/tag/tag_send.c
Labels: optimization

#2695 IB: Use mlx5dv.h
  config/m4/ib.m4
  configure.ac
  src/ucm/malloc/malloc_hook.c
  src/uct/Makefile.am
  src/uct/ib/mlx5/ib_mlx5.c
  src/uct/ib/mlx5/ib_mlx5.h
  src/uct/ib/mlx5/ib_mlx5_dv.c
  src/uct/ib/mlx5/ib_mlx5_dv.h
  src/uct/ib/mlx5/ib_mlx5_hw.c
  src/uct/ib/mlx5/ib_mlx5_hw.h
  src/uct/ib/rc/accel/rc_mlx5_common.c
Labels: portability

#2719 UCP/UCT: Add flag for mem reg error supression
  src/ucp/core/ucp_mm.c
  src/ucp/core/ucp_request.c
  src/ucp/core/ucp_request.h
  src/ucp/core/ucp_request.inl
  src/ucp/tag/offload.c
  src/uct/api/uct.h
  src/uct/ib/base/ib_md.c
Labels: Ready for Review, api, bugfix

#2722 IB/DV: Fix CQ poll/arm/clean
  config/m4/ib.m4
  src/uct/ib/base/ib_iface.c
  src/uct/ib/base/ib_iface.h
  src/uct/ib/cm/cm_iface.c
  src/uct/ib/dc/accel/dc_mlx5.c
  src/uct/ib/dc/base/dc_iface.c
  src/uct/ib/dc/verbs/dc_verbs.c
  src/uct/ib/mlx5/ib_mlx5.c
  src/uct/ib/mlx5/ib_mlx5.h
  src/uct/ib/mlx5/ib_mlx5_dv.c
  src/uct/ib/mlx5/ib_mlx5_dv.h
  src/uct/ib/mlx5/ib_mlx5_hw.c
  src/uct/ib/rc/accel/rc_mlx5_common.c
  src/uct/ib/rc/accel/rc_mlx5_common.h
  src/uct/ib/rc/accel/rc_mlx5_ep.c
  src/uct/ib/rc/accel/rc_mlx5_iface.c
  src/uct/ib/rc/base/rc_iface.c
  src/uct/ib/rc/verbs/rc_verbs_common.h
  src/uct/ib/rc/verbs/rc_verbs_iface.c
  src/uct/ib/ud/accel/ud_mlx5.c
  src/uct/ib/ud/accel/ud_mlx5.h
  src/uct/ib/ud/base/ud_iface.c
  src/uct/ib/ud/verbs/ud_verbs.c
  test/gtest/uct/ib/test_ib.cc
Labels: Waiting for Author Response, feature

#2728 UCT/IB: Clarify the meaning of TX_CQ_MODERATION
  src/uct/ib/base/ib_iface.c
Labels: documentation

#2692 UCP/CUDA-IPC: enable protocols using cuda-ipc for inter-node GPU transfers
  src/tools/perf/libperf.c
  src/ucp/core/ucp_rkey.c
  src/ucp/tag/rndv.c
  src/ucp/wireup/select.c
  src/uct/cuda/cuda_ipc/cuda_ipc_ep.c
  src/uct/cuda/cuda_ipc/cuda_ipc_md.c
  src/uct/cuda/cuda_ipc/cuda_ipc_md.h
  test/gtest/uct/uct_test.h
Labels: enhancement

#2731 Fix installing malloc hook symbols for shmat(REMAP) and mmap(FIXED)
  contrib/test_jenkins.sh
  src/ucm/event/event.c
  test/mpi/test_memhooks.c
Labels: bugfix

#2732 Fix malloc hook symbols for shmat(REMAP) and mmap(FIXED) - v1.3.x
  contrib/test_jenkins.sh
  src/ucm/event/event.c
  test/gtest/ucm/cuda_hooks.cc
  test/mpi/test_memhooks.c
Labels: bugfix

#2739 Unit test portability fixes
  test/gtest/ucp/test_ucp_wireup.cc
  test/gtest/uct/test_pending.cc
Labels: bugfix, test

#2740 UCT/DC: Fix DCI pending allocation scheme
  src/uct/ib/dc/base/dc_ep.c
  test/gtest/uct/ib/test_dc.cc
Labels: bugfix

#2734 UCP/CUDA-IPC: enable protocols using cuda-ipc for inter-node GPU transfers- v1.4.x
  src/tools/perf/libperf.c
  src/ucp/core/ucp_rkey.c
  src/ucp/tag/rndv.c
  src/ucp/wireup/select.c
  src/uct/cuda/cuda_ipc/cuda_ipc_ep.c
  src/uct/cuda/cuda_ipc/cuda_ipc_md.c
  src/uct/cuda/cuda_ipc/cuda_ipc_md.h
  test/gtest/uct/uct_test.h
Labels: enhancement

#2745 UCT/DC: Fix DCI pending allocation scheme - v1.4.x
  src/uct/ib/dc/base/dc_ep.c
  test/gtest/uct/ib/test_dc.cc
Labels: Ready for Review, bugfix

#2744 UCT/DC: Fix DCI pending allocation scheme - v1.3.x
  src/uct/ib/dc/base/dc_ep.c
  test/gtest/uct/ib/test_dc.cc
Labels: Ready for Review, bugfix

#2757 UCS/STATS: suppressed build warning
  src/ucs/stats/stats_fwd.h
Labels: bugfix, portability

#2756 UCM/CUDA: do not generate VM_UNMAP for cudaFree with NULL
  src/ucm/event/event.c
  test/gtest/ucm/cuda_hooks.cc
Labels: bugfix

#2738 UCT/CUDA_IPC: caching for remote cuda ipc memhandle mappings
  src/ucs/datastruct/pgtable.c
  src/uct/Makefile.am
  src/uct/cuda/cuda_ipc/cuda_ipc_cache.c
  src/uct/cuda/cuda_ipc/cuda_ipc_cache.h
  src/uct/cuda/cuda_ipc/cuda_ipc_ep.c
  src/uct/cuda/cuda_ipc/cuda_ipc_ep.h
  src/uct/cuda/cuda_ipc/cuda_ipc_iface.c
  src/uct/cuda/cuda_ipc/cuda_ipc_iface.h
Labels: optimization

#2758 UCS/STATS: suppressed build warning - v1.4
  src/ucs/stats/stats_fwd.h
Labels: portability

#2760 UCT/CUDA_IPC: caching for remote cuda ipc memhandle mappings -v1.4.x
  src/ucs/datastruct/pgtable.c
  src/uct/Makefile.am
  src/uct/cuda/cuda_ipc/cuda_ipc_cache.c
  src/uct/cuda/cuda_ipc/cuda_ipc_cache.h
  src/uct/cuda/cuda_ipc/cuda_ipc_ep.c
  src/uct/cuda/cuda_ipc/cuda_ipc_ep.h
  src/uct/cuda/cuda_ipc/cuda_ipc_iface.c
  src/uct/cuda/cuda_ipc/cuda_ipc_iface.h
Labels: bugfix

#2759 UCM/CUDA: do not generate VM_UNMAP for cudaFree with NULL - v1.4.x
  src/ucm/event/event.c
  test/gtest/ucm/cuda_hooks.cc
Labels: bugfix

#2768 UCS/PGTABLE: return error instead of assert on inserting overlapped r…
  src/ucs/datastruct/pgtable.c
Labels: bugfix
