Repository openucx/ucx, pull requests merged in 2018-09, with the labels that each got.

#2828 UCM/RELOC: fix modifying GOT mechanism
  src/ucm/util/reloc.c
Labels: bugfix

#2819 UCP/API: Deprecate blocking AMO and RMA operations
  src/ucp/api/ucp.h
  src/ucp/api/ucp_compat.h
Labels: Ready for Review, api, documentation

#2844 UCS/SYS: Fallback to malloc() if hugepages are not supported
  src/ucs/sys/sys.c
Labels: bugfix

#2846 BUILD: Check for mlx5dv.h w/o default includes
  config/m4/ib.m4
Labels: bugfix

#2845 UCT/IB: Workaround invalid GCC vectorization for DM byte-copy loop
  src/ucs/sys/compiler.h
  src/uct/ib/mlx5/ib_mlx5.inl
  src/uct/ib/rc/accel/rc_mlx5_common.h
Labels: bugfix

#2850 Fix broken links in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#2853 Fixed for MLNX_OFED 4.4 testing - v1.4.x
  contrib/valgrind.supp
  test/apps/test_ucx_tls.py
Labels: bugfix

#2857 GTEST: Fix test_tag tests - v.1.4.x
  test/gtest/uct/test_tag.cc
Labels: bugfix

#2863 UCT/IB: Wrap calls to ibv_wc_status_str() from header files
  src/uct/ib/base/ib_device.c
  src/uct/ib/base/ib_device.h
  src/uct/ib/base/ib_iface.h
  src/uct/ib/rc/accel/rc_mlx5_common.h
  src/uct/ib/rc/verbs/rc_verbs_common.h
  test/gtest/common/test_obj_size.cc
Labels: bugfix

#2862 EXAMPLE: fixed missing initialization of EP
  contrib/test_jenkins.sh
  test/examples/uct_hello_world.c
Labels: bugfix, test

#2752 UCP/STREAM/CUDA: enable cuda buffers in stream api
  contrib/ucx_perftest_config/test_types
  src/ucp/stream/stream_recv.c
  src/ucp/stream/stream_send.c
Labels: WIP-DNM, Waiting for Author Response

#2840 UCP/API: client-server connection establishment
  src/ucp/api/ucp.h
  src/ucp/api/ucp_compat.h
  src/ucp/api/ucp_def.h
Labels: Ready for Review, api

#2794 POWER: improve store mem barrier
  src/ucs/arch/ppc64/cpu.h
Labels: Optimization

#2869 UCM/RELOC: fix modifying GOT mechanism v1.4.x
  src/ucm/util/reloc.c
Labels: Bugfix

#2868 Fixed uct hello world crash v1.4
  contrib/test_jenkins.sh
  test/examples/uct_hello_world.c
Labels: Bugfix

#2878 GTEST/UCP/SOCKADDR: fix log handlers leak
  test/gtest/ucp/test_ucp_sockaddr.cc
Labels: Bugfix

#2887 UCP/TAG: Minor cleanups in tag offload
  src/ucp/tag/offload.c
Labels: Cleanup

#2884 TEST/EXAMPLES: ucp_hello_world.c code cleanup.
  test/examples/ucp_hello_world.c
Labels: Documentation, Waiting for Author Response

#2891 TEST/IB: Enable ODP tests on aarch64 and ppc64
  test/gtest/uct/ib/test_ib_xfer.cc
Labels: Bugfix

#2873 UCT/TAG: Add stats for tag API
  src/uct/base/uct_iface.c
  src/uct/base/uct_iface.h
  src/uct/ib/dc/accel/dc_mlx5.c
  src/uct/ib/dc/verbs/dc_verbs.c
  src/uct/ib/rc/accel/rc_mlx5_common.h
  src/uct/ib/rc/accel/rc_mlx5_ep.c
  src/uct/ib/rc/base/rc_iface.c
  src/uct/ib/rc/base/rc_iface.h
  src/uct/ib/rc/verbs/rc_verbs_common.h
  src/uct/ib/rc/verbs/rc_verbs_ep.c
  test/gtest/uct/test_tag.cc
Labels: Enhancement, Ready for Review

#2843 Updating news and authors files
  AUTHORS
  NEWS
Labels: Documentation, Ready for Review

#2898 UCM/RELOC: add dlopen symbol to reloc patch list
  src/ucm/util/reloc.c
Labels: Bugfix

#2870 UCP: improve check parameters in API routines
  src/ucp/core/ucp_context.c
  src/ucp/core/ucp_context.h
  src/ucp/core/ucp_rkey.c
  src/ucp/core/ucp_worker.c
  src/ucp/rma/amo_send.c
  src/ucp/rma/rma_send.c
  src/ucp/stream/stream_recv.c
  src/ucp/stream/stream_send.c
  src/ucp/tag/probe.c
  src/ucp/tag/tag_recv.c
  src/ucp/tag/tag_send.c
  test/gtest/ucp/test_ucp_peer_failure.cc
Labels: Enhancement, Ready for Review
