Repository openucx/ucx, pull requests merged in 2018-05, with the labels that each got.

#2573 Revert "UCT/CM: Return empty resource list if ib_ucm.ko driver is not loaded"
  src/uct/ib/cm/cm_iface.c
Labels: bugfix

#2574 TEST/UD: Fix test_ud_slow_timer.tick1
  test/gtest/uct/ib/test_ud_slow_timer.cc
Labels: bugfix, test

#2566 UCS/MEMTRACK: Revamp memtrack service to avoid changing allocation size
  src/ucs/debug/memtrack.c
  src/ucs/debug/memtrack.h
  src/ucs/sys/sys.c
  src/ucs/time/timerq.c
  src/uct/ib/base/ib_md.c
  test/gtest/ucs/test_memtrack.cc
Labels: cleanup, enhancement

#2563 UCT/UCP: atomic cleanup
  src/tools/info/tl_info.c
  src/tools/perf/libperf.c
  src/ucp/core/ucp_proxy_ep.c
  src/ucp/core/ucp_worker.h
  src/ucp/wireup/select.c
  src/ucp/wireup/wireup_ep.c
  src/uct/api/tl.h
  src/uct/api/uct.h
  src/uct/base/uct_iface.c
  src/uct/ib/dc/accel/dc_mlx5.c
  src/uct/ib/dc/verbs/dc_verbs.c
  src/uct/ib/rc/accel/rc_mlx5.h
  src/uct/ib/rc/accel/rc_mlx5_ep.c
  src/uct/ib/rc/accel/rc_mlx5_iface.c
  src/uct/ib/rc/base/rc_iface.c
  src/uct/ib/rc/verbs/rc_verbs.h
  src/uct/ib/rc/verbs/rc_verbs_ep.c
  src/uct/ib/rc/verbs/rc_verbs_iface.c
  src/uct/sm/base/sm_ep.c
  src/uct/sm/base/sm_ep.h
  src/uct/sm/mm/mm_iface.c
  src/uct/sm/self/self.c
  src/uct/ugni/rdma/ugni_rdma_iface.c
  test/gtest/uct/test_amo_cswap.cc
  test/gtest/uct/test_amo_swap.cc
Labels: Waiting for Author Response, api, cleanup

#2579 UCT/RDMACM: Fix a race caused by two threads accessing slow progress id.
  src/uct/base/uct_worker.c
  src/uct/ib/rdmacm/rdmacm_ep.c
Labels: bugfix

#2567 TEST/SOCKADDR: Full support for TCP
  test/apps/sockaddr/sa_base.h
  test/apps/sockaddr/sa_main.cc
  test/apps/sockaddr/sa_tcp.cc
  test/apps/sockaddr/sa_tcp.h
  test/apps/sockaddr/sa_util.cc
  test/apps/sockaddr/sa_util.h
Labels: test

#2583 TEST/JENKINS: Avoid testing rdmacm on ib device with node_guid==0x0
  contrib/test_jenkins.sh
  test/gtest/common/test_helpers.cc
  test/gtest/common/test_helpers.h
  test/gtest/ucp/test_ucp_sockaddr.cc
  test/gtest/uct/ib/test_sockaddr.cc
  test/gtest/uct/test_md.cc
  test/gtest/uct/uct_test.cc
Labels: test

#2584 UCP/STREAM: Code cleanups
  src/ucp/stream/stream_send.c
Labels: cleanup

#2571 UCT/CUDA-IPC: Adding implementation (initial reviews incorporated)
  src/uct/cuda/base/cuda_iface.h
  src/uct/cuda/cuda_ipc/cuda_ipc_ep.c
  src/uct/cuda/cuda_ipc/cuda_ipc_iface.c
  src/uct/cuda/cuda_ipc/cuda_ipc_iface.h
  src/uct/cuda/cuda_ipc/cuda_ipc_md.c
  src/uct/cuda/cuda_ipc/cuda_ipc_md.h
  test/gtest/uct/test_md.cc
  test/gtest/uct/test_p2p_rma.cc
  test/gtest/uct/test_stats.cc
  test/gtest/uct/test_uct_perf.cc
  test/gtest/uct/test_zcopy_comp.cc
  test/gtest/uct/uct_test.h
Labels: feature

#2572 UCP/GTEST: Client-server - handle a case of a large worker address.
  contrib/test_jenkins.sh
  src/ucp/core/ucp_context.c
  src/ucp/core/ucp_context.h
  src/ucp/core/ucp_ep.c
  src/ucp/core/ucp_ep.h
  src/ucp/core/ucp_listener.c
  src/ucp/core/ucp_listener.h
  src/ucp/wireup/wireup.c
  src/ucp/wireup/wireup.h
  src/ucp/wireup/wireup_ep.c
  src/ucp/wireup/wireup_ep.h
  test/gtest/ucp/test_ucp_sockaddr.cc
Labels: enhancement

#2576 UCP/API/WIREUP: Fix loopback connections
  src/ucp/api/ucp.h
  src/ucp/core/ucp_ep.c
  src/ucp/wireup/wireup.c
  test/gtest/common/test_helpers.h
  test/gtest/ucp/test_ucp_wireup.cc
Labels: Ready for Review, api, bugfix

#2517 UCT/IB: Use KSM for atomic_mr
  config/m4/ib.m4
  src/uct/ib/base/ib_md.c
  src/uct/ib/base/ib_md.h
  src/uct/ib/base/ib_verbs.h
  test/gtest/uct/ib/test_ib_md.cc
Labels: Waiting for Author Response, bugfix

#2597 UCP/RNDV: Register only the receive buffer part which is used for RMA
  src/ucp/core/ucp_request.inl
  src/ucp/tag/rndv.c
Labels: optimization

#2599 UCP/REQUEST: Make ucp_request_send_state_ff() non-inline
  src/ucp/core/ucp_request.c
  src/ucp/core/ucp_request.h
  src/ucp/core/ucp_request.inl
Labels: enhancement

#2596 TEST/JENKINS: Don't run client/server test if no IPv4 address on the netdev
  contrib/test_jenkins.sh
Labels: test

#2600 UCP/RMA: Complete send request in case of error
  src/ucp/rma/basic_rma.c
Labels: bugfix

#2602 UCP/FLUSH: Use ucp_request_get() macro
  src/ucp/rma/flush.c
  src/ucp/wireup/wireup_ep.c
Labels: enhancement

#2594 UCP: Enhance the requirement when selecting sockaddr aux transports.
  src/ucp/wireup/wireup_ep.c
Labels: enhancement

#2590 README: Add instructions for running unit tests
  README
Labels: Ready for Review, documentation

#2607 Small test fixes
  test/gtest/ucs/test_async.cc
  test/gtest/uct/ib/test_ib_xfer.cc
Labels: test

#2595 UCP/GTEST: Fix setting mask for available tls.
  src/ucp/core/ucp_context.c
  src/ucp/core/ucp_context.h
  test/gtest/ucp/test_ucp_perf.cc
  test/gtest/ucp/ucp_test.cc
Labels: bugfix

#2604 JENKINS: Wait longer time for ucp_hello_world server to start
  contrib/test_jenkins.sh
Labels: test

#2605 UCS/TEST/UGNI: Warn about async context being busy when destroyed
  src/ucm/malloc/malloc_hook.c
  src/ucs/Makefile.am
  src/ucs/async/async.c
  src/ucs/async/async_int.h
  src/ucs/async/signal.c
  src/ucs/async/thread.c
  src/ucs/type/spinlock.c
  src/ucs/type/spinlock.h
  src/uct/ugni/base/ugni_device.c
  test/gtest/ucs/test_async.cc
Labels: enhancement

#2591 UCP/MM/TEST: Allow mmap with address=NULL and length=0
  src/ucp/api/ucp.h
  src/ucp/core/ucp_mm.c
  test/gtest/ucp/test_ucp_mmap.cc
Labels: Ready for Review, api

#2615 UCS/UCT/MM: Prevent potential out-of-order sending in shared memory.
  src/ucs/arch/ppc64/cpu.h
  src/uct/sm/mm/mm_ep.c
Labels: bugfix

#2609 UCP/EP: Don't call error callback for internal endpoints
  src/ucp/core/ucp_worker.c
Labels: bugfix

#2618 UCP/BCOPY: removed deprecated staff on bcopy-multi
  src/ucp/proto/proto_am.inl
  src/ucp/stream/stream_send.c
  src/ucp/tag/eager_snd.c
  src/ucp/tag/rndv.c
Labels: cleanup

#2617 TEST/JENKINS: Avoid testing rdmacm on ib device with node_guid==0x0
  test/gtest/common/test_helpers.cc
  test/gtest/common/test_helpers.h
  test/gtest/ucp/test_ucp_sockaddr.cc
  test/gtest/uct/ib/test_sockaddr.cc
  test/gtest/uct/test_md.cc
  test/gtest/uct/uct_test.cc
Labels: test

#2620 UCP/WIREUP: Fix race conditions in wireup
  src/ucp/wireup/wireup.c
  src/ucp/wireup/wireup_ep.c
Labels: bugfix

#2621 MM: Adding an assert and using an existing function.
  src/uct/sm/mm/mm_ep.c
Labels: cleanup

#2622 MM: Adding an assert and using an existing function.
  src/uct/sm/mm/mm_ep.c
Labels: cleanup

#2610 UCP/WIREUP: Avoid wireup_ep switch if ep in error state
  src/ucp/core/ucp_worker.c
  src/ucp/wireup/wireup_ep.c
Labels: bugfix

#2589 UCT/IB/TAG: Increase MAX_BCOPY for HW TM
  src/ucp/core/ucp_context.c
  src/ucp/core/ucp_context.h
  src/ucp/core/ucp_request.c
  src/ucp/core/ucp_request.h
  src/ucp/stream/stream_send.c
  src/ucp/tag/offload.c
  src/ucp/tag/tag_send.c
  src/uct/ib/base/ib_iface.c
  src/uct/ib/cm/cm_iface.c
  src/uct/ib/rc/base/rc_iface.c
  src/uct/ib/rc/base/rc_iface.h
  src/uct/ib/ud/base/ud_iface.c
  test/gtest/ucp/test_ucp_tag_match.cc
  test/gtest/ucp/test_ucp_tag_xfer.cc
  test/gtest/uct/test_tag.cc
Labels: Waiting for Author Response, bugfix, optimization

#2625 UCS/PGTABLE/TEST: Fix lookup for range larger than page table span - v1.3.x
  src/ucs/datastruct/pgtable.c
  test/gtest/ucs/test_pgtable.cc
Labels: bugfix

#2624 UCS/RCACHE: Check that physical pages of rcache regions are not moved
  src/ucs/config/global_opts.c
  src/ucs/config/global_opts.h
  src/ucs/sys/rcache.c
  src/ucs/sys/rcache.h
  src/ucs/sys/sys.c
  src/ucs/sys/sys.h
Labels: enhancement

#2628 UCP/TAG/TEST: Fix handling empty IOV buffers
  src/ucp/core/ucp_request.c
  src/ucp/core/ucp_request.h
  src/ucp/dt/dt_iov.c
  src/ucp/dt/dt_iov.h
  src/ucp/proto/proto_am.inl
  src/ucp/stream/stream_send.c
  src/ucp/tag/tag_send.c
  test/gtest/ucp/test_ucp_tag_xfer.cc
  test/gtest/ucp/ucp_datatype.h
Labels: bugfix

#2637 GTEST: added ucp_datatype.h to tarball
  test/gtest/Makefile.am
Labels: bugfix

#2639 IB/DC: Set the traffic_class and gid_index in ibv_exp_dct_init_attr
  src/uct/ib/dc/base/dc_iface.c
Labels: bugfix

#2638 TOOLS: Better support of '-h' argument of ucx_info and ucx_read_profile
  contrib/ucx_perftest_config/README
  src/tools/info/ucx_info.c
  src/tools/profile/read_profile.c
Labels: documentation, enhancement

#2635 UCP/API: revert ucp_ep_close_sync API
  src/ucp/api/ucp.h
  src/ucs/type/status.h
Labels: api, cleanup

#2626 UCS/SYS/UCT: Avoid allocating huge pages if not supported by the system
  src/ucs/sys/sys.c
  src/ucs/sys/sys.h
  src/uct/base/uct_mem.c
Labels: portability

#2629 UCT/IB/UD: Improve AV logging and show dgid/rmac
  src/uct/ib/mlx5/ib_mlx5.h
  src/uct/ib/mlx5/ib_mlx5_log.c
  src/uct/ib/ud/base/ud_iface.c
Labels: enhancement

#2603 TEST/UCP/ERROR: Refactor test_ucp_peer_failure
  test/gtest/common/test.cc
  test/gtest/common/test.h
  test/gtest/ucp/test_ucp_peer_failure.cc
  test/gtest/ucp/ucp_test.cc
  test/gtest/ucp/ucp_test.h
  test/gtest/uct/ib/test_ib_xfer.cc
  test/gtest/uct/test_peer_failure.cc
Labels: cleanup, test

#2645 UCT/UD: Don't report errors for internal endpoints
  src/uct/ib/ud/base/ud_ep.c
  src/uct/ib/ud/base/ud_ep.h
  src/uct/ib/ud/base/ud_iface.c
Labels: bugfix

#2643 Test fixes for ppc and VM jenkins slaves
  contrib/test_jenkins.sh
  src/ucs/stats/libstats.h
Labels: bugfix, test

#2647 UCP/CONFIG: added MAX_XXX_RAILS variables
  src/ucp/core/ucp_context.c
  src/ucs/config/parser.c
Labels: enhancement

#2646 UCT/CUDA-IPC: khash for cuda-ipc memhandles
  src/uct/cuda/cuda_ipc/cuda_ipc_ep.c
  src/uct/cuda/cuda_ipc/cuda_ipc_ep.h
  src/uct/cuda/cuda_ipc/cuda_ipc_iface.c
  src/uct/cuda/cuda_ipc/cuda_ipc_iface.h
  src/uct/cuda/cuda_ipc/cuda_ipc_md.c
Labels: optimization

#2653 UCM/TEST: Support tcmalloc
  config/m4/ucm.m4
  configure.ac
  contrib/test_jenkins.sh
  src/ucm/api/ucm.h
  src/ucm/event/event.c
  src/ucm/malloc/malloc_hook.c
  src/ucm/mmap/install.c
  src/ucm/mmap/mmap.h
  src/ucm/util/reloc.c
  src/ucm/util/replace.c
  src/ucm/util/sys.c
  src/ucm/util/sys.h
  src/ucs/config/parser.c
  test/apps/Makefile.am
  test/apps/test_dlopen.c
  test/apps/test_tcmalloc.c
  test/examples/uct_hello_world.c
Labels: bugfix
