Repository openucx/ucx, pull requests merged in 2019-06, with the labels that each got.

#3635 UCT/API: Add 'component' parameter to md_open and rkey functions
  src/tools/info/tl_info.c
  src/tools/perf/lib/libperf.c
  src/ucp/core/ucp_context.c
  src/ucp/core/ucp_mm.c
  src/ucp/core/ucp_rkey.c
  src/uct/api/uct.h
  src/uct/base/uct_md.c
  test/examples/uct_hello_world.c
  test/gtest/uct/test_md.cc
  test/gtest/uct/test_mem.cc
  test/gtest/uct/uct_test.cc
Labels: API

#3662 Multiple fixes for UCX v1.5.2
  NEWS
  configure.ac
  contrib/test_jenkins.sh
  src/ucp/rma/amo_sw.c
  src/ucp/rma/rma.inl
  src/ucp/rma/rma_sw.c
  src/ucs/config/parser.c
  src/ucs/config/parser.h
  src/ucs/sys/sys.c
  src/uct/ib/base/ib_iface.c
  src/uct/ib/dc/base/dc_iface.c
  test/apps/Makefile.am
  test/apps/test_dlopen_cfg_print.c
  ucx.spec.in
Labels: Bugfix

#3478 UCT/CUDA_IPC: event notification support
  src/uct/cuda/cuda_ipc/cuda_ipc_iface.c
  src/uct/cuda/cuda_ipc/cuda_ipc_iface.h
Labels: Waiting for Author Response

#3673 UCP/API/DOC: Add clarification for ucp_ep_rkey_unpack()
  src/ucp/api/ucp.h
Labels: API, Documentation

#3510 UCP/TAG: Fix to use am short for HOST buffers when MEMTYPE cache is off
  src/ucp/core/ucp_context.h
  src/ucp/core/ucp_ep.c
  src/ucp/core/ucp_ep.h
  src/ucp/tag/tag_send.c
Labels: Waiting for Author Response

#3710 UCT/API: Replace md_name by component handle in uct_md_config_read()
  src/tools/info/tl_info.c
  src/tools/perf/lib/libperf.c
  src/ucp/core/ucp_context.c
  src/uct/api/uct.h
  src/uct/base/uct_md.c
  test/examples/uct_hello_world.c
  test/gtest/uct/test_md.cc
  test/gtest/uct/test_mem.cc
  test/gtest/uct/uct_test.cc
Labels: API, Enhancement

#3424 UCT/UCP/MEM_TYPE: Refactor memory type detection
  src/ucp/core/ucp_context.c
  src/ucp/core/ucp_context.h
  src/ucp/core/ucp_ep.c
  src/ucp/core/ucp_rkey.c
  src/ucp/core/ucp_worker.c
  src/ucp/wireup/select.c
  src/uct/api/uct.h
  src/uct/base/uct_md.c
  src/uct/base/uct_md.h
  src/uct/base/uct_mem.c
  src/uct/cuda/base/cuda_md.c
  src/uct/cuda/base/cuda_md.h
  src/uct/cuda/cuda_copy/cuda_copy_md.c
  src/uct/cuda/cuda_ipc/cuda_ipc_md.c
  src/uct/cuda/gdr_copy/gdr_copy_md.c
  src/uct/ib/base/ib_md.c
  src/uct/ib/rdmacm/rdmacm_md.c
  src/uct/rocm/base/rocm_base.c
  src/uct/rocm/base/rocm_base.h
  src/uct/rocm/copy/rocm_copy_md.c
  src/uct/rocm/gdr/rocm_gdr_md.c
  src/uct/rocm/ipc/rocm_ipc_md.c
  src/uct/sm/cma/cma_md.c
  src/uct/sm/knem/knem_md.c
  src/uct/sm/mm/base/mm_md.c
  src/uct/sm/self/self.c
  src/uct/tcp/sockcm/sockcm_md.c
  src/uct/tcp/tcp_md.c
  src/uct/ugni/base/ugni_md.c
  test/gtest/uct/test_md.cc
  test/gtest/uct/test_p2p_mix.cc
  test/gtest/uct/test_stats.cc
  test/gtest/uct/test_zcopy_comp.cc
  test/gtest/uct/uct_p2p_test.cc
Labels: API, Ready for Review, Waiting for Author Response

#3721 UCT/MD: uct_md_open() to not search component by md name
  src/uct/base/uct_md.c
Labels: Enhancement

#3719 Port fixes to v1.6.x: UCM events test, client/server example
  NEWS
  src/ucm/event/event.c
  src/ucm/mmap/install.c
  src/ucm/mmap/mmap.h
  test/examples/ucp_client_server.c
  test/gtest/ucm/malloc_hook.cc
Labels: Bugfix, Target: v1.6.x

#3715 CONFIG: Fixing broken configure logic
  configure.ac
  src/uct/ib/ud/base/ud_ep.h
  src/uct/ib/ud/base/ud_iface.h
  test/gtest/uct/ib/test_ud.cc
  test/gtest/uct/ib/test_ud_slow_timer.cc
Labels: Ready for Review

#3754 TEST/ASYNC: Add few retries to async event tests
  test/gtest/ucs/test_async.cc
Labels: Bugfix, Test

#3766 GTEST/UCS: Fix event_set tests instability
  test/gtest/ucs/test_event_set.cc
Labels: Bugfix

#3763 UCT/MD: Fix component name check in uct_rkey_unpack
  src/uct/base/uct_md.c
Labels: Bugfix
