Repository openucx/ucx, pull requests merged in 2019-02, with the labels that each got.

#3169 UCT/DC/MLX5: Set proper source port for FC over RoCE - v1.5.x
  src/ucp/core/ucp_worker.c
  src/uct/ib/dc/accel/dc_mlx5.c
  src/uct/ib/dc/base/dc_iface.c
  src/uct/ib/mlx5/ib_mlx5.h
  src/uct/ib/mlx5/ib_mlx5.inl
  src/uct/ib/mlx5/ib_mlx5_log.c
  src/uct/ib/mlx5/ib_mlx5_log.h
  src/uct/ib/ud/accel/ud_mlx5.c
  src/uct/ib/ud/accel/ud_mlx5_common.c
Labels: Bugfix, Critical v1.5.x

#3171 CONFIGURE: Update SO version from 0:0:0 to 1:0:1 - v1.5.x
  configure.ac
Labels: Critical v1.5.x

#3170 SPEC/README: Update the description of UCX in .spec and README files
  README
  ucx.spec.in
Labels: Critical v1.5.x, Documentation

#3177 UCP/API: Fix misprint in the doxygen
  PULL_REQUEST_TEMPLATE.md
  src/ucp/api/ucp.h
Labels: Cleanup, Documentation

#3175 EXAMPLES/UCT: Rename PD to MD as PD is deprecated name
  doc/doxygen/conventions.md
  doc/doxygen/design.md
  test/examples/uct_hello_world.c
Labels: Cleanup, Documentation, Ready for Review

#3172 UCT/RC/DC: Fix iface tx ops buffer overflow
  src/uct/ib/dc/dc_mlx5_ep.c
  src/uct/ib/rc/accel/rc_mlx5_ep.c
  src/uct/ib/rc/base/rc_ep.c
  src/uct/ib/rc/base/rc_ep.h
  src/uct/ib/rc/base/rc_iface.c
  src/uct/ib/rc/base/rc_iface.h
  src/uct/ib/rc/verbs/rc_verbs_ep.c
  test/gtest/common/test_helpers.h
  test/gtest/uct/ib/test_dc.cc
  test/gtest/uct/ib/test_rc.cc
  test/gtest/uct/ib/test_rc.h
Labels: Bugfix, Ready for Review

#3181 Topic/update ucx desc in spec and readme v1.5.x
  README
  ucx.spec.in
Labels: Critical v1.5.x, Documentation

#3189 TEST/TIME: Allow up to 1% time calculation discrepancy for nanoseconds
  test/gtest/ucs/test_time.cc
Labels: Bugfix

#3188 UCT/RC/DC: Fix iface tx ops buffer overflow - v1.5.x
  src/uct/ib/dc/accel/dc_mlx5.c
  src/uct/ib/dc/verbs/dc_verbs.c
  src/uct/ib/rc/accel/rc_mlx5_ep.c
  src/uct/ib/rc/base/rc_ep.c
  src/uct/ib/rc/base/rc_ep.h
  src/uct/ib/rc/base/rc_iface.c
  src/uct/ib/rc/base/rc_iface.h
  src/uct/ib/rc/verbs/rc_verbs_ep.c
  test/gtest/common/test_helpers.h
  test/gtest/uct/ib/test_dc.cc
  test/gtest/uct/ib/test_rc.cc
  test/gtest/uct/ib/test_rc.h
Labels: Bugfix, Ready for Review

#3195 NEWS: Add v1.5.0-rc3 with list of bugfixes
  NEWS
Labels: Documentation

#3185 UCS/MPOOL: Improve checks for user input values
  src/ucs/datastruct/mpool.c
  test/gtest/ucs/test_mpool.cc
Labels: Waiting for Author Response

#3206 NEWS: Removing duplicated line.
  NEWS
Labels: Documentation

#3203 TEST/ASYNC: Add retries to test_async.modify_event
  test/gtest/ucs/test_async.cc
Labels: Bugfix

#3115 UCT/API: make uct_ep_create backward compatible
  src/tools/perf/lib/libperf.c
  src/ucp/core/ucp_proxy_ep.c
  src/ucp/wireup/wireup.c
  src/ucp/wireup/wireup_ep.c
  src/uct/api/tl.h
  src/uct/api/uct.h
  src/uct/api/uct_def.h
  src/uct/base/uct_iface.c
  src/uct/base/uct_iface.h
  src/uct/cuda/cuda_copy/cuda_copy_ep.c
  src/uct/cuda/cuda_copy/cuda_copy_ep.h
  src/uct/cuda/cuda_copy/cuda_copy_iface.c
  src/uct/cuda/cuda_ipc/cuda_ipc_ep.c
  src/uct/cuda/cuda_ipc/cuda_ipc_ep.h
  src/uct/cuda/cuda_ipc/cuda_ipc_iface.c
  src/uct/cuda/gdr_copy/gdr_copy_ep.c
  src/uct/cuda/gdr_copy/gdr_copy_ep.h
  src/uct/cuda/gdr_copy/gdr_copy_iface.c
  src/uct/ib/cm/cm.h
  src/uct/ib/cm/cm_ep.c
  src/uct/ib/cm/cm_iface.c
  src/uct/ib/dc/dc_mlx5.c
  src/uct/ib/rc/accel/rc_mlx5.h
  src/uct/ib/rc/accel/rc_mlx5_ep.c
  src/uct/ib/rc/verbs/rc_verbs.h
  src/uct/ib/rc/verbs/rc_verbs_ep.c
  src/uct/ib/rdmacm/rdmacm_ep.c
  src/uct/ib/rdmacm/rdmacm_ep.h
  src/uct/ib/rdmacm/rdmacm_iface.c
  src/uct/ib/ud/accel/ud_mlx5.c
  src/uct/ib/ud/base/ud_ep.c
  src/uct/ib/ud/verbs/ud_verbs.c
  src/uct/ib/ud/verbs/ud_verbs.h
  src/uct/sm/cma/cma_ep.c
  src/uct/sm/cma/cma_ep.h
  src/uct/sm/cma/cma_iface.c
  src/uct/sm/knem/knem_ep.c
  src/uct/sm/knem/knem_ep.h
  src/uct/sm/knem/knem_iface.c
  src/uct/sm/mm/base/mm_ep.c
  src/uct/sm/mm/base/mm_ep.h
  src/uct/sm/mm/base/mm_iface.c
  src/uct/sm/self/self.c
  src/uct/tcp/tcp.h
  src/uct/tcp/tcp_ep.c
  src/uct/tcp/tcp_iface.c
  test/examples/uct_hello_world.c
  test/gtest/uct/ib/test_ud.cc
  test/gtest/uct/uct_test.cc
Labels: API, Enhancement, Ready for Review

#3137 UCT/API: make uct_iface_open backward compatible
  src/tools/info/tl_info.c
  src/tools/perf/lib/libperf.c
  src/ucp/core/ucp_listener.c
  src/ucp/core/ucp_worker.c
  src/ucp/core/ucp_worker.h
  src/uct/api/uct.h
  src/uct/base/uct_iface.c
  src/uct/base/uct_md.c
  src/uct/ib/base/ib_iface.c
  src/uct/ib/rc/accel/rc_mlx5_iface.c
  src/uct/ib/rdmacm/rdmacm_iface.c
  src/uct/ib/ud/base/ud_iface.c
  src/uct/sm/cma/cma_iface.c
  src/uct/sm/knem/knem_iface.c
  src/uct/sm/mm/base/mm_iface.c
  src/uct/sm/self/self.c
  src/uct/tcp/tcp_iface.c
  test/examples/uct_hello_world.c
  test/gtest/uct/ib/test_sockaddr.cc
  test/gtest/uct/test_peer_failure.cc
  test/gtest/uct/test_tag.cc
  test/gtest/uct/uct_test.cc
Labels: API, Enhancement, Ready for Review

#3209 UCS/DEBUG: Remove libiberty.h include
  config/m4/ucs.m4
  src/ucs/debug/debug.c
Labels: Bugfix

#3205 UCS/CMA: Check yama.ptrace_scope permissions
  config/m4/sysdep.m4
  src/ucs/sys/string.c
  src/ucs/sys/string.h
  src/ucs/sys/sys.c
  src/ucs/sys/sys.h
  src/uct/sm/cma/cma_md.c
  test/gtest/Makefile.am
  test/gtest/ucs/test_string.cc
Labels: Bugfix

#3208 TOOLS/UCM/UCT: Build CUDA as a separate loadable module
  config/m4/cuda.m4
  configure.ac
  contrib/buildrpm.sh
  src/tools/perf/Makefile.am
  src/tools/perf/configure.m4
  src/tools/perf/cuda/Makefile.am
  src/tools/perf/cuda/configure.m4
  src/tools/perf/cuda/cuda_alloc.c
  src/tools/perf/lib/Makefile.am
  src/tools/perf/lib/configure.m4
  src/tools/perf/lib/libperf.c
  src/tools/perf/lib/libperf_int.h
  src/ucm/Makefile.am
  src/ucm/configure.m4
  src/ucm/cuda/Makefile.am
  src/ucm/cuda/configure.m4
  src/ucm/event/event.c
  src/ucs/sys/module.c
  src/ucs/sys/module.h
  src/uct/Makefile.am
  src/uct/base/uct_md.c
  src/uct/configure.m4
  src/uct/cuda/Makefile.am
  src/uct/cuda/base/cuda_md.c
  src/uct/cuda/configure.m4
  src/uct/cuda/gdr_copy/Makefile.am
  src/uct/cuda/gdr_copy/configure.m4
  test/gtest/Makefile.am
  ucx.spec.in
Labels: Waiting for Author Response

#2697 UCP/API: Proposed API for Active Messages at the UCP level
  src/ucp/api/ucp.h
  src/ucp/api/ucp_def.h
  src/ucp/api/ucpx.h
Labels: API, Feature

#3253 New readme
  README
  doc/doxygen/api.svg
  doc/doxygen/release.svg
  doc/doxygen/twitter.svg
Labels: Documentation

#3247 UCP/RNDV: set 2 RNDV lanes by default
  src/ucp/core/ucp_context.c
  test/gtest/ucp/test_ucp_tag_offload.cc
  test/gtest/ucp/test_ucp_wireup.cc
Labels: Waiting for Author Response

#3262 UCS/ARBITER: Fix purge bug
  src/ucs/datastruct/arbiter.c
  test/gtest/ucs/test_arbiter.cc
Labels: Bugfix

#3227 UCT/ROCM: Build as a loadable module
  contrib/buildrpm.sh
  src/uct/Makefile.am
  src/uct/rocm/Makefile.am
  src/uct/rocm/configure.m4
  ucx.spec.in
Labels: Ready for Review

#3224 UCT/TCP/EP: Implement AM short send
  src/uct/tcp/tcp.h
  src/uct/tcp/tcp_ep.c
  src/uct/tcp/tcp_iface.c
Labels: Waiting for Author Response

#3226 Fence PCI atomics
  src/uct/ib/base/ib_device.h
  src/uct/ib/base/ib_md.c
  src/uct/ib/configure.m4
  src/uct/ib/dc/dc_mlx5.c
  src/uct/ib/dc/dc_mlx5_ep.c
  src/uct/ib/dc/dc_mlx5_ep.h
  src/uct/ib/mlx5/ib_mlx5.c
  src/uct/ib/mlx5/ib_mlx5.h
  src/uct/ib/mlx5/ib_mlx5_dv.c
  src/uct/ib/mlx5/ib_mlx5_ifc.h
  src/uct/ib/rc/accel/rc_mlx5.h
  src/uct/ib/rc/accel/rc_mlx5.inl
  src/uct/ib/rc/accel/rc_mlx5_common.c
  src/uct/ib/rc/accel/rc_mlx5_common.h
  src/uct/ib/rc/accel/rc_mlx5_ep.c
  src/uct/ib/rc/accel/rc_mlx5_iface.c
  src/uct/ib/rc/base/rc_iface.c
Labels: Waiting for Author Response

#3257 UCT/DC: Use arbiter group per dci for rand dci policy
  src/uct/ib/dc/dc_mlx5.c
  src/uct/ib/dc/dc_mlx5.h
  src/uct/ib/dc/dc_mlx5_ep.c
  src/uct/ib/dc/dc_mlx5_ep.h
  test/gtest/uct/ib/test_dc.cc
Labels: Ready for Review

#3269 UCT/UGNI: Build as loadable module
  contrib/buildrpm.sh
  src/uct/Makefile.am
  src/uct/ugni/Makefile.am
  src/uct/ugni/configure.m4
  ucx.spec.in
Labels: Ready for Review
