Repository openucx/ucx, pull requests merged in 2019-07, with the labels that each got.

#3793 UCT/IB/RC: Remove create_qp callback
  src/uct/ib/Makefile.am
  src/uct/ib/base/ib_iface.c
  src/uct/ib/base/ib_iface.h
  src/uct/ib/dc/dc_mlx5.c
  src/uct/ib/dc/dc_mlx5.h
  src/uct/ib/dc/dc_mlx5_ep.c
  src/uct/ib/mlx5/exp/ib_exp.c
  src/uct/ib/mlx5/exp/ib_exp.h
  src/uct/ib/mlx5/ib_mlx5.c
  src/uct/ib/mlx5/ib_mlx5.h
  src/uct/ib/mlx5/ib_mlx5.inl
  src/uct/ib/rc/accel/rc_mlx5.h
  src/uct/ib/rc/accel/rc_mlx5_ep.c
  src/uct/ib/rc/accel/rc_mlx5_iface.c
  src/uct/ib/rc/base/rc_iface.c
  src/uct/ib/rc/base/rc_iface.h
  src/uct/ib/rc/verbs/rc_verbs_ep.c
  src/uct/ib/rc/verbs/rc_verbs_iface.c
  src/uct/ib/ud/accel/ud_mlx5.c
  src/uct/ib/ud/base/ud_iface.c
  src/uct/ib/ud/base/ud_iface.h
  src/uct/ib/ud/verbs/ud_verbs.c
Labels: Waiting for Author Response

#3799 UCS, UCT, UCP, TOOLS: Fixed few csmock warnings
  src/tools/perf/perftest.c
  src/ucp/proto/proto_am.c
  src/ucp/wireup/wireup.c
  src/ucs/config/parser.c
  src/ucs/datastruct/mpmc.c
  src/ucs/datastruct/strided_alloc.c
  src/ucs/sys/sys.c
  src/ucs/type/class.c
  src/uct/ib/base/ib_md.c
  src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
  src/uct/ib/rdmacm/rdmacm_iface.c
  src/uct/ib/rdmacm/rdmacm_md.c
  src/uct/ib/ud/accel/ud_mlx5.c
  src/uct/ib/ud/base/ud_ep.c
  src/uct/ib/ud/verbs/ud_verbs.c
  src/uct/sm/mm/base/mm_md.c
  src/uct/tcp/sockcm/sockcm_md.c
  src/uct/tcp/tcp_ep.c
Labels: Waiting for Author Response

#3796 UCT/RC/DC: Resource check cleanups
  src/uct/ib/dc/dc_mlx5_ep.h
  src/uct/ib/rc/accel/rc_mlx5.h
  src/uct/ib/rc/accel/rc_mlx5_ep.c
  src/uct/ib/rc/base/rc_ep.c
  src/uct/ib/rc/base/rc_ep.h
Labels: Waiting for Author Response

#3768 STATS: Fixed crash on stat trigger "exit"
  src/ucs/stats/stats.c
Labels: Waiting for Author Response

#3777 JUCX: remove maven for clean step.
  bindings/java/src/main/native/Makefile.am
Labels: Waiting for Author Response

#3817 TEST/JENKINS: Don't run valgrind tests if JENKINS_NO_VALGRIND is set
  contrib/test_jenkins.sh
Labels: Test

#3829 UCT/RELOC: Fix patching dlopen() dependencies
  src/ucm/util/reloc.c
Labels: Bugfix

#3828 UCS/QUEUE: Fix cppcheck & clang warnings
  src/ucs/datastruct/queue.h
Labels: Waiting for Author Response

#3847 TEST/EXAMPLES: Fix socket operations - use MSG_WAITALL and print result
  test/examples/ucp_hello_world.c
  test/examples/uct_hello_world.c
  test/examples/ucx_hello_world.h
Labels: Test

#3723 UCT/API: A new client-server API in UCT with a connection manager.
  src/uct/api/tl.h
  src/uct/api/uct.h
  src/uct/api/uct_def.h
Labels: API

#3836 UCM: added madvise into VM_UNMAP events group
  src/ucm/event/event.h
  src/ucm/mmap/install.c
  test/gtest/ucm/malloc_hook.cc
Labels: Bugfix

#3858 TEST/IB: Skip non-default GID test if AH cannot be created
  test/gtest/uct/ib/test_ib.cc
Labels: Test

#3870 UCS/ASYNC: Don't spin when event_set return INPROGRESS
  src/ucs/async/thread.c
Labels: Bugfix

#3774 UCP/API : Moving ucp am api from ucpx.h
  src/ucp/api/ucp.h
  src/ucp/api/ucp_def.h
  src/ucp/api/ucpx.h
  src/ucp/core/ucp_am.c
  src/ucp/core/ucp_ep.h
  src/ucp/core/ucp_worker.c
  src/ucp/wireup/select.c
Labels: API, Waiting for Author Response

#3855 UCT/API: Update uct_ep_am_zcopy description
  src/uct/api/uct.h
Labels: API, Documentation

#3891 Porting test fixes from master to v1.6.x
  contrib/test_jenkins.sh
  contrib/valgrind.supp
  src/uct/tcp/tcp_net.c
  test/apps/test_ucx_tls.py
  test/examples/ucp_hello_world.c
  test/examples/uct_hello_world.c
  test/examples/ucx_hello_world.h
Labels: Target: v1.6.x

#3872 UCP/CONTEXT: added PPN runtime parameter
  src/tools/info/proto_info.c
  src/tools/info/ucx_info.c
  src/tools/info/ucx_info.h
  src/ucp/api/ucp.h
  src/ucp/core/ucp_context.c
  src/ucp/core/ucp_context.h
Labels: API

#3876 UCP/DOC: ucp_rkey_destroy() doc clarification
  src/ucp/api/ucp.h
Labels: API, Documentation

#3859 UCT/TCP: Send ACK along with WAIT_REQ if EP is waiting for ACK
  src/uct/tcp/tcp.h
  src/uct/tcp/tcp_cm.c
  src/uct/tcp/tcp_ep.c
Labels: Bugfix

#3834 UCT/GTEST/DC: Do not check for CQE res with DC
  src/uct/ib/dc/dc_mlx5.c
  src/uct/ib/dc/dc_mlx5.h
  src/uct/ib/dc/dc_mlx5_ep.c
  src/uct/ib/dc/dc_mlx5_ep.h
  src/uct/ib/rc/accel/rc_mlx5.inl
  src/uct/ib/rc/accel/rc_mlx5_iface.c
  src/uct/ib/rc/base/rc_iface.c
  src/uct/ib/rc/base/rc_iface.h
  src/uct/ib/rc/verbs/rc_verbs_iface.c
  test/gtest/uct/ib/test_dc.cc
  test/gtest/uct/ib/test_rc.cc
  test/gtest/uct/ib/test_rc.h
Labels: Ready for Review

#3936 GTEST/UCT/UD: Re-enable majority of UD tests
  test/gtest/uct/ib/test_ud.cc
Labels: Ready for Review

#3941 CI/AZP: Fixes for csmock issues found during AZP testing (backport) - v1.6
  src/tools/perf/lib/libperf.c
  src/tools/perf/perftest.c
  src/ucm/ptmalloc286/malloc.c
  src/ucp/wireup/address.c
  src/ucp/wireup/select.c
  src/ucs/datastruct/pgtable.c
  src/ucs/datastruct/ptr_array.c
  src/uct/ib/base/ib_log.c
  src/uct/ib/mlx5/ib_mlx5.c
  src/uct/ib/rc/base/rc_ep.c
  test/apps/sockaddr/sa_main.cc
Labels: Target: v1.6.x

#3942 UCS: Handle differences in the signal handling on Linux vs. FreeBSD.
  src/ucs/async/signal.c
  src/ucs/debug/debug.c
Labels: Waiting for Author Response

#3782 UCT/TCP: Enable AM Zcopy
  src/uct/tcp/tcp.h
  src/uct/tcp/tcp_ep.c
  src/uct/tcp/tcp_iface.c
Labels: Optimization

#3906 JENKINS: Improvements, run ucx_perftest with TCP and with sock rte launcher
  contrib/test_jenkins.sh
Labels: Waiting for Author Response

#3968 UCT: Introduce iface_attr::max_num_eps configurable parameter
  src/uct/api/uct.h
  src/uct/base/uct_iface.c
  src/uct/base/uct_iface.h
  src/uct/cuda/cuda_copy/cuda_copy_iface.c
  src/uct/cuda/cuda_ipc/cuda_ipc_iface.c
  src/uct/cuda/gdr_copy/gdr_copy_iface.c
  src/uct/ib/base/ib_iface.c
  src/uct/ib/rc/base/rc_iface.c
  src/uct/ib/rdmacm/rdmacm_iface.c
  src/uct/rocm/copy/rocm_copy_iface.c
  src/uct/rocm/gdr/rocm_gdr_iface.c
  src/uct/rocm/ipc/rocm_ipc_iface.c
  src/uct/sm/knem/knem_iface.c
  src/uct/sm/mm/base/mm_iface.c
  src/uct/sm/self/self.c
  src/uct/tcp/sockcm/sockcm_iface.c
  src/uct/tcp/tcp_iface.c
  src/uct/ugni/rdma/ugni_rdma_iface.c
  src/uct/ugni/smsg/ugni_smsg_iface.c
  src/uct/ugni/udt/ugni_udt_iface.c
Labels: API
