Repository openucx/ucx, pull requests merged in 2019-10, with the labels that each got.

#4254 GTEST/UCS: Fix prints in test_async
  test/gtest/ucs/test_async.cc
Labels: Cleanup

#4305 UCT/TCP: Close TCP socket when unable to send data
  src/uct/tcp/tcp_ep.c
Labels: Target: v1.7.x

#4290 MEM/TYPE-DETECT: use const pointer
  src/ucp/core/ucp_context.c
  src/ucp/core/ucp_context.h
  src/ucs/memory/memtype_cache.c
  src/ucs/memory/memtype_cache.h
  src/uct/api/uct.h
  src/uct/base/uct_md.c
  src/uct/base/uct_md.h
  src/uct/cuda/base/cuda_md.c
  src/uct/cuda/base/cuda_md.h
  src/uct/rocm/base/rocm_base.c
  src/uct/rocm/base/rocm_base.h
  src/uct/rocm/copy/rocm_copy_md.c
Labels: API

#4250 UCT/RCX: MP XRQ support
  src/uct/ib/base/ib_iface.h
  src/uct/ib/configure.m4
  src/uct/ib/dc/dc_mlx5.c
  src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
  src/uct/ib/mlx5/ib_mlx5.c
  src/uct/ib/mlx5/ib_mlx5.h
  src/uct/ib/mlx5/ib_mlx5.inl
  src/uct/ib/rc/accel/rc_mlx5.h
  src/uct/ib/rc/accel/rc_mlx5.inl
  src/uct/ib/rc/accel/rc_mlx5_common.c
  src/uct/ib/rc/accel/rc_mlx5_common.h
  src/uct/ib/rc/accel/rc_mlx5_devx.c
  src/uct/ib/rc/accel/rc_mlx5_ep.c
  src/uct/ib/rc/accel/rc_mlx5_iface.c
  test/gtest/uct/ib/test_rc.cc
  test/gtest/uct/test_tag.cc
Labels: Optimization

#4339 UCS/ASYNC: Support sync-removing a handler from its callback
  bindings/java/src/main/java/org/openucx/jucx/examples/UcxReadBWBenchmarkReceiver.java
  bindings/java/src/main/java/org/openucx/jucx/examples/UcxReadBWBenchmarkSender.java
  src/ucs/async/async.c
  src/ucs/async/async_fwd.h
  src/ucs/async/async_int.h
  test/gtest/ucs/test_async.cc
Labels: Bugfix

#4352 UCS/ASYNC/TEST: Fix sync handler remove
  src/ucs/async/async.c
  src/ucs/async/async_int.h
  test/gtest/ucs/test_async.cc
Labels: Bugfix
