Repository openucx/ucx, pull requests merged in 2019-01, with the labels that each got.

#3109 UCS/SYS: Better error handling of missing CAP_IPC_LOCK for HUGETLB
  config/m4/sysdep.m4
  src/ucs/sys/sys.c
Labels: Bugfix

#3110 SM/GDRCOPY/UGNI: configure.m4 cleanup
  src/uct/Makefile.am
  src/uct/cuda/gdr_copy/configure.m4
  src/uct/sm/knem/configure.m4
  src/uct/sm/mm/xpmem/configure.m4
  src/uct/ugni/configure.m4
Labels: Waiting for Author Response

#3105 UCP: Add header file for experimental APIs
  NEWS
  configure.ac
  contrib/test_jenkins.sh
  src/ucp/Makefile.am
  src/ucp/api/ucpx.h
Labels: API

#3116 UCP: fallback into single thread on single-thread build
  src/ucp/api/ucp.h
  src/ucp/core/ucp_worker.c
Labels: Bugfix, Documentation

#3106 UCT/IB: Move TM into accelerated transports
  src/tools/info/type_info.c
  src/uct/ib/base/ib_verbs.h
  src/uct/ib/configure.m4
  src/uct/ib/dc/dc_mlx5.c
  src/uct/ib/dc/dc_mlx5_ep.c
  src/uct/ib/rc/accel/rc_mlx5.h
  src/uct/ib/rc/accel/rc_mlx5.inl
  src/uct/ib/rc/accel/rc_mlx5_common.c
  src/uct/ib/rc/accel/rc_mlx5_common.h
  src/uct/ib/rc/accel/rc_mlx5_ep.c
  src/uct/ib/rc/accel/rc_mlx5_iface.c
  src/uct/ib/rc/base/rc_ep.c
  src/uct/ib/rc/base/rc_ep.h
  src/uct/ib/rc/base/rc_iface.c
  src/uct/ib/rc/base/rc_iface.h
  src/uct/ib/rc/verbs/rc_verbs_ep.c
  src/uct/ib/rc/verbs/rc_verbs_iface.c
  src/uct/ib/rc/verbs/rc_verbs_impl.h
  test/gtest/common/test_obj_size.cc
  test/gtest/uct/test_tag.cc
Labels: Waiting for Author Response

#3142 UCS: Add missing include to memtrack.c
  src/ucs/debug/memtrack.c
Labels: Bugfix

#3126 DOC: updated wording for ucp_worker_params::thread_mode value
  src/ucp/api/ucp.h
Labels: Documentation

#3114 CONTRIB: add --enable-examples to configure-devel
  contrib/configure-devel
  test/examples/ucp_client_server.c
  test/examples/ucp_hello_world.c
  test/examples/uct_hello_world.c
  test/examples/ucx_hello_world.h
Labels: Waiting for Author Response

#3153 UCS/TEST: Fix segfault in UCP, due to int truncation in count_one_bits() - v1.5.x
  src/ucp/core/ucp_mm.c
  src/ucp/core/ucp_mm.h
  src/ucp/core/ucp_request.c
  src/ucp/core/ucp_request.inl
  src/ucp/core/ucp_rkey.c
  src/ucp/tag/rndv.c
  src/ucp/wireup/address.c
  src/ucp/wireup/select.c
  src/ucp/wireup/wireup.c
  src/ucs/arch/bitops.h
  src/uct/sm/mm/mm_iface.c
  test/gtest/ucs/test_math.cc
Labels: Bugfix

#3157 PERFTEST: Fix memory types initialization
  src/tools/perf/perftest.c
Labels: Bugfix

#3159 Fix some English/spelling in ucp.h
  src/ucp/api/ucp.h
  src/uct/api/uct_def.h
Labels: Documentation

#3138 UCP: Reduce worker address for unified mode
  src/ucp/core/ucp_ep.c
  src/ucp/core/ucp_worker.c
  src/ucp/wireup/address.c
  src/ucp/wireup/address.h
  src/ucp/wireup/wireup.c
  src/ucp/wireup/wireup_ep.c
  test/gtest/ucp/test_ucp_wireup.cc
Labels: Enhancement, Ready for Review

#3140 RC/UD: add support for max_inline==0
  src/uct/ib/base/ib_iface.h
  src/uct/ib/rc/base/rc_iface.c
  src/uct/ib/rc/verbs/rc_verbs.h
  src/uct/ib/rc/verbs/rc_verbs_ep.c
  src/uct/ib/rc/verbs/rc_verbs_iface.c
  src/uct/ib/ud/base/ud_ep.c
  src/uct/ib/ud/base/ud_iface.c
  src/uct/ib/ud/verbs/ud_verbs.c
Labels: Waiting for Author Response

#3095 UCT/IB/MLX5: DEVX KSM
  src/uct/ib/base/ib_device.c
  src/uct/ib/base/ib_md.c
  src/uct/ib/base/ib_md.h
  src/uct/ib/mlx5/ib_mlx5.h
  src/uct/ib/mlx5/ib_mlx5_dv.c
  src/uct/ib/mlx5/ib_mlx5_ifc.h
  test/gtest/uct/ib/test_ib_md.cc
Labels: Waiting for Author Response

#3163 UCT/DC/MLX5: Set proper source port for FC over RoCE
  src/ucp/core/ucp_worker.c
  src/uct/ib/dc/dc_mlx5.c
  src/uct/ib/dc/dc_mlx5.h
  src/uct/ib/dc/dc_mlx5_ep.c
  src/uct/ib/mlx5/ib_mlx5.h
  src/uct/ib/mlx5/ib_mlx5.inl
  src/uct/ib/mlx5/ib_mlx5_log.c
  src/uct/ib/mlx5/ib_mlx5_log.h
  src/uct/ib/ud/accel/ud_mlx5.c
  src/uct/ib/ud/accel/ud_mlx5_common.c
Labels: Bugfix, Critical v1.5.x

#3164 UCT/DC: Implement random dci allocation policy
  src/uct/ib/dc/dc_mlx5.c
  src/uct/ib/dc/dc_mlx5.h
  src/uct/ib/dc/dc_mlx5_ep.c
  src/uct/ib/dc/dc_mlx5_ep.h
  test/gtest/ucp/test_ucp_sockaddr.cc
  test/gtest/uct/ib/test_dc.cc
Labels: Feature, Ready for Review
