Repository openucx/ucx, pull requests merged in 2019-08, with the labels that each got.

#3991 UCT/MM: Fix redundant stringification in component name
  src/uct/sm/mm/base/mm_md.h
Labels: Bugfix

#3985 UCT/API/COMPONENT: add capabilities flags to attrs
  src/uct/api/uct.h
  src/uct/base/uct_component.c
  src/uct/base/uct_component.h
  src/uct/cuda/cuda_copy/cuda_copy_md.c
  src/uct/cuda/cuda_ipc/cuda_ipc_md.c
  src/uct/cuda/gdr_copy/gdr_copy_md.c
  src/uct/ib/base/ib_md.c
  src/uct/ib/rdmacm/rdmacm_md.c
  src/uct/rocm/copy/rocm_copy_md.c
  src/uct/rocm/gdr/rocm_gdr_md.c
  src/uct/rocm/ipc/rocm_ipc_md.c
  src/uct/sm/cma/cma_md.c
  src/uct/sm/knem/knem_md.c
  src/uct/sm/mm/base/mm_md.h
  src/uct/sm/self/self.c
  src/uct/tcp/sockcm/sockcm_md.c
  src/uct/tcp/tcp_md.c
  src/uct/ugni/base/ugni_md.c
  test/gtest/uct/uct_test.cc
Labels: API

#3943 UCT/IB/DC: Upstream DC TM
  configure.ac
  src/uct/ib/Makefile.am
  src/uct/ib/base/ib_iface.h
  src/uct/ib/base/ib_verbs.h
  src/uct/ib/configure.m4
  src/uct/ib/dc/dc_mlx5.c
  src/uct/ib/dc/dc_mlx5.h
  src/uct/ib/dc/dc_mlx5_devx.c
  src/uct/ib/dc/dc_mlx5_ep.c
  src/uct/ib/dc/dc_mlx5_ep.h
  src/uct/ib/mlx5/dv/ib_mlx5_dv.c
  src/uct/ib/mlx5/dv/ib_mlx5_ifc.h
  src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
  src/uct/ib/mlx5/exp/ib_exp_md.c
  src/uct/ib/mlx5/ib_mlx5.c
  src/uct/ib/mlx5/ib_mlx5.h
  src/uct/ib/rc/accel/rc_mlx5_common.c
  src/uct/ib/rc/accel/rc_mlx5_common.h
  src/uct/ib/rc/accel/rc_mlx5_devx.c
  src/uct/ib/rc/accel/rc_mlx5_iface.c
  src/uct/ib/rc/base/rc_iface.c
Labels: Waiting for Author Response

#4004 API/UCT/GTEST: Added uct_listener_query() to query the listening port.
  src/uct/api/uct.h
  src/uct/api/uct_def.h
  src/uct/base/uct_cm.c
  src/uct/base/uct_cm.h
  src/uct/ib/rdmacm/rdmacm_cm.c
  src/uct/ib/rdmacm/rdmacm_listener.c
  src/uct/ib/rdmacm/rdmacm_listener.h
  test/gtest/uct/ib/test_sockaddr.cc
  test/gtest/uct/uct_test.cc
  test/gtest/uct/uct_test.h
Labels: API

#3889 UCS: added system CPU cache size processing
  src/ucs/Makefile.am
  src/ucs/arch/aarch64/cpu.h
  src/ucs/arch/cpu.c
  src/ucs/arch/cpu.h
  src/ucs/arch/ppc64/cpu.h
  src/ucs/arch/x86_64/cpu.c
  src/ucs/arch/x86_64/cpu.h
  src/ucs/sys/compiler_def.h
  src/ucs/sys/sys.c
  src/ucs/sys/sys.h
  test/gtest/ucs/test_sys.cc
Labels: Waiting for Author Response

#4046 UCT/API: enhance doc for the uct_listener functions.
  src/uct/api/uct.h
  src/uct/api/uct_def.h
Labels: Documentation

#4043 GTEST: added client-server over CM stress tests.
  test/gtest/uct/ib/test_sockaddr.cc
Labels: Test

#4000 malloc() use portability fixes.
  src/tools/perf/lib/libperf.c
  src/ucm/malloc/malloc_hook.c
  src/ucm/mmap/install.c
  src/ucm/util/replace.c
  src/ucp/dt/dt_generic.c
  src/ucs/datastruct/ptr_array.c
  src/ucs/debug/memtrack.c
  src/ucs/debug/memtrack.h
  src/ucs/memory/memtype_cache.c
  src/ucs/memory/rcache.c
  src/uct/base/uct_md.c
  src/uct/base/uct_mem.c
  src/uct/cuda/cuda_ipc/cuda_ipc_cache.c
  src/uct/ib/mlx5/dv/ib_mlx5_dv.c
  src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
  src/uct/rocm/ipc/rocm_ipc_cache.c
  test/gtest/ucs/test_memtrack.cc
Labels: Waiting for Author Response

#4080 GTEST: update the sockaddr to connect to if the listener's port changed
  test/gtest/uct/ib/test_sockaddr.cc
Labels: Test

#4026 UCP/LISTENER: add CMs initialization and destroy
  src/ucp/core/ucp_listener.c
  src/ucp/core/ucp_listener.h
  src/ucp/core/ucp_types.h
  src/ucp/core/ucp_worker.c
  src/ucp/core/ucp_worker.h
  test/gtest/ucp/test_ucp_sockaddr.cc
Labels: Waiting for Author Response

#4109 UCT: backport fixes from master (1.6.x)
  src/uct/base/uct_worker.h
  src/uct/ib/mlx5/ib_mlx5.c
Labels: Target: v1.6.x

#4097 GTEST: add sockaddr over cm tests where the server's response is delayed
  test/gtest/uct/ib/test_sockaddr.cc
Labels: Test

#4111 UCP: Fix unified mode
  src/ucp/wireup/address.c
Labels: Bugfix
