Repository openucx/ucx, pull requests merged in 2019-11, with the labels that each got.

#4364 TEST/ASYNC: Add retries to test_async.ctx_event_block
  test/gtest/ucs/test_async.cc
Labels: Bugfix

#4380 UCT/IB, UCS/CONFIG: Make default PKEY - auto, improve PKEY search time
  src/ucs/config/parser.c
  src/ucs/sys/string.h
  src/uct/ib/base/ib_iface.c
  test/gtest/uct/ib/test_ib_pkey.cc
Labels: Target: v1.7.x

#4408 UCS/ARCH: Use built-in memcpy for 1Kb..136Kb on AMD
  src/ucs/arch/cpu.c
  src/ucs/arch/cpu.h
  src/ucs/arch/x86_64/cpu.c
Labels: Enhancement

#4355 Handle cpusets and affinity portability issues.
  config/m4/sysdep.m4
  src/tools/perf/perftest.c
  src/ucs/config/types.h
  src/ucs/sys/sys.c
  src/ucs/sys/sys.h
  src/uct/api/uct.h
  src/uct/ib/base/ib_device.c
  src/uct/ib/base/ib_device.h
  src/uct/ib/base/ib_iface.c
  src/uct/ib/base/ib_md.c
  src/uct/ugni/base/ugni_types.h
  test/gtest/uct/test_uct_perf.cc
  test/gtest/uct/uct_test.cc
  test/gtest/uct/uct_test.h
Labels: API, Ready for Review

#4438 GTEST/UCS: Enable sockaddr testing with an IPv6 address - v1.7.x
  bindings/java/src/main/java/org/openucx/jucx/examples/UcxReadBWBenchmarkReceiver.java
  bindings/java/src/main/java/org/openucx/jucx/examples/UcxReadBWBenchmarkSender.java
  src/ucs/async/async.c
  src/ucs/async/async_fwd.h
  src/ucs/async/async_int.h
  src/ucs/sys/sock.c
  src/ucs/sys/sock.h
  src/uct/tcp/sockcm/sockcm_ep.c
  src/uct/tcp/sockcm/sockcm_iface.c
  test/gtest/common/test_helpers.cc
  test/gtest/common/test_helpers.h
  test/gtest/ucp/test_ucp_sockaddr.cc
  test/gtest/ucs/test_async.cc
  test/gtest/uct/ib/test_sockaddr.cc
  test/gtest/uct/test_md.cc
  test/gtest/uct/uct_test.cc
Labels: Target: v1.7.x

#4463 UCT/TCP, UCS/SYS: Repeat connection establishment when detected dropped connections
  src/ucs/sys/sock.c
  src/ucs/sys/sock.h
  src/uct/tcp/tcp.h
  src/uct/tcp/tcp_cm.c
  src/uct/tcp/tcp_ep.c
  src/uct/tcp/tcp_iface.c
  test/gtest/common/test_obj_size.cc
Labels: Target: v1.7.x
