Repository openucx/ucx, pull requests merged in 2019-12, with the labels that each got.

#4539 UCT/XPMEM: Fix build on ppc64le
  src/uct/sm/mm/xpmem/mm_xpmem.c
Labels: Bugfix

#4507 UCT/API: Add configuration to CM
  src/ucp/core/ucp_worker.c
  src/ucs/config/parser.c
  src/ucs/config/parser.h
  src/uct/api/uct.h
  src/uct/api/uct_def.h
  src/uct/base/uct_cm.c
  src/uct/base/uct_cm.h
  src/uct/base/uct_component.c
  src/uct/base/uct_component.h
  src/uct/base/uct_md.c
  src/uct/base/uct_md.h
  src/uct/cuda/cuda_copy/cuda_copy_md.c
  src/uct/cuda/cuda_ipc/cuda_ipc_md.c
  src/uct/cuda/gdr_copy/gdr_copy_md.c
  src/uct/ib/base/ib_md.c
  src/uct/ib/rdmacm/rdmacm_cm.c
  src/uct/ib/rdmacm/rdmacm_cm.h
  src/uct/ib/rdmacm/rdmacm_md.c
  src/uct/rocm/copy/rocm_copy_md.c
  src/uct/rocm/gdr/rocm_gdr_md.c
  src/uct/rocm/ipc/rocm_ipc_md.c
  src/uct/sm/cma/cma_md.c
  src/uct/sm/knem/knem_md.c
  src/uct/sm/mm/base/mm_md.h
  src/uct/sm/self/self.c
  src/uct/tcp/sockcm/sockcm_md.c
  src/uct/tcp/tcp_md.c
  src/uct/ugni/base/ugni_md.c
  test/gtest/uct/ib/test_sockaddr.cc
  test/gtest/uct/uct_test.cc
Labels: API

#4572 UCP/UCS: Use a lower Bcopy BW value for more optimal RNDV threshold on AMD
  src/ucp/core/ucp_context.c
  src/ucp/core/ucp_context.h
  src/ucs/arch/cpu.c
  src/ucs/arch/cpu.h
Labels: Optimization

#4445 UCP/EP: sockaddr CM close protocol
  src/ucp/core/ucp_ep.c
  src/ucp/core/ucp_ep.h
  src/ucp/core/ucp_ep.inl
  src/ucp/core/ucp_types.h
  src/ucp/core/ucp_worker.c
  src/ucp/wireup/wireup_cm.c
  src/ucp/wireup/wireup_cm.h
  src/uct/ib/rdmacm/rdmacm_cm.c
  test/gtest/ucp/test_ucp_sockaddr.cc
Labels: Ready for Review

#4601 DOCS: Add basic read-the-docs support
  .gitignore
  docs/Makefile
  docs/source/_static/UCX_Layers.png
  docs/source/_static/ucxlogo.png
  docs/source/conf.py
  docs/source/index.rst
  docs/source/running.md
Labels: Documentation

#4574 UCT/API: Add refs in the uct_cm_open doc.
  src/uct/api/uct.h
Labels: API, Documentation

#4604 DOCS/RTD: Add download and FAQ pages
  docs/source/download.md
  docs/source/faq.md
  docs/source/index.rst
Labels: Documentation
