Repository openucx/ucx, pull requests merged in 2019-05, with the labels that each got.

#3426 UCS/API event_set
  src/ucs/Makefile.am
  src/ucs/sys/event_set.c
  src/ucs/sys/event_set.h
  test/gtest/Makefile.am
  test/gtest/ucs/test_event_set.cc
Labels: Portability, Ready for Review

#3537 API/UCP/UCT/TEST: Added a function to retrieve the listening port.
  src/ucp/api/ucp.h
  src/ucp/api/ucp_def.h
  src/ucp/core/ucp_listener.c
  src/uct/api/uct.h
  src/uct/ib/rdmacm/rdmacm_iface.c
  test/examples/ucp_client_server.c
  test/gtest/ucp/test_ucp_sockaddr.cc
  test/gtest/ucp/ucp_test.cc
  test/gtest/ucp/ucp_test.h
Labels: API, Feature

#3449 UCT/sockcm: Socket-based connection management skeleton
  src/ucp/core/ucp_context.c
  src/uct/Makefile.am
  src/uct/tcp/sockcm/sockcm_def.h
  src/uct/tcp/sockcm/sockcm_ep.c
  src/uct/tcp/sockcm/sockcm_ep.h
  src/uct/tcp/sockcm/sockcm_iface.c
  src/uct/tcp/sockcm/sockcm_iface.h
  src/uct/tcp/sockcm/sockcm_md.c
  src/uct/tcp/sockcm/sockcm_md.h
Labels: Waiting for Author Response

#3548 UCP/AM: Fixing Compilation issue on Fedora system.
  src/ucp/core/ucp_am.c
  src/ucp/core/ucp_am.h
Labels: Waiting for Author Response

#3511 UCP/EP: Print ep lane transports with INFO log level
  src/ucp/core/ucp_ep.c
  src/ucp/core/ucp_worker.c
  src/ucp/core/ucp_worker.h
  src/ucp/wireup/wireup.c
Labels: Enhancement, Ready for Review

#3576 CONFIGURE: Add support for --enable-devel-headers
  configure.ac
Labels: Waiting for Author Response

#3567 JUCX: get non blocking operation.
  bindings/java/src/main/java/org/ucx/jucx/UcxCallback.java
  bindings/java/src/main/java/org/ucx/jucx/UcxRequest.java
  bindings/java/src/main/java/org/ucx/jucx/ucp/UcpEndpoint.java
  bindings/java/src/main/native/endpoint.cc
  bindings/java/src/main/native/jucx_common_def.cc
  bindings/java/src/main/native/jucx_common_def.h
  bindings/java/src/test/java/org/ucx/jucx/UcpEndpointTest.java
  bindings/java/src/test/java/org/ucx/jucx/UcpMemoryTest.java
Labels: Waiting for Author Response

#3623 TEST/EXAMPLES: use htons on server_port - v1.6.x
  test/examples/ucp_client_server.c
Labels: Target: v1.6.x

#3614 UCT/IB: Don't fail if no devices are found; return an empty list
  src/uct/ib/base/ib_md.c
Labels: Bugfix

#3598 UCS/CONFIG: Add infra for deprecated env vars
  src/tools/perf/api/libperf.h
  src/ucp/rma/amo_send.c
  src/ucp/rma/rma_send.c
  src/ucp/wireup/wireup_ep.c
  src/ucs/Makefile.am
  src/ucs/async/async.c
  src/ucs/async/thread.c
  src/ucs/config/parser.c
  src/ucs/config/parser.h
  src/ucs/sys/compiler_def.h
  src/ucs/sys/stubs.c
  src/ucs/sys/stubs.h
  src/ucs/sys/sys.c
  src/ucs/sys/sys.h
  src/uct/base/uct_iface.c
  test/gtest/common/test_perf.cc
  test/gtest/ucs/test_config.cc
Labels: Waiting for Author Response

#3554 GTEST/UCP: Adjust the number of iterations when running under valgrind
  test/gtest/ucp/test_ucp_memheap.cc
  test/gtest/ucp/test_ucp_mmap.cc
  test/gtest/ucp/test_ucp_peer_failure.cc
  test/gtest/ucp/test_ucp_rma.cc
  test/gtest/ucp/test_ucp_stream.cc
  test/gtest/ucp/test_ucp_tag_match.cc
  test/gtest/ucp/test_ucp_tag_offload.cc
  test/gtest/ucp/test_ucp_tag_xfer.cc
  test/gtest/ucp/test_ucp_wireup.cc
  test/gtest/uct/test_md.cc
  test/gtest/uct/test_p2p_am.cc
  test/gtest/uct/test_p2p_err.cc
  test/gtest/uct/test_pending.cc
  test/gtest/uct/uct_p2p_test.cc
Labels: Waiting for Author Response

#3632 SPEC: Remove ucx-static package since it's unusable - v1.6.x
  ucx.spec.in
Labels: Target: v1.6.x

#3625 NEWS: Getting news ready for v1.6.x
  NEWS
Labels: Documentation, Ready for Review

#3524 UCT: replace MAX_BCOPY by SEG_SIZE attribute
  src/ucp/core/ucp_context.c
  src/uct/base/uct_iface.c
  src/uct/base/uct_iface.h
  src/uct/ib/base/ib_iface.c
  src/uct/ib/base/ib_iface.h
  src/uct/ib/cm/cm_iface.c
  src/uct/ib/rc/accel/rc_mlx5_common.c
  src/uct/ib/rc/accel/rc_mlx5_common.h
  src/uct/ib/rc/accel/rc_mlx5_iface.c
  src/uct/ib/rc/verbs/rc_verbs_iface.c
  src/uct/ib/ud/base/ud_iface.c
  src/uct/sm/mm/base/mm_iface.c
  src/uct/sm/mm/base/mm_iface.h
  src/uct/sm/self/self.c
  src/uct/sm/self/self.h
  src/uct/tcp/tcp.h
  src/uct/tcp/tcp_ep.c
  src/uct/tcp/tcp_iface.c
  test/gtest/ucp/test_ucp_peer_failure.cc
  test/gtest/ucp/test_ucp_tag_match.cc
  test/gtest/ucp/test_ucp_tag_xfer.cc
  test/gtest/uct/test_many2one_am.cc
  test/gtest/uct/uct_test.cc
  test/gtest/uct/uct_test.h
Labels: Waiting for Author Response

#3628 JUCX: PUT/SEND/RECV non-blocking operations.
  bindings/java/src/main/java/org/ucx/jucx/ucp/UcpEndpoint.java
  bindings/java/src/main/java/org/ucx/jucx/ucp/UcpWorker.java
  bindings/java/src/main/native/endpoint.cc
  bindings/java/src/main/native/jucx_common_def.cc
  bindings/java/src/main/native/jucx_common_def.h
  bindings/java/src/main/native/org_ucx_jucx_ucp_UcpConstants.h
  bindings/java/src/main/native/org_ucx_jucx_ucp_UcpContext.h
  bindings/java/src/main/native/org_ucx_jucx_ucp_UcpEndpoint.h
  bindings/java/src/main/native/org_ucx_jucx_ucp_UcpListener.h
  bindings/java/src/main/native/org_ucx_jucx_ucp_UcpMemory.h
  bindings/java/src/main/native/org_ucx_jucx_ucp_UcpRemoteKey.h
  bindings/java/src/main/native/org_ucx_jucx_ucp_UcpWorker.h
  bindings/java/src/main/native/org_ucx_jucx_ucs_UcsConstants.h
  bindings/java/src/main/native/org_ucx_jucx_ucs_UcsConstants_ThreadMode.h
  bindings/java/src/main/native/worker.cc
  bindings/java/src/test/java/org/ucx/jucx/UcpEndpointTest.java
Labels: Waiting for Author Response
