Repository openucx/ucx, pull requests merged in 2019-04, with the labels that each got.

#3434 DOC/CODESTYLE Add code style example
  doc/CodeStyle.md
Labels: Documentation

#3437 UCM: Avoid releasing environment strings in library destructor
  src/ucm/malloc/malloc_hook.c
Labels: Bugfix

#3443 RC/FC: fixed potential deadlock
  src/uct/api/uct.h
  src/uct/base/uct_iface.h
  src/uct/ib/rc/base/rc_ep.c
  src/uct/ib/rc/base/rc_iface.c
Labels: Bugfix

#3321 DOC/INSTALL: Update OpenMPI build instructions
  INSTALL
  README
Labels: Documentation, Waiting for Author Response

#3325 UCT/API: Add API for querying component list and attributes
  src/uct/api/uct.h
  src/uct/api/uct_def.h
Labels: API

#3482 UCM/TEST: Fix handling of shmat(SHM_REMAP|SHM_RND) - v1.6.x
  src/ucm/event/event.c
  test/gtest/ucm/malloc_hook.cc
Labels: Bugfix

#3488 SPEC: Remove CUDA BuildRequires, since package name is not consistent - v1.6.x
  ucx.spec.in
Labels: Enhancement

#3491 UCM: Link with --no-as-needed, to find all symbols at runtime
  src/ucm/configure.m4
Labels: Bugfix

#2723 UCP/API/EP/Request/worker/select Implementation of Active Messages at…
  AUTHORS
  src/ucp/Makefile.am
  src/ucp/core/ucp_am.c
  src/ucp/core/ucp_am.h
  src/ucp/core/ucp_am.inl
  src/ucp/core/ucp_ep.c
  src/ucp/core/ucp_ep.h
  src/ucp/core/ucp_request.c
  src/ucp/core/ucp_request.h
  src/ucp/core/ucp_types.h
  src/ucp/core/ucp_worker.c
  src/ucp/core/ucp_worker.h
  src/ucp/stream/stream_recv.c
  src/ucp/stream/stream_send.c
  src/ucp/tag/eager.h
  src/ucp/tag/eager_snd.c
  src/ucp/tag/tag_match.c
  src/ucp/tag/tag_match.h
  src/ucp/tag/tag_recv.c
  src/ucp/tag/tag_send.c
  src/ucp/wireup/select.c
Labels: Feature, Ready for Review

#3490 UCM: Search for symbols in .got, in additon to .got.plt
  src/ucm/malloc/malloc_hook.c
  src/ucm/util/reloc.c
  test/gtest/ucm/malloc_hook.cc
Labels: Bugfix

#3476 UCT/DC: Fix possible OOO in iface flush
  src/uct/ib/dc/dc_mlx5.c
  src/uct/ib/dc/dc_mlx5.h
  src/uct/ib/dc/dc_mlx5_ep.c
  src/uct/ib/dc/dc_mlx5_ep.h
Labels: Ready for Review
