Repository openucx/ucx, pull requests merged in 2019-03, with the labels that each got.

#3273 UCP&UCT: add ROCM memory type
  src/ucm/api/ucm.h
  src/ucp/core/ucp_context.c
  src/ucp/core/ucp_context.h
  src/uct/api/uct.h
  test/gtest/uct/test_md.cc
Labels: API

#3283 CONFIG: Fail if --with-docs-only specified, but required tools can't be found
  configure.ac
  contrib/test_jenkins.sh
Labels: Target: v1.6.x, Waiting for Author Response

#3302 DOC: Small doc. fix in UCP
  src/ucp/api/ucp.h
Labels: API

#3320 UCS/UCM: Avoid linking UCM loadable modules with "nodelete" flag
  contrib/test_jenkins.sh
  src/tools/perf/lib/libperf.c
  src/ucm/configure.m4
  src/ucm/event/event.c
  src/ucs/sys/module.c
  src/ucs/sys/module.h
  src/uct/base/uct_md.c
  src/uct/cuda/base/cuda_md.c
  src/uct/ib/base/ib_md.c
  test/apps/Makefile.am
  test/apps/test_link_map.c
  test/gtest/ucs/test_sys.cc
Labels: Bugfix

#3334 UCT/TM: Fix tag-matching initialization
  src/uct/ib/rc/base/rc_iface.c
  src/uct/ib/rc/verbs/rc_verbs_iface.c
Labels: Bugfix

#3301 UCT/IB/MLX5: Fasten DC support check
  src/uct/ib/mlx5/ib_mlx5_dv.c
Labels: Waiting for Author Response

#3345 UCT/ROCM: remove cma TL
  src/uct/rocm/Makefile.am
  src/uct/rocm/cma/rocm_cma_ep.c
  src/uct/rocm/cma/rocm_cma_ep.h
  src/uct/rocm/cma/rocm_cma_iface.c
  src/uct/rocm/cma/rocm_cma_iface.h
  src/uct/rocm/cma/rocm_cma_md.c
  src/uct/rocm/cma/rocm_cma_md.h
  src/uct/rocm/cma/rocm_common.c
  src/uct/rocm/cma/rocm_common.h
  test/gtest/uct/test_md.cc
  test/gtest/uct/uct_test.h
Labels: Cleanup

#3344 UCT/IB: enable ROCM direct rdma
  src/uct/ib/base/ib_md.c
  test/gtest/uct/test_md.cc
Labels: Waiting for Author Response

#3323 JENKINS: Add cray-ugni build test
  contrib/cray-ugni-mock/cray-pmi.pc
  contrib/cray-ugni-mock/cray-ugni.pc
  contrib/cray-ugni-mock/include/gni_pub.h
  contrib/cray-ugni-mock/include/pmi.h
  contrib/cray-ugni-mock/include/pmi2.h
  contrib/test_jenkins.sh
  src/uct/ugni/base/ugni_ep.c
  src/uct/ugni/smsg/ugni_smsg_ep.c
Labels: Ready for Review

#3288 UCT/IB: Move res_domain to accelerated TLs
  src/uct/ib/base/ib_iface.c
  src/uct/ib/base/ib_iface.h
  src/uct/ib/cm/cm_iface.c
  src/uct/ib/dc/dc_mlx5.c
  src/uct/ib/mlx5/ib_mlx5.c
  src/uct/ib/mlx5/ib_mlx5.h
  src/uct/ib/mlx5/ib_mlx5.inl
  src/uct/ib/rc/accel/rc_mlx5_common.c
  src/uct/ib/rc/accel/rc_mlx5_common.h
  src/uct/ib/rc/accel/rc_mlx5_iface.c
  src/uct/ib/rc/verbs/rc_verbs_iface.c
  src/uct/ib/ud/accel/ud_mlx5.c
  src/uct/ib/ud/accel/ud_mlx5.h
  src/uct/ib/ud/verbs/ud_verbs.c
Labels: Waiting for Author Response

#3338 UCM/HOOKS: added ucm_test_events routine to check if hooks works properly
  src/ucm/api/ucm.h
  src/ucm/event/event.c
  src/ucm/mmap/install.c
  src/ucm/mmap/mmap.h
  test/gtest/ucm/malloc_hook.cc
Labels: Waiting for Author Response

#3377 GTEST/UCP: Adjust tag offload test to multirail
  test/gtest/ucp/test_ucp_tag_offload.cc
Labels: Ready for Review, Test

#3350 TOOLS/PERF: Fix ucx_perftest's multi-threaded mode
  src/tools/perf/lib/libperf.c
  src/tools/perf/lib/libperf_int.h
  src/tools/perf/lib/ucp_tests.cc
  src/tools/perf/perftest.c
Labels: Bugfix, Waiting for Author Response

#3387 UCT/TCP: Add support for messages with the length > 64k
  src/uct/tcp/tcp.h
  test/gtest/uct/test_p2p_am.cc
Labels: Waiting for Author Response

#3384 UCT/TCP: Add cfg option for socket RCV buffer
  src/tools/perf/perftest.c
  src/ucs/sys/sock.c
  src/ucs/sys/sock.h
  src/uct/tcp/tcp.h
  src/uct/tcp/tcp_iface.c
  test/gtest/ucs/test_sock.cc
Labels: Waiting for Author Response

#3410 UCM: Set NODELETE flag at runtime instead of link time
  src/ucm/Makefile.am
  src/ucm/event/event.c
  src/ucm/util/sys.c
  src/ucm/util/sys.h
Labels: Bugfix

#3332 UCT/IB/RC: Fence PCI atomics on verbs RC
  src/uct/ib/base/ib_device.h
  src/uct/ib/base/ib_iface.h
  src/uct/ib/dc/dc_mlx5.c
  src/uct/ib/dc/dc_mlx5_ep.c
  src/uct/ib/mlx5/ib_mlx5.c
  src/uct/ib/mlx5/ib_mlx5.h
  src/uct/ib/rc/accel/rc_mlx5.inl
  src/uct/ib/rc/accel/rc_mlx5_common.c
  src/uct/ib/rc/accel/rc_mlx5_common.h
  src/uct/ib/rc/accel/rc_mlx5_ep.c
  src/uct/ib/rc/accel/rc_mlx5_iface.c
  src/uct/ib/rc/base/rc_ep.h
  src/uct/ib/rc/base/rc_iface.c
  src/uct/ib/rc/base/rc_iface.h
  src/uct/ib/rc/verbs/rc_verbs.h
  src/uct/ib/rc/verbs/rc_verbs_ep.c
  src/uct/ib/rc/verbs/rc_verbs_iface.c
Labels: Waiting for Author Response

#3411 BUILD: Bump version to v1.5.1 - v1.5.x
  configure.ac
  ucx.spec.in
Labels: Documentation

#3412 UCP/RNDV: Fix pipelined rndv condition checks
  src/ucp/tag/rndv.c
Labels: Bugfix

#3415 UCS/DEBUG: Add ability to read env for TMPDIR
  src/ucs/debug/debug.c
  src/ucs/sys/sys.c
  src/ucs/sys/sys.h
Labels: Enhancement

#3419 UCT/DC: Remove needless checks from iface flush
  src/uct/ib/dc/dc_mlx5.c
Labels: Enhancement, Ready for Review
