Repository openucx/ucx, pull requests merged in 2020-03, with the labels that each got.

#4843 TEST/ASYNC: Drain pipe before test - v1.8.x
  test/gtest/ucs/test_async.cc
Labels: Target: v1.8.0

#4835 UCT/TCP: Add knob to disable PUT Zcopy by default, fix scalability issue - v1.8.x
  src/uct/tcp/tcp.h
  src/uct/tcp/tcp_iface.c
Labels: Target: v1.8.0

#4845 UCP/TYPO: fixed typos in UCP_STREAM_RECV_FLAG_WAITALL description
  src/ucp/api/ucp.h
Labels: Documentation

#4850 UCP/DOC: Multiple fixes in UCP iov doc
  src/ucp/dt/dt_iov.h
Labels: Documentation

#4833 NEWS update for v1.8.0-rc1
  NEWS
Labels: Target: v1.8.0

#4837 AUTHORS: Updating authors list
  AUTHORS
Labels: Target: v1.8.0

#4599 UCT/CUDA/CUDA_IPC: unmap only when there are no in-flight requests
  src/uct/cuda/cuda_ipc/cuda_ipc_cache.c
  src/uct/cuda/cuda_ipc/cuda_ipc_cache.h
  src/uct/cuda/cuda_ipc/cuda_ipc_ep.c
  src/uct/cuda/cuda_ipc/cuda_ipc_iface.c
  src/uct/cuda/cuda_ipc/cuda_ipc_iface.h
  src/uct/cuda/cuda_ipc/cuda_ipc_md.c
Labels: Waiting for Author Response

#4853 API/UCP: Allow querying the connection request fields on the server side
  src/ucp/api/ucp.h
  src/uct/api/uct_def.h
Labels: API

#4906 Backport: UCT/TCP/SOCKCM: UCT_SOCKCM_PRIV_DATA_LEN to 2048
  src/uct/tcp/sockcm/sockcm_def.h
Labels: Target: v1.8.0

#4902 API/UCT/GTEST: New function for the client & rename server's connect cb
  src/ucp/wireup/wireup_cm.c
  src/uct/api/tl.h
  src/uct/api/uct.h
  src/uct/api/uct_def.h
  src/uct/base/uct_cm.c
  src/uct/base/uct_cm.h
  src/uct/ib/rdmacm/rdmacm_cm.c
  src/uct/ib/rdmacm/rdmacm_cm_ep.c
  src/uct/ib/rdmacm/rdmacm_cm_ep.h
  src/uct/tcp/tcp_sockcm_ep.c
  test/gtest/uct/ib/test_sockaddr.cc
  test/gtest/uct/uct_test.cc
  test/gtest/uct/uct_test.h
Labels: API

#4910 JUCX: build ucx to include libjucx.so into release jar - v1.8
  buildlib/azure-pipelines-release.yml
Labels: Target: v1.8.0

#4920 UCP/WIREUP/CM: fix TL lanes selection according to device, backport to v1.8.x
  src/ucp/core/ucp_context.c
  src/ucp/core/ucp_context.h
  src/ucp/core/ucp_ep.c
  src/ucp/core/ucp_ep.h
  src/ucp/wireup/wireup.c
  src/ucp/wireup/wireup.h
  src/ucp/wireup/wireup_cm.c
Labels: Target: v1.8.0

#4915 AZP: run new bunch of tests - (legacy&GPU) — v1.8
  buildlib/azure-pipelines.yml
  buildlib/tests.yml
  contrib/test_jenkins.sh
Labels: Target: v1.8.0

#4777 UCT/SM/MM: Poll multi FIFO elements in a single iface progress + optimizations
  src/uct/sm/mm/base/mm_ep.c
  src/uct/sm/mm/base/mm_iface.c
  src/uct/sm/mm/base/mm_iface.h
Labels: Optimization
