Repository openucx/ucx, pull requests merged in 2020-01, with the labels that each got.

#4637 DOCS/RTD: Update home page content
  docs/source/_static/UCX_Layers.png
  docs/source/index.rst
  docs/source/ucx_features.rst
Labels: Documentation

#4586 UCT/DOC: document uct_ep_disconnect return codes
  src/uct/api/uct.h
Labels: Documentation

#4667 UCP/API/DOC: Fix ucp_get_[nb|nbi] documentation
  src/ucp/api/ucp.h
Labels: API, Documentation

#4661 JAVA: Backport JUCX fixes to v1.7.x
  Makefile.am
  bindings/java/Makefile.am
  bindings/java/pom.xml.in
  bindings/java/src/main/native/Makefile.am
  config/m4/java.m4
  configure.ac
  contrib/buildrpm.sh
  contrib/rpmdef.sh.in
  contrib/test_jenkins.sh
  ucx.spec.in
Labels: Target: v1.7.x

#4659 UCT/TCP/GTEST: Protect against connection from non-UCX sock-based app
  src/ucs/sys/sock.c
  src/ucs/sys/sock.h
  src/uct/tcp/tcp.h
  src/uct/tcp/tcp_cm.c
  src/uct/tcp/tcp_ep.c
  src/uct/tcp/tcp_iface.c
  test/gtest/Makefile.am
  test/gtest/uct/tcp/test_tcp.cc
Labels: Target: v1.7.x

#4636 UCP/RNDV: Enable shared memory rendezvous protocol over xpmem
  src/ucp/core/ucp_ep.c
  src/ucp/core/ucp_ep.h
  src/ucp/core/ucp_mm.h
  src/ucp/core/ucp_rkey.c
  src/ucp/tag/rndv.c
  src/ucp/wireup/select.c
  test/gtest/ucp/test_ucp_mmap.cc
Labels: Optimization

#4683 UCP: Do not hash first msg fragment for tag offload
  src/ucp/tag/eager_rcv.c
Labels: Bugfix

#4699 README: fixed broken link and fixed ucx_perftest example
  README
Labels: Documentation

#4694 TEST: ucp_client_server.c remove progress call from server's conn_req_cb
  test/examples/ucp_client_server.c
Labels: Test

#4709 UCT/SM/MM: Increase MM segment size to include UCP header for 8KB msgs
  src/uct/sm/mm/base/mm_iface.c
Labels: Optimization
