Repository openucx/ucx, pull requests merged in 2020-05, with the labels that each got.

#5122 DOCS: readthedocs update
  docs/source/download.md
  docs/source/index.rst
  docs/source/ucx_features.rst
Labels: Documentation

#5037 UCP/AM: Fix stub ep multi-bcopy flow
  src/ucp/core/ucp_am.c
  test/gtest/ucp/test_ucp_sockaddr.cc
Labels: Ready for Review

#5150 UCT/UD: Remove duplicate call to ucs_wtimer_add()
  src/uct/ib/ud/base/ud_ep.c
Labels: Bugfix

#4990 UCP/API: added atomic fetch nbx API
  src/ucp/api/ucp.h
  src/ucp/rma/amo_send.c
Labels: API

#5071 SPEC: specify openjdk-devel package as dependency
  buildlib/azure-pipelines-pr.yml
  buildlib/fedora.Dockerfile
  ucx.spec.in
Labels: Waiting for Author Response

#5182 UCT/API: return device index as part of tl_resource/device descriptor
  src/uct/api/uct.h
  src/uct/base/uct_iface.h
  src/uct/base/uct_md.c
Labels: API
