Repository openucx/ucx, pull requests merged in 2020-02, with the labels that each got.

#4711 UCP/API/DOC: Fix typo in UCP Worker description
  bindings/java/src/main/java/org/openucx/jucx/ucp/UcpWorker.java
  src/ucp/api/ucp_def.h
Labels: Documentation

#4708 TEST: ucp_client_server.c - add Tag-Matching support.
  test/examples/ucp_client_server.c
  test/gtest/ucs/test_callbackq.cc
Labels: Test

#4682 GTEST/API: add cm config to gtest and update doc for the uct functions
  src/uct/api/uct.h
  test/gtest/uct/uct_test.cc
  test/gtest/uct/uct_test.h
Labels: Documentation

#4729 TEST: ucp_client_server.c - add an option to set iterations.
  test/examples/ucp_client_server.c
Labels: Test

#4448 GTEST/UCP/SOCKADDR: extend testing for close protocol
  test/gtest/ucp/test_ucp_sockaddr.cc
  test/gtest/ucp/ucp_test.cc
  test/gtest/ucp/ucp_test.h
Labels: Approved pending CI, Ready for Review

#4638 UCT/API: Add API for endpoints multi-path
  src/uct/api/uct.h
  src/uct/base/uct_iface.c
Labels: API

#4761 UCP/EP/CM: fix close protocol on server side
  src/ucp/core/ucp_ep.c
  src/ucp/wireup/wireup_cm.c
  test/gtest/ucp/ucp_test.cc
Labels: Bugfix

#4688 UCT/IB: consider the RoCE version when checking reachability.
  src/ucs/sys/sock.c
  src/ucs/sys/sock.h
  src/uct/ib/base/ib_device.c
  src/uct/ib/base/ib_device.h
  src/uct/ib/base/ib_iface.c
  src/uct/ib/base/ib_iface.h
  src/uct/ib/cm/cm_ep.c
  src/uct/ib/dc/dc_mlx5.c
  src/uct/ib/dc/dc_mlx5_devx.c
  src/uct/ib/dc/dc_mlx5_ep.c
  src/uct/ib/mlx5/exp/ib_exp_md.c
  src/uct/ib/mlx5/ib_mlx5_log.c
  src/uct/ib/rc/accel/rc_mlx5_common.c
  src/uct/ib/rc/accel/rc_mlx5_devx.c
  src/uct/ib/rdmacm/rdmacm_cm.c
  src/uct/ib/ud/base/ud_iface.c
  src/uct/ib/ud/base/ud_iface.h
  test/gtest/uct/ib/test_ib.cc
Labels: Bugfix

#4771 GTEST/UCP/SOCKADDR: add a loop around UCS_ERR_BUSY on listener create
  test/gtest/common/test_helpers.cc
  test/gtest/common/test_helpers.h
  test/gtest/ucp/test_ucp_sockaddr.cc
  test/gtest/ucp/ucp_test.cc
  test/gtest/uct/ib/test_sockaddr.cc
  test/gtest/uct/uct_test.cc
Labels: Bugfix

#4782 UCP/UCT/API/GTEST: Add field mask usage to the client-server CM callbacks
  src/ucp/wireup/wireup_cm.c
  src/ucp/wireup/wireup_cm.h
  src/ucp/wireup/wireup_ep.c
  src/uct/api/uct.h
  src/uct/api/uct_def.h
  src/uct/base/uct_cm.c
  src/uct/base/uct_cm.h
  src/uct/ib/rdmacm/rdmacm_cm.c
  src/uct/ib/rdmacm/rdmacm_cm_ep.c
  src/uct/ib/rdmacm/rdmacm_ep.h
  src/uct/ib/rdmacm/rdmacm_iface.c
  src/uct/ib/rdmacm/rdmacm_listener.h
  src/uct/tcp/sockcm/sockcm_ep.c
  src/uct/tcp/sockcm/sockcm_ep.h
  src/uct/tcp/tcp_listener.h
  src/uct/tcp/tcp_sockcm_ep.c
  test/gtest/uct/ib/test_sockaddr.cc
  test/gtest/uct/uct_test.cc
  test/gtest/uct/uct_test.h
Labels: API

#4760 UCS/ARCH: Added optimized memcpy for ThunderX2
  config/m4/compiler.m4
  configure.ac
  src/ucs/Makefile.am
  src/ucs/arch/aarch64/cpu.h
  src/ucs/arch/aarch64/memcpy_thunderx2.S
Labels: Optimization

#4802 NEWS: Backport NEWS file from v.1.7.x branch.
  NEWS
Labels: Documentation

#4800 UCT/API: add client's sockaddr as param to server connection request cb
  src/uct/api/uct_def.h
  src/uct/ib/rdmacm/rdmacm_cm.c
  src/uct/tcp/tcp_sockcm_ep.c
  test/examples/ucp_client_server.c
  test/gtest/uct/ib/test_sockaddr.cc
Labels: API
