Repository openucx/ucx, pull requests merged in 2020-12, with the labels that each got.

#5956 GTEST/UCP/TAG: Fix offload thresh check
  test/gtest/ucp/test_ucp_tag.cc
Labels: Bugfix

#5974 AZP: add warning for azure
  buildlib/tests.yml
  contrib/test_jenkins.sh
Labels: Waiting for Author Response

#5966 UCP: Recv msg nbx routine.
  NEWS
  src/ucp/api/ucp.h
  src/ucp/tag/tag_recv.c
  test/gtest/ucp/test_ucp_tag_probe.cc
Labels: API

#5992 API/UCT/IFACE: added keepalive_timeout value
  src/uct/api/uct.h
Labels: API

#5965 Ignore PFs without RDMA cap on BF2 according to its gid_tlb_len==0
  src/uct/ib/base/ib_device.c
Labels: Waiting for Author Response

#5958 AZP: analyzer for iodemo
  buildlib/az-network-corrupter.sh
  buildlib/azure-pipelines-pr.yml
  buildlib/io-demo.yml
  buildlib/io_demo/az-stage-io-demo.yaml
  buildlib/io_demo/io-demo.yml
  buildlib/io_demo/iodemo_analyzer.py
Labels: Waiting for Author Response

#5941 UCT/API: Added new UCT EP AM short IOV API.
  src/ucp/core/ucp_ep.c
  src/ucp/wireup/wireup_ep.c
  src/uct/api/tl.h
  src/uct/api/uct.h
  src/uct/base/uct_iface.c
  src/uct/base/uct_iface.h
  src/uct/ib/dc/dc_mlx5.c
  src/uct/ib/rc/accel/rc_mlx5_iface.c
  src/uct/ib/rc/verbs/rc_verbs_iface.c
  src/uct/ib/rdmacm/rdmacm_cm.c
  src/uct/ib/ud/accel/ud_mlx5.c
  src/uct/ib/ud/verbs/ud_verbs.c
  src/uct/sm/mm/base/mm_iface.c
  src/uct/sm/self/self.c
  src/uct/tcp/tcp_iface.c
  src/uct/tcp/tcp_sockcm.c
  src/uct/ugni/rdma/ugni_rdma_iface.c
  src/uct/ugni/smsg/ugni_smsg_iface.c
  src/uct/ugni/udt/ugni_udt_iface.c
  test/gtest/uct/test_p2p_am.cc
  test/gtest/uct/test_p2p_err.cc
  test/gtest/uct/test_p2p_mix.cc
  test/gtest/uct/test_p2p_mix.h
  test/gtest/uct/test_stats.cc
Labels: API
