Repository openucx/ucx, pull requests merged in 2021-02, with the labels that each got.

#6261 UCS: A fix for cross compilation support in configure
  src/ucs/configure.m4
Labels: Release Blocker

#5986 UCT/IB: Fix cq creation failure using legacy ibv api
  src/uct/ib/base/ib_iface.c
  src/uct/ib/base/ib_verbs.h
Labels: Bugfix

#6248 UCP/AM: Fix releasing of deferred data
  src/ucp/core/ucp_am.c
  src/ucp/core/ucp_request.h
  test/gtest/ucp/test_ucp_am.cc
Labels: Ready for Review

#6274 UCS: A fix for cross compilation support in configure - v1.10.x
  src/ucs/configure.m4
Labels: Release Blocker

#6276 UCP/AM: Fix releasing of deferred data - v1.10.x
  src/ucp/core/ucp_am.c
  src/ucp/core/ucp_request.h
  test/gtest/ucp/test_ucp_am.cc
Labels: Release Blocker

#6277 IB/ADDRESS: pack MTU value for non 4K value - v1.10
  src/uct/ib/base/ib_iface.c
  test/gtest/uct/ib/test_ib.cc
  test/gtest/uct/ib/test_ib_pkey.cc
  test/gtest/uct/ib/test_ud_ds.cc
Labels: Release Blocker

#6278 UCT/RC: Fix QP destroy for EXP flow - v1.10
  src/uct/ib/rc/accel/rc_mlx5_common.c
  src/uct/ib/rc/accel/rc_mlx5_common.h
  src/uct/ib/rc/accel/rc_mlx5_ep.c
Labels: Release Blocker

#6232 UCP/API: Flag to silence request leak check
  src/ucp/api/ucp.h
  src/ucp/core/ucp_worker.c
  src/ucp/core/ucp_worker.h
  test/gtest/common/test.cc
  test/gtest/common/test.h
  test/gtest/ucp/test_ucp_worker.cc
Labels: API

#6245 UCP/CORE/WIREUP/GTEST: Fix check intersection with CM initial configuration on TMP EP
  src/ucp/core/ucp_ep.c
  src/ucp/core/ucp_ep.h
  src/ucp/wireup/select.c
  src/ucp/wireup/wireup.c
  src/ucp/wireup/wireup_cm.c
  src/ucp/wireup/wireup_ep.c
  src/ucp/wireup/wireup_ep.h
  test/gtest/ucp/test_ucp_sockaddr.cc
Labels: Release Blocker

#6332 AUTHORS: Updating the list of authors - v1.10.0
  AUTHORS
Labels: Release Blocker

#6333 NEWS: Update before RC3 - v1.10.0
  NEWS
Labels: Release Blocker

#6342 AZP: add new OS for release CI
  buildlib/az-distro-release.yml
  buildlib/azure-pipelines-release.yml
Labels: Release Blocker

#6340 JUCX: add new ucp_mmap_params + test GPU operations.
  bindings/java/src/main/java/org/openucx/jucx/ucp/UcpConstants.java
  bindings/java/src/main/java/org/openucx/jucx/ucp/UcpMemMapParams.java
  bindings/java/src/main/java/org/openucx/jucx/ucp/UcpMemory.java
  bindings/java/src/main/native/context.cc
  bindings/java/src/main/native/ucp_constants.cc
  bindings/java/src/test/java/org/openucx/jucx/UcpEndpointTest.java
  bindings/java/src/test/java/org/openucx/jucx/UcpMemoryTest.java
  bindings/java/src/test/java/org/openucx/jucx/UcxTest.java
  buildlib/az-helpers.sh
  buildlib/jucx/jucx-test.yml
  src/ucp/api/ucp.h
  src/ucp/api/ucp_def.h
  src/ucp/core/ucp_mm.c
  src/ucp/core/ucp_mm.h
  test/gtest/ucp/test_ucp_mmap.cc
Labels: API

#6178 UCT/API: return base addr and alloc len from md_mem_query
  src/uct/api/uct.h
  src/uct/cuda/base/cuda_md.c
  src/uct/rocm/base/rocm_base.c
  test/gtest/uct/test_md.cc
Labels: API
