Repository openucx/ucx, pull requests merged in 2021-11, with the labels that each got.

#7460 [DNM] Do Not Merge. Only for CICD test purpose
  test/apps/iodemo/io_demo.cc
Labels: WIP-DNM

#7626 UCP/DATATYPE: Fix length==0 initialization of dt_reg array
  src/ucp/core/ucp_request.inl
  src/ucp/dt/datatype_iter.c
  test/gtest/ucp/test_ucp_proto.cc
Labels: Bugfix

#7628 UCT/IB/MLX5: Fix TX WQ overflow check
  src/uct/ib/mlx5/ib_mlx5.c
  src/uct/ib/mlx5/ib_mlx5.h
  src/uct/ib/mlx5/ib_mlx5.inl
  src/uct/ib/rc/accel/rc_mlx5.inl
  src/uct/ib/ud/accel/ud_mlx5.c
Labels: Bugfix

#7685 BINDINGS/JAVA: Fix typo
  bindings/java/src/main/java/org/openucx/jucx/ucp/UcpEndpoint.java
  bindings/java/src/main/java/org/openucx/jucx/ucp/UcpMemory.java
  bindings/java/src/main/native/jucx_common_def.cc
  bindings/java/src/main/native/ucs_constants.cc
  bindings/java/src/test/java/org/openucx/jucx/UcpEndpointTest.java
  bindings/java/src/test/java/org/openucx/jucx/UcpWorkerTest.java
  docs/LoggingStyle.md
  docs/doxygen/design.md
Labels: Approved pending CLA
