Repository openucx/ucx, pull requests merged in 2021-04, with the labels that each got.

#6590 UCP/WIREUP/TEST: Fix endpoint reconfiguration error with many lanes
  contrib/test_jenkins.sh
  src/ucp/wireup/select.c
  src/uct/ib/dc/dc_mlx5.c
  src/uct/ib/dc/dc_mlx5.h
  src/uct/ib/dc/dc_mlx5_devx.c
  src/uct/ib/mlx5/dv/ib_mlx5_dv.c
  src/uct/ib/mlx5/ib_mlx5.h
  src/uct/ib/rc/accel/rc_mlx5_devx.c
Labels: Bugfix

#6265 UCT/API/TLS: Define AM alignment in iface params
  src/ucp/tag/probe.c
  src/uct/api/uct.h
  src/uct/base/uct_iface.c
  src/uct/base/uct_iface.h
  src/uct/ib/base/ib_iface.c
  src/uct/ib/base/ib_iface.h
  src/uct/ib/rc/base/rc_iface.c
  src/uct/ib/ud/base/ud_iface.c
  src/uct/sm/mm/base/mm_iface.c
  src/uct/sm/self/self.c
  test/gtest/uct/test_p2p_am.cc
  test/gtest/uct/test_tag.cc
  test/gtest/uct/uct_p2p_test.cc
  test/gtest/uct/uct_p2p_test.h
  test/gtest/uct/uct_test.cc
  test/gtest/uct/uct_test.h
Labels: API, Ready for Review

#6557 UCP/API: Added name to worker parameters.
  src/ucp/api/ucp.h
  src/ucp/api/ucp_def.h
  src/ucp/core/ucp_context.c
  src/ucp/core/ucp_context.h
  src/ucp/core/ucp_worker.c
  src/ucp/core/ucp_worker.h
Labels: API

#6609 UCP/API: Replaced 'maximal' by 'maximum' in UCP/API docs.
  src/ucp/api/ucp.h
Labels: Documentation

#6732 UCT/HWTM: First fragment bit support for MP XRQ
  src/uct/ib/mlx5/dv/ib_mlx5_ifc.h
  src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
  src/uct/ib/mlx5/ib_mlx5.h
  src/uct/ib/rc/accel/rc_mlx5.inl
Labels: Feature, Ready for Review
