Repository openucx/ucx, pull requests merged in 2021-06, with the labels that each got.

#6917 UCS/VFS: Set affinity for FUSE thread via option.
  src/ucs/config/global_opts.c
  src/ucs/config/global_opts.h
  src/ucs/vfs/fuse/vfs_fuse.c
Labels: Ready for Review

#6854 API/UCP/ERR-HANDLING: added memory invalidation on error
  src/ucp/core/ucp_ep.c
  src/ucp/core/ucp_request.c
  src/ucp/core/ucp_request.h
  src/ucp/rndv/rndv.c
  src/ucp/wireup/select.c
  src/uct/api/v2/uct_v2.h
  src/uct/base/uct_md.h
  src/uct/ib/base/ib_md.c
  test/gtest/ucp/test_ucp_sockaddr.cc
  test/gtest/ucp/ucp_test.cc
  test/gtest/ucp/ucp_test.h
  test/gtest/uct/test_md.cc
  test/gtest/uct/test_md.h
Labels: API

#6883 UCT/IFACE: Check RC verbs support by creating a dummy QP
  src/uct/ib/rc/verbs/rc_verbs_iface.c
Labels: Ready for Review

#6954 UCT/DC/MLX5: Fix deadlock between DCI resources and RDMA_READ credits
  src/uct/ib/dc/dc_mlx5_ep.h
Labels: Bugfix

#6924 UCS/VFS: Symbolic links support in VFS.
  src/ucs/vfs/base/vfs_obj.c
  src/ucs/vfs/base/vfs_obj.h
  src/ucs/vfs/fuse/vfs_fuse.c
  test/gtest/ucs/test_vfs.cc
Labels: Ready for Review
