Repository openucx/ucx, pull requests merged in 2021-03, with the labels that each got.

#6404 TOOLS/PERF/UCP: Allow 0 length msg for AM and TAG benchmarks
  src/tools/perf/lib/ucp_tests.cc
  test/gtest/ucp/test_ucp_perf.cc
Labels: Ready for Review

#6368 UCP/API: Added context name to UCP parameters.
  src/ucp/api/ucp.h
  src/ucp/api/ucp_def.h
  src/ucp/core/ucp_context.c
  src/ucp/core/ucp_context.h
Labels: API

#6441 AZP: do not include libjucx into release packages. [v.1.10]
  buildlib/az-distro-release.yml
  buildlib/azure-pipelines-release.yml
  debian/rules.in
Labels: Release Blocker

#6137 UCT/API: Support interface query by operation and memory type
  Makefile.am
  src/uct/api/v2/uct_v2.h
  src/uct/base/uct_iface.c
  test/gtest/Makefile.am
  test/gtest/uct/v2/test_uct_query.cc
Labels: API

#6436 UCP: Print error if no proper device exists for ep connection
  src/ucp/wireup/wireup_cm.c
  test/gtest/ucp/test_ucp_sockaddr.cc
Labels: Ready for Review

#6445 UCP/AM: Use short_iov for short protocols
  src/ucp/core/ucp_am.c
  src/ucp/core/ucp_ep.c
  src/ucp/core/ucp_ep.h
  src/ucp/proto/proto_am.inl
  src/uct/ib/base/ib_iface.c
  src/uct/ib/ud/base/ud_iface.c
  test/gtest/ucp/test_ucp_am.cc
Labels: Ready for Review

#6378 UCT/API/SOCKADDR: extend connection establishment API
  src/uct/api/tl.h
  src/uct/api/uct.h
  src/uct/api/uct_def.h
Labels: API

#6262 UCP/LISTENER: ucp_listener_create
  src/ucp/api/ucp.h
  src/ucp/core/ucp_listener.c
  src/uct/ib/rdmacm/rdmacm_listener.c
  test/gtest/ucp/test_ucp_sockaddr.cc
Labels: Documentation

#6358 UCP/AM: Implement ucp_am_recv_data_nbx for eager messages
  src/ucp/core/ucp_am.c
  src/ucp/core/ucp_request.h
  src/ucp/core/ucp_request.inl
  test/gtest/ucp/test_ucp_am.cc
Labels: Ready for Review

#6474 GTEST: test send-recv between client/server with diff UCX_IB_NUM_PATHS
  test/gtest/ucp/test_ucp_sockaddr.cc
Labels: Test

#6555 IODEMO: fix stream_recv_callback on failed conn
  test/apps/iodemo/ucx_wrapper.cc
Labels: Bugfix

#6552 UCP: Add ucp_lib_query API
  NEWS
  src/ucp/api/ucp.h
  src/ucp/core/ucp_context.c
  test/gtest/ucp/test_ucp_context.cc
Labels: API

#6567 UCP: Documentation of ucp_request_param_t uses type name instead of field name for callback function
  src/ucp/api/ucp.h
Labels: Documentation

#6580 UCT/DC: Fix UCX_IB_NUM_PATHS influence on DCI pool logic
  src/uct/ib/dc/dc_mlx5.c
  src/uct/ib/dc/dc_mlx5.h
  src/uct/ib/dc/dc_mlx5_ep.c
Labels: Bugfix
