Repository openucx/ucx, pull requests merged in 2021-05, with the labels that each got.

#6749 UCS/QUEUE/FRAGLIST: Fix checking for last element in fraglist queue
  src/ucs/datastruct/frag_list.c
  src/ucs/datastruct/queue.h
  test/gtest/ucs/test_datatype.cc
Labels: Bugfix

#6558 UCT/CMA/KNEM: Add errh support
  src/uct/base/uct_iface.c
  src/uct/base/uct_iface.h
  src/uct/cuda/cuda_ipc/cuda_ipc_ep.c
  src/uct/cuda/cuda_ipc/cuda_ipc_ep.h
  src/uct/ib/base/ib_iface.h
  src/uct/ib/dc/dc_mlx5.c
  src/uct/ib/rc/accel/rc_mlx5_iface.c
  src/uct/ib/rc/verbs/rc_verbs_iface.c
  src/uct/sm/mm/base/mm_ep.c
  src/uct/sm/mm/base/mm_iface.c
  src/uct/sm/mm/base/mm_iface.h
  src/uct/sm/scopy/cma/cma_ep.c
  src/uct/sm/scopy/cma/cma_ep.h
  src/uct/sm/scopy/cma/cma_iface.c
  test/gtest/common/test_obj_size.cc
  test/gtest/uct/test_peer_failure.cc
Labels: Ready for Review

#6774 Fix active-message-with-reply on failed ep and test it
  src/ucp/wireup/wireup.c
  test/gtest/ucp/test_ucp_peer_failure.cc
Labels: Bugfix

#6760 UCP/API: Fix the documentation of ucp_listener_create
  src/ucp/api/ucp.h
Labels: Documentation

#6782 CONFIG/M4: Fix libnuma detection macro
  buildlib/tools/builds.sh
  config/m4/sysdep.m4
  configure.ac
Labels: Bugfix

#6786 UCS/FRAGLIST: Fix sn compare in assert
  src/ucs/datastruct/frag_list.c
Labels: Bugfix

#6403 UCP/API: Support endpoint performance evaluation
  src/ucp/api/ucp.h
  src/ucp/core/ucp_ep.c
  test/gtest/Makefile.am
  test/gtest/ucp/test_ucp_ep.cc
Labels: API

#6803 DOC: fixed typos in comments
  src/ucp/core/ucp_ep.c
  src/ucp/core/ucp_ep.h
  src/ucp/wireup/select.c
  src/uct/api/uct.h
  test/gtest/ucp/test_ucp_sockaddr.cc
Labels: Documentation

#6615 UCP/API: Added name to ep parameters.
  src/ucp/api/ucp.h
  src/ucp/api/ucp_def.h
  src/ucp/core/ucp_ep.c
  src/ucp/core/ucp_ep.h
Labels: API

#6804 UCP/API: Remove UCP AM chunk API
  src/tools/perf/lib/ucp_tests.cc
  src/ucp/api/ucp.h
  src/ucp/api/ucp_def.h
Labels: Ready for Review

#6554 UCP/API: ucp_request_query functionality.
  src/ucp/api/ucp.h
  src/ucp/core/ucp_request.c
  src/ucp/core/ucp_worker.c
  test/gtest/Makefile.am
  test/gtest/ucp/test_ucp_request.cc
Labels: API

#6819 API/EXPERIMENTAL/MD: added flags-based mem_dereg
  src/uct/api/uct.h
  src/uct/api/v2/uct_v2.h
  src/uct/base/uct_md.c
  src/uct/base/uct_md.h
  src/uct/cuda/cuda_copy/cuda_copy_md.c
  src/uct/cuda/cuda_ipc/cuda_ipc_md.c
  src/uct/cuda/gdr_copy/gdr_copy_md.c
  src/uct/ib/base/ib_md.c
  src/uct/rocm/copy/rocm_copy_md.c
  src/uct/rocm/gdr/rocm_gdr_md.c
  src/uct/rocm/ipc/rocm_ipc_md.c
  src/uct/sm/mm/xpmem/mm_xpmem.c
  src/uct/sm/scopy/cma/cma_md.c
  src/uct/sm/scopy/knem/knem_md.c
  src/uct/sm/self/self.c
  src/uct/tcp/tcp_md.c
  src/uct/ugni/base/ugni_md.c
Labels: API
