Repository openucx/ucx, pull requests merged in 2022-01, with the labels that each got.

#7779 UCP: Implement passing user memh in proto_v1
  src/ucp/core/ucp_am.c
  src/ucp/core/ucp_ep.c
  src/ucp/core/ucp_ep.h
  src/ucp/core/ucp_request.c
  src/ucp/core/ucp_request.h
  src/ucp/core/ucp_request.inl
  src/ucp/rndv/rndv.c
  src/ucp/rndv/rndv.h
  src/ucp/stream/stream_send.c
  src/ucp/tag/eager_snd.c
  src/ucp/tag/offload.c
  src/ucp/tag/offload.h
  src/ucp/tag/tag_recv.c
  src/ucp/tag/tag_rndv.c
  src/ucp/tag/tag_rndv.h
  src/ucp/tag/tag_send.c
Labels: Ready for Review

#7840 API/V2: minor typo
  src/uct/api/v2/uct_v2.h
  test/gtest/uct/v2/test_uct_query.cc
Labels: API

#7854 UCT/UD: Fix completion callback not called for flush operation
  src/uct/ib/ud/base/ud_ep.c
  src/uct/ib/ud/base/ud_iface.c
Labels: Bugfix

#7832 UCP/CORE: Support AM align offset
  src/ucp/api/ucp.h
  src/ucp/core/ucp_am.c
  src/ucp/core/ucp_am.h
  src/ucp/core/ucp_request.inl
  src/ucp/core/ucp_worker.c
  test/gtest/ucp/test_ucp_am.cc
Labels: API

#7866 UCM/BISTRO: Translate relative jumps
  src/ucm/bistro/bistro_x86_64.c
  src/ucm/bistro/bistro_x86_64.h
  src/ucm/util/log.c
  test/apps/test_cuda_hook.c
Labels: Bugfix

#7791 UCP/UCS/UCT: Fix memtype_cache region info after merge
  src/ucp/core/ucp_mm.c
  src/ucs/memory/memtype_cache.c
  src/ucs/memory/memtype_cache.h
  src/uct/cuda/base/cuda_md.c
  test/gtest/ucs/test_memtype_cache.cc
Labels: Bugfix

#7870 UCT/EP: move local_sockaddr to end of uct_ep_params_t to fix ABI break
  src/uct/api/uct.h
Labels: API

#7877 UCM/BISTRO: Translate relative jumps - v1.12.x
  NEWS
  src/ucm/bistro/bistro_x86_64.c
  src/ucm/bistro/bistro_x86_64.h
  src/ucm/util/log.c
  test/apps/test_cuda_hook.c
Labels: Bugfix

#7820 [DNM] Do Not Merge. Only for CICD test purpose
  test/apps/iodemo/io_demo.cc
Labels: WIP-DNM
