Repository openucx/ucx, pull requests merged in 2022-03, with the labels that each got.

#8003 NEWS: Update for v1.12.1-rc3 (v1.12.x)
  NEWS
Labels: Documentation

#8007 TEST: Don't generate .tap files
  contrib/test_jenkins.sh
  test/gtest/Makefile.am
  test/gtest/common/main.cc
  test/gtest/common/tap.h
Labels: Cleanup

#8008 UCT/IB: Don't fail if can't detect RoCE subnet mask
  src/uct/ib/base/ib_iface.c
Labels: Bugfix

#8005 TOOLS/PERF: Fix worker destroy in error flow
  src/tools/perf/lib/libperf.c
Labels: Bugfix

#8009 TEST/GTEST: Limit test buffer sizes according to memory size
  test/gtest/common/test_helpers.cc
  test/gtest/common/test_helpers.h
  test/gtest/ucp/test_ucp_tag_match.cc
  test/gtest/ucs/test_mpool.cc
  test/gtest/uct/uct_p2p_test.cc
Labels: Test

#8012 TOOLS/PERF: Fix assertion in test_uct_loopback
  src/tools/perf/lib/uct_tests.cc
Labels: Bugfix

#7984 UCT/API/MM/UCP: Introduce PEER_CHECK AM Bcopy flag, resolve remote ID for UCP EP if PEER_FAILURE requested
  src/ucp/core/ucp_am.c
  src/ucp/core/ucp_ep.c
  src/uct/api/uct.h
  src/uct/base/uct_iface.c
  src/uct/base/uct_iface.h
  src/uct/cuda/cuda_ipc/cuda_ipc_ep.c
  src/uct/sm/mm/base/mm_ep.c
  src/uct/sm/scopy/cma/cma_ep.c
  test/gtest/ucp/test_ucp_am.cc
  test/gtest/uct/test_peer_failure.cc
Labels: API

#8004 UCT/IB: Improve DevX debug prints
  src/uct/ib/base/ib_md.c
  src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
  src/uct/ib/rc/accel/rc_mlx5_common.c
  src/uct/ib/rc/accel/rc_mlx5_common.h
  src/uct/ib/rc/accel/rc_mlx5_devx.c
Labels: Enhancement

#8006 TOOLS/PERF: Fix status exchange with multiple threads during warmup
  src/tools/perf/lib/libperf.c
Labels: Bugfix

#8010 UCT/IB: Fix subfunction device query
  src/uct/ib/base/ib_device.c
  src/uct/ib/base/ib_device.h
  src/uct/ib/base/ib_md.c
Labels: Bugfix

#8011 AZP/CI: Skip representor devices
  buildlib/az-helpers.sh
  contrib/test_jenkins.sh
  test/apps/test_ucx_tls.py
Labels: Test

#8030 UCT/API/BASE/CUDA/IB: Introduce max_inflight_eps attribute in perf_attr
  src/uct/api/v2/uct_v2.h
  src/uct/base/uct_iface.c
  src/uct/cuda/cuda_copy/cuda_copy_iface.c
  src/uct/cuda/gdr_copy/gdr_copy_iface.c
  src/uct/ib/base/ib_iface.c
  src/uct/ib/dc/dc_mlx5.c
  src/uct/ib/rc/accel/rc_mlx5_iface.c
  src/uct/ib/rc/base/rc_iface.c
  src/uct/ib/rc/base/rc_iface.h
  src/uct/ib/rc/verbs/rc_verbs_iface.c
  src/uct/sm/mm/base/mm_iface.c
Labels: API

#8039 UCT/API: Introduce interfaces features
  src/uct/api/uct.h
Labels: API

#8060 UCM/UTIL: Fix HAVE_DECL_GETAUXVAL ifdefs
  src/ucm/util/reloc.c
Labels: Approved pending CLA
