Repository openucx/ucx, pull requests merged in 2023-02, with the labels that each got.

#8805 Add rkey_ptr to self transport, tag matching performance improvement
  src/uct/Makefile.am
  src/uct/sm/base/sm_md.c
  src/uct/sm/base/sm_md.h
  src/uct/sm/mm/base/mm_md.c
  src/uct/sm/mm/base/mm_md.h
  src/uct/sm/self/self.c
Labels: Enhancement

#8865 UCP/EP: Fix rendezvous threshold for multi-path
  src/ucp/core/ucp_ep.c
Labels: Bugfix

#8847 UCT/SM/SELF: Choosing self rndv/rkey_ptr for big messages in same-process communications
  src/uct/sm/self/self.c
  test/gtest/ucp/test_ucp_tag_xfer.cc
  test/gtest/ucp/test_ucp_wireup.cc
Labels: Ready for Review

#8769 UCT/IB/MLX5DV: separate testing of AMO and KSM caps
  src/tools/perf/lib/libperf_memory.c
  src/ucp/core/ucp_context.c
  src/ucp/core/ucp_ep.c
  src/ucp/core/ucp_mm.c
  src/ucp/core/ucp_request.c
  src/ucp/wireup/select.c
  src/uct/api/uct.h
  src/uct/api/v2/uct_v2.h
  src/uct/base/uct_iface.c
  src/uct/base/uct_md.c
  src/uct/base/uct_md.h
  src/uct/base/uct_mem.c
  src/uct/ib/base/ib_md.c
  src/uct/ib/base/ib_md.h
  src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
  test/gtest/uct/test_md.cc
  test/gtest/uct/test_md.h
  test/gtest/uct/uct_test.cc
Labels: API
