Repository openucx/ucx, pull requests merged in 2023-01, with the labels that each got.

#8789 UCP/API: Updated ucp_worker_release_address description.
  src/ucp/api/ucp.h
Labels: Documentation

#8802 TOOLS/PERF: Fix worker flush deadlock when using multiple workers
  Makefile.am
  src/tools/perf/lib/libperf.c
Labels: Bugfix

#8816 UCT/CUDA: Pass page-aligned address and length to dmabuf query
  src/uct/cuda/cuda_copy/cuda_copy_md.c
Labels: Bugfix

#8779 GTEST: Adding explicit call to nvml init
  test/gtest/common/mem_buffer.cc
  test/gtest/uct/uct_p2p_test.cc
Labels: Ready for Review
