Repository openucx/ucx, pull requests merged in 2024-04, with the labels that each got.

#9766 TOOLS/PERF/LIB: bugfixes for multithreading in UCP perftest
  contrib/ucx_perftest_config/test_types_ucp
  src/tools/perf/lib/libperf.c
  src/tools/perf/lib/libperf_int.h
  src/tools/perf/lib/libperf_memory.c
  src/tools/perf/lib/libperf_thread.c
Labels: Bugfix, Ready for Review, CI (AZP/Jenkins)

#9743 UCT/IB/MLX5/DV: fixed memic iova in ksm registration
  src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
Labels: Bugfix

#9802 UCP/TAG: Call user callback from tag_recv only if NO_IMM_CMPL is passed
  src/ucp/core/ucp_request.inl
  src/ucp/tag/tag_recv.c
Labels: Bugfix

#9836 NEWS: Add 1.16.0 and 1.17.0-rc1 sections - v1.17.x
  NEWS
Labels: Documentation

#9835 CONFIG/SPEC: Bump version to 1.18.0
  configure.ac
  ucx.spec.in
Labels: Documentation
