Repository openucx/ucx, pull requests merged in 2024-11, with the labels that each got.

#10266 UCT/IB/MLX5/DC: add a docstring to dcs_hybrid policy (for ucx_info -cf)
  src/uct/ib/mlx5/dc/dc_mlx5.c
Labels: Documentation

#10142 TOOLS/PERF/LIB: add hints for devices and transports in UCT perftests
  src/tools/perf/lib/libperf.c
  src/ucs/datastruct/string_set.h
Labels: Ready for Review

#10271 GITHUB: Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Approved pending CI

#10127 STACK: Change PATH_MAX stack allocation to heap
  src/tools/vfs/vfs_main.c
  src/ucp/proto/proto_debug.c
  src/ucs/config/parser.c
  src/ucs/debug/log.c
  src/ucs/debug/memtrack.c
  src/ucs/memory/numa.c
  src/ucs/sys/module.c
  src/ucs/sys/sock.c
  src/ucs/sys/string.c
  src/ucs/sys/string.h
  src/ucs/sys/topo/base/topo.c
  src/ucs/vfs/base/vfs_obj.c
  src/ucs/vfs/fuse/vfs_fuse.c
  src/ucs/vfs/sock/vfs_sock.c
  src/uct/ib/base/ib_device.c
  src/uct/sm/mm/posix/mm_posix.c
  src/uct/tcp/tcp_iface.c
  test/gtest/common/test_helpers.cc
  test/gtest/ucp/test_ucp_worker.cc
  test/gtest/ucs/test_string.cc
Labels: Approved pending CI

#10160 UCT/VERBS/RC: Fix the macro that is supposed fill desc within uct rc.
  src/uct/ib/rc/verbs/rc_verbs_impl.h
Labels: Approved pending CLA

#10262 UCT/IB/TEST: Configure available SLs in gtest
  test/gtest/uct/ib/test_ib.cc
Labels: Ready for Review

#10117 CI: improve Coverity error reporting
  buildlib/tools/coverity.sh
Labels: Ready for Review

#9963 BUILD/CONFIGURE: enforce 8KB stack threshold on compilation
  config/m4/compiler.m4
Labels: Approved pending CI

#10243 UCT/IB/MLX5/DC: hybrid dcs fixes - pending queue
  src/uct/ib/mlx5/dc/dc_mlx5.c
  src/uct/ib/mlx5/dc/dc_mlx5.inl
  src/uct/ib/mlx5/dc/dc_mlx5_ep.c
  src/uct/ib/mlx5/dc/dc_mlx5_ep.h
  test/gtest/uct/ib/test_dc.cc
Labels: Bugfix
