Repository openucx/ucx, pull requests merged in 2024-09, with the labels that each got.

#10113 TEST/COMPAT: Fix wire compat test failures
  buildlib/tools/check_tls_perf_caps.sh
Labels: WIP-DNM

#10133 UCT/IB/MLX5/DV: added missing conditional compilation checks for dm
  src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
Labels: Bugfix

#10146 UCT/IB/MLX5: enable ddp support when available
  src/uct/ib/configure.m4
  src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
  src/uct/ib/mlx5/ib_mlx5.h
  src/uct/ib/mlx5/rc/rc_mlx5_common.c
Labels: Ready for Review

#10166 CI: add AddressSanitizer load check in test_jenkins
  contrib/test_jenkins.sh
Labels: Approved pending CI

#10169 TOOLS/INFO: fix memory leak in print_ucp_ep_info()
  src/tools/info/proto_info.c
Labels: Bugfix, Ready for Review

#10187 UCT/IB/MLX5: reduce log level of both WC and NC unsupported
  src/uct/ib/mlx5/ib_mlx5.c
Labels: Approved pending CI

#10175 UCT/API: Change HIDE_ERRORS flag description
  src/uct/api/uct.h
Labels: API

#10157 UCT/IB/MLX5/DV: convert stack allocation at uct_ib_mlx5_devx_md_open() to heap
  src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
Labels: Approved pending CI

#10130 GTEST: reduce stack frame size in gtest macros
  test/gtest/common/googletest/gtest-param-test.h
  test/gtest/common/test.h
Labels: Approved pending CI
