Repository openucx/ucx, pull requests merged in 2024-07, with the labels that each got.

#9665 UCT/IB/DC: dynamic allocation of dci pools by configuration
  src/tools/info/type_info.c
  src/uct/ib/base/ib_device.h
  src/uct/ib/dc/dc_mlx5.c
  src/uct/ib/dc/dc_mlx5.h
  src/uct/ib/dc/dc_mlx5_devx.c
  src/uct/ib/dc/dc_mlx5_ep.c
  src/uct/ib/dc/dc_mlx5_ep.h
  test/gtest/uct/ib/test_dc.cc
Labels: Ready for Review

#9998 UCT/IB/DC: in poll_tx change is_valid_dci ucs_assert_always to ucs_as…
  src/uct/ib/dc/dc_mlx5.c
Labels: Ready for Review

#10017 UCS/SYS/COMPILER_DEF: use __func__ instead of __FUNCTION__ to meet standard
  src/ucm/cuda/cudamem.c
  src/ucm/util/log.h
  src/ucm/util/replace.h
  src/ucs/debug/assert.h
  src/ucs/debug/log_def.h
  src/ucs/memory/rcache_int.h
  src/ucs/profile/profile_defs.h
  src/uct/ib/base/ib_log.h
  src/uct/ib/mlx5/ib_mlx5_log.h
Labels: Portability

#9988 UCP: Add user_data to ucp_ep_query
  src/ucp/api/ucp.h
  src/ucp/core/ucp_ep.c
  src/ucp/core/ucp_ep.h
Labels: API
