Repository openucx/ucx, pull requests merged in 2024-02, with the labels that each got.

#9639 UCP/CUDA: Use static_bitmap structure
  src/ucp/core/ucp_context.c
  src/ucp/core/ucp_context.h
  src/ucp/core/ucp_ep.c
  src/ucp/core/ucp_types.h
  src/ucp/core/ucp_worker.c
  src/ucp/core/ucp_worker.inl
  src/ucp/rma/amo_sw.c
  src/ucp/rma/flush.c
  src/ucp/wireup/address.c
  src/ucp/wireup/address.h
  src/ucp/wireup/select.c
  src/ucp/wireup/wireup.c
  src/ucp/wireup/wireup_cm.c
  src/ucp/wireup/wireup_ep.c
  src/ucs/datastruct/bitmap.h
  src/uct/cuda/cuda_copy/cuda_copy_ep.c
  src/uct/cuda/cuda_copy/cuda_copy_iface.c
  src/uct/cuda/cuda_copy/cuda_copy_iface.h
  src/uct/ib/dc/dc_mlx5.h
  src/uct/ib/rdmacm/rdmacm_cm.h
  test/gtest/ucp/test_ucp_wireup.cc
  test/gtest/ucp/test_ucp_worker.cc
Labels: Cleanup

#9667 UCM/PTMALLOC286: added UCS_V_UNUSED attribute to nfences
  src/ucm/ptmalloc286/malloc.c
Labels: Bugfix

#9681 DOCS: Clarify `ucp_put_nbx` and `ucp_get_nbx`
  src/ucp/api/ucp.h
Labels: Documentation

#9684 UCT/IB/DC: bugfix - dci_pool_index have only 3 bits in ep->flags (it's max value is 15)
  src/uct/ib/dc/dc_mlx5.c
  src/uct/ib/dc/dc_mlx5_ep.h
  test/gtest/uct/ib/test_dc.cc
  test/gtest/uct/uct_test.cc
  test/gtest/uct/uct_test.h
Labels: Ready for Review
