Repository openucx/ucx, pull requests merged in 2025-01, with the labels that each got.

#10410 UCT/IB/MLX5/RC: skip cyclic_emulated when using ddp
  src/uct/ib/mlx5/rc/rc_mlx5_iface.c
Labels: Bugfix, Ready for Review

#10413 TEST/GTEST/UCT: Fix retry when it cannot allocate MEMIC memory - add scoped_log_handler
  test/gtest/uct/uct_test.cc
Labels: Approved pending CI

#10400 AZP: Align build OS list with the support matrix
  buildlib/pr/main.yml
Labels: Ready for Review

#10270 UCT/IB/MLX5/DC: Change DCIs array to pointers - dynamic array grow
  src/ucs/datastruct/array.h
  src/uct/ib/base/ib_device.h
  src/uct/ib/mlx5/dc/dc_mlx5.c
  src/uct/ib/mlx5/dc/dc_mlx5.h
  src/uct/ib/mlx5/dc/dc_mlx5.inl
  src/uct/ib/mlx5/dc/dc_mlx5_ep.c
  src/uct/ib/mlx5/dc/dc_mlx5_ep.h
  test/gtest/uct/ib/test_dc.cc
Labels: Bugfix

#10135 UCT: check reachability using the routing table
  AUTHORS
  buildlib/tools/build_static.sh
  buildlib/tools/test_wire_compat.sh
  contrib/test_jenkins.sh
  src/ucs/Makefile.am
  src/ucs/sys/netlink.c
  src/ucs/sys/netlink.h
  src/ucs/sys/sock.c
  src/ucs/sys/sock.h
  src/uct/ib/base/ib_iface.c
  src/uct/ib/base/ib_iface.h
  src/uct/tcp/tcp_ep.c
  src/uct/tcp/tcp_sockcm_ep.c
  test/gtest/common/test_helpers.cc
  test/gtest/ucs/test_sock.cc
  test/gtest/uct/ib/test_ib.cc
  test/gtest/uct/tcp/test_tcp.cc
Labels: Ready for Review
