Repository openucx/ucx, pull requests merged in 2025-02, with the labels that each got.

#10417 AZP/Perf: Update the PerfX code used by the perf pipeline
  buildlib/azure-pipelines-perf.yml
Labels: Ready for Review

#10475 TEST/GTEST/UCT: Increase retries and add random sleep when MEMIC allocation fails
  test/gtest/uct/test_atomic_key_reg_rdma_mem_type.cc
  test/gtest/uct/uct_test.cc
Labels: Approved pending CI

#10418 UCT/GGA: move global attach lock to MD
  src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
  src/uct/ib/mlx5/gga/gga_mlx5.c
  src/uct/ib/mlx5/ib_mlx5.h
Labels: Ready for Review

#10504 UCT/IB/MLX5/DC: pass pool_index to dci_create, dci_find: check dci is valid
  src/uct/ib/mlx5/dc/dc_mlx5.c
  src/uct/ib/mlx5/dc/dc_mlx5.h
  src/uct/ib/mlx5/dc/dc_mlx5_ep.h
Labels: Bugfix, Ready for Review
